### ISSUE TITLE
More than one migrations configuration type was found in the assembly 'NuGetGallery.Website'.

### ISSUE THREAD

**Issue by pfaithlin** [NuGet/NuGetGallery#1108]
I'm setting up Database for first time and followed below steps thru Package Manager.
I got the Migrations folder created with bunch of cs files with timestamp.
But when I ran **Update-Database** command to create the DB to my localDB getting below error:

_PM> Enable-Migrations_
Checking if the context targets an existing database...
Code First Migrations enabled for project Website.

**_PM> Update-Database -Debug -Verbose**_
Using StartUp project 'Website'.
Using NuGet project 'Website'.
Specify the '-Verbose' flag to view the SQL statements being applied to the target database.
**More than one migrations configuration type was found in the assembly 'NuGetGallery.Website'. Specify the name of the one to use.**
This I could do after looking at #1105 

Is there any info/link to resolve this?

**Comment by AndrewSpec** [comment]
I have the same problem today but excluding Configurations.cs don't resolve this problem.

**Comment by cmcknz77** [comment]
I'm having exactly this problem today... I don't understand how to 'exclude' the configurations.cs short of deleting it (which causes the project to fail). Or if I should be able to see somewhere within the project the correct 'migrations configuration type' to specify on the command-line in order to get the database created in SQLExpress.
