### ISSUE TITLE
An InvalidOperationException gets logged when attempting to post invalid form data from the Contact Support page

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1803]
To repro:
1.  Log in and go to the Contact Support page for a package you own.
2.  Without typing anything in the message textbox, submit the form.
3.  Review the error logs for details.

RESULT:  You'll see an InvalidOperationException logged at the time you post.
EXPECTED:  THis error is benign, and doesn't affect the user's experience on the site.  For this reason, we ought to get rid of it in the name of keeping our error logs clean.

**Comment by robertmuehsig** [comment]
I'm not sure which error log is described in the issue, but with the current NuGet Gallery you can't submit the form without typing anything. Even if you try to include some bad chars like </html> no exception is thrown.
![image](https://cloud.githubusercontent.com/assets/756703/12081105/74a0b7e2-b270-11e5-8829-71b89bfe4607.png)

If you disable Javascript, the weird captcha system comes in, so... I don't think anybody does that anymore in real life.

Maybe this issue is already solved.
