### ISSUE TITLE
Can Gallery be put on top of Feed?

### ISSUE THREAD

**Issue by bc3tech** [NuGet/NuGetGallery#2372]
I can't find anything in the doco on how to take the NuGet Gallery and have it pull in as its source a feed that was built using the steps [from here](http://docs.nuget.org/create/hosting-your-own-nuget-feeds#creating-remote-feeds).
We've already got an internal nuget server built using this method, and I'd like to bring the "prettiness" of the NugetGallery to it w/o having to pull & push everything to a new repo.

If this *is* possible, might I suggest a spot somewhere in the doco on how to do it? Thanks!

**Comment by maartenba** [comment]
You would have to upload the existing packages I'm affraid. One way f doing this is this:

1. Open a command prompt in your NuGet.Server's packages directory
2. Run `nuget push * <api key of new gallery> -Source <url of new gallery>`

This will upload all packages at once to the new gallery you deployed.

**Comment by bc3tech** [comment]
Severe bummer. I spent some time yesterday trying to make this happen as I waited for a response; my thinking was - if the default installation of Gallery pulls from the Nuget.Org feed, how is it doing this? It must be looking at the feed, right?

**Comment by angelwang** [comment]
Not sure if this is the right way, but after clear "Gallery.ServiceDiscoveryUri" key value in the web.config, it does not search the feed in official nugget server anymore, now my private nugget gallery only list internal published packages. 

Here is the key, it was pointing to the nugget api: 
 <add key="Gallery.ServiceDiscoveryUri" value="https://api.nuget.org/v3/index.json" />

**Comment by bc3tech** [comment]
Yup. Did that. haven't tried putting the URL to my existing feed in there though....

**Comment by ChrisSfanos** [comment]
Thanks for the posting - as this is a support issue, can you email support@nuget.org or post a question to StackOverflow - thanks!

**Comment by maartenba** [comment]
Seems there's some confusion here. The NuGet Gallery has its own set of packages stored in SQL database. When configured, it will build a Lucene index from that database in order to make package downloading fast.

The `Gallery.ServiceDiscoveryUri` and `Gallery.SearchServiceResourceType` settings are used by us to run NuGet.org: with the amount of packages and us running multiple servers, we wanted to not have separate Lucene indexes on each box. These two settings point to where NuGet.org can find our "external Lucene". 

More background: `Gallery.ServiceDiscoveryUri` points to https://api.nuget.org/v3/index.json. `Gallery.SearchServiceResourceType` tells the gallery to look for any URL in that document that has the "SearchQueryService" type. When both are satisfied, the gallery no longer builds its internal Lucene index but uses the external one. The setting is by no means used to connect it to other feeds.

If you want to "proxy" an existing feed, have a look at the different servers in the NuGet ecosystem - http://docs.nuget.org/Contribute/Ecosystem. I know that ProGet, MyGet, Artifactory and a couple of others provide the ability to do this.
