### ISSUE TITLE
Downloading a package from nuget.org

### ISSUE THREAD

**Issue by Rast1234** [NuGet/NuGetGallery#2381]
On nuget.org i have "download" button for packages only when logged in. If i have not logged in, i see "How to download" with misleading proclamation __"...there is no download link..."__

I wanted to download a package to unpack it and examine its structure. Because nuget itself downloads packages somehow, i had to google the way to download manually. Why not add download button for everyone (not logged in) or write a hint on a "How to download" page?

**Comment by maartenba** [comment]
@Rast1234 you could use the excellent NuGet Package Explorer (http://npe.codeplex.com) to search and download NuGet packages and explore their contents.

**Comment by robertmuehsig** [comment]
Small Hint, if you are logged and are using Internet Explorer you have a deep link to the NuGet Package Explorer.

![open in package explorer](https://cloud.githubusercontent.com/assets/756703/6942198/36cbdf60-d886-11e4-959b-37364e59a1fd.PNG)

It is limited to Internet Explorer because of some ClickOnce issue in other browsers. The full problem is described here: http://npe.codeplex.com/discussions/542880

**Comment by robertmuehsig** [comment]
:+1:

**Comment by Rast1234** [comment]
:+1:

**Comment by maartenba** [comment]
Added the download + open in package explorer link for all users:

![1](https://cloud.githubusercontent.com/assets/485230/6979119/0e625770-d9df-11e4-91d2-850f9344d445.png)

Next to the download link, I added a "how-to" link, which gives a quick intro to NuGet:

![2](https://cloud.githubusercontent.com/assets/485230/6979120/1299c238-d9df-11e4-85ef-b5647ffa52eb.png)

Will be live with our next deployment. Thanks for the suggestion, @Rast1234!
