### ISSUE TITLE
Version unavailable (FAKE 3.27.6)

### ISSUE THREAD

**Issue by albertjan** [NuGet/NuGetGallery#2400]
When running this command: `nuget install FAKE -nocache`

While this request: https://www.nuget.org/api/v2/FindPackagesById()?$filter=IsLatestVersion&$orderby=Version%20desc&$top=1&id=%27FAKE%27

Tells the client `3.27.6` is the latests version 

This request:  https://www.nuget.org/api/v2/Packages(Id='FAKE',Version='3.27.6')

this does return the package: https://www.nuget.org/api/v2/FindPackagesById?id=%27fake%27&$skiptoken=%27FAKE%27,%273.2.8%27

Returns a 404

@forki do you have any idea why this happens? 

Response 1st request:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<feed xml:base="https://www.nuget.org/api/v2/" xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
  <id>https://www.nuget.org/api/v2/FindPackagesById</id>
  <title type="text">FindPackagesById</title>
  <updated>2015-04-09T12:23:03Z</updated>
  <link rel="self" title="FindPackagesById" href="FindPackagesById" />
  <entry>
    <id>https://www.nuget.org/api/v2/Packages(Id='FAKE',Version='3.27.6')</id>
    <category term="NuGetGallery.V2FeedPackage" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
    <link rel="edit" title="V2FeedPackage" href="Packages(Id='FAKE',Version='3.27.6')" />
    <title type="text">FAKE</title>
    <summary type="text">FAKE - F# Make - Get rid of the noise in your build scripts.</summary>
    <updated>2015-04-09T12:20:05Z</updated>
    <author>
      <name>Steffen Forkmann, Mauricio Scheffer, Colin Bull</name>
    </author>
    <link rel="edit-media" title="V2FeedPackage" href="Packages(Id='FAKE',Version='3.27.6')/$value" />
    <content type="application/zip" src="https://www.nuget.org/api/v2/package/FAKE/3.27.6" />
    <m:properties>
      <d:Version>3.27.6</d:Version>
      <d:NormalizedVersion>3.27.6</d:NormalizedVersion>
      <d:Copyright m:null="true" />
      <d:Created m:type="Edm.DateTime">2015-04-09T06:53:31.323</d:Created>
      <d:Dependencies></d:Dependencies>
      <d:Description>FAKE - F# Make - is a build automation tool for .NET. Tasks and dependencies are specified in a DSL which is integrated in F#. This package bundles all extensions.</d:Description>
      <d:DownloadCount m:type="Edm.Int32">150969</d:DownloadCount>
      <d:GalleryDetailsUrl>https://www.nuget.org/packages/FAKE/3.27.6</d:GalleryDetailsUrl>
      <d:IconUrl>https://raw.githubusercontent.com/fsharp/FAKE/master/help/pics/logo.png</d:IconUrl>
      <d:IsLatestVersion m:type="Edm.Boolean">true</d:IsLatestVersion>
      <d:IsAbsoluteLatestVersion m:type="Edm.Boolean">true</d:IsAbsoluteLatestVersion>
      <d:IsPrerelease m:type="Edm.Boolean">false</d:IsPrerelease>
      <d:Language>en-US</d:Language>
      <d:Published m:type="Edm.DateTime">2015-04-09T06:53:31.323</d:Published>
      <d:PackageHash>GuMB137iRrnUa8RqaOfF7cR6vrnfy+KQqVylO0XhIk5R1A0WW8Iu8w6KndND1ELtMDJzegkPsjKaqX0e5ODr7g==</d:PackageHash>
      <d:PackageHashAlgorithm>SHA512</d:PackageHashAlgorithm>
      <d:PackageSize m:type="Edm.Int64">13291005</d:PackageSize>
      <d:ProjectUrl>http://www.github.com/fsharp/Fake</d:ProjectUrl>
      <d:ReportAbuseUrl>https://www.nuget.org/package/ReportAbuse/FAKE/3.27.6</d:ReportAbuseUrl>
      <d:ReleaseNotes>Added support for Mage's CertHash parameter - https://github.com/fsharp/FAKE/pull/750</d:ReleaseNotes>
      <d:RequireLicenseAcceptance m:type="Edm.Boolean">false</d:RequireLicenseAcceptance>
      <d:Tags>build fake f#</d:Tags>
      <d:Title m:null="true" />
      <d:VersionDownloadCount m:type="Edm.Int32">52</d:VersionDownloadCount>
      <d:MinClientVersion m:null="true" />
      <d:LastEdited m:type="Edm.DateTime" m:null="true" />
      <d:LicenseUrl>http://www.github.com/fsharp/Fake/blob/master/License.txt</d:LicenseUrl>
      <d:LicenseNames m:null="true" />
      <d:LicenseReportUrl m:null="true" />
    </m:properties>
  </entry>
</feed>
```

Response 2nd request:
```xml
<m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
<m:code/>
<m:message xml:lang="en-US">Resource not found for the segment 'Packages'.</m:message>
</m:error>
```

**Comment by albertjan** [comment]
@forki I was you published a new version but the problem persists.

**Comment by forki** [comment]
please pin to 3.27.5 - I don't know whats happening on nuget at the moment. /cc @maartenba

**Comment by filipw** [comment]
I can't install FAKE anymore as well

**Comment by forki** [comment]
I'm unlisting latest packages in order to reduce the pain.

**Comment by maartenba** [comment]
The NuGet index has been rebuilt, listing packages should make them available now (bear in mind the up-to-10-minute delay that is possible).

**Comment by albertjan** [comment]
Confirmed, closing: 

```sh
C:\...\shared [dev +1 ~0 -0 !]> nuget install fake -version 3.28.0
Installing 'FAKE 3.28.0'.
Successfully installed 'FAKE 3.28.0'.
```

**Comment by albertjan** [comment]
@maartenba what is the desired channel to communicate about these kinds of things? And where does nuget comunicate about service interruptions like this. Nuget is an essential part in our daily workflow including deployments. I was a bit frustrating :smile:, a bit more information would have gone a long way in resolving this.

**Comment by filipw** [comment]
same here, our builds didn't work and it was an expensive, tangible outage in the develeopment process

**Comment by forki** [comment]
I hate to say that, but the only thing we as nuget users can do is to pin the versions. It completely defeats the whole idea of continuous deployment, but at least you don't have day long build failures.

**Comment by maartenba** [comment]
@albertjan Good question for @csharpfritz and @yishaigalatzer

**Comment by yishaigalatzer** [comment]
We will fix this eventually (and sooner rather than later) But practically almost always you should pin a version.@forki I disagree with you. If its your own package you should test it yourself before uploading to nuget, nuget is not your nightly build repository you should stop using it like that. We use myget or a local feed for that. Prereleases on nuget are for stable pre releases.

**Comment by forki** [comment]
Dude, the packages work. It's only the delivery mechanism that's broken.

**Comment by yishaigalatzer** [comment]
About where to communicate - you have a support link on the site, it is faster to reach our emails than a github issue. And we want to augment status.nuget.org. Infact @maartenba is looking at it. 

Generally I have a goal to make NuGet.org a LOT more stable and LOT more self service. It's not going to happen overnight. At the moment we are focused mostly on releasing nuget 3.0 with visual studio 2015, while still doing work on the server. I expect this balance to shift to we can dedicate more time to the server. We will share roadmap with what exactly we plan to do around that timeframe (or before if when we solidify it)

**Comment by yishaigalatzer** [comment]
@forki read my comment. It's not your nightly shares server. Can't force you to stop, but your really should.

**Comment by forki** [comment]
Dude we don't provide nightly builds. All these versions solve real world issues (coming in by pull requests), the release notes are manually edited. I start the release process manually. 
These are real versions. It's just that we release A LOT and our users like that.

**Comment by dsyme** [comment]
Agreed - these are real releases. @forki has found a fantastic methodology and rhythm for incremental, fast turnover, high-quality tool releases, and the adoption rates of FAKE and Paket are going through the roof partly as a result of this methodology.

**Comment by khellang** [comment]
If you have an automated system to do your packaging and deployment, and perfectly good code (which people would benefit from) hitting master, why wouldn't you ship it? Even if it means multiple times a day?

About communication; I think what you're saying is really sad, that "it is faster to reach our emails than a github issue". Think about how many people have access to that conversation vs. an issue on GitHub. Not very OSS at all. No transparency.

**Comment by csharpfritz** [comment]
Some quick numbers and then thoughts:
FAKE has 1337 releases available to the public, with an average of about
110 downloads per version and a high water mark of 2905 downloads for FAKE
3.9.9 that was released in November 2014.

I agree with Yishai, NuGet.org is not a nightly build distribution center.
We can't stop you from deploying as often as you'd like to it, but I
question the value of more than 1300 releases for the typical developer.





Jeff

**Comment by csharpfritz** [comment]
There's a reason that the Support link doesn't go directly to GitHub
issues: it is intended for that one-on-one private support request.  GitHub
issues house more discussion around features or issues that effect all
users.

We are about to get a lot more transparent in our operations at the
conclusion of our effort for Visual Studio 2015, and Yishai has already
paved the way for a number of significant improvements to NuGet features
and services.

We're working on improvements all the time, and we will make this ecosystem
significantly better.



Jeff

**Comment by dsyme** [comment]
These are not nightly releases.  They are frequent incremental releases. And Nuget is most definitely a distribution center for frequent incremental releases, isn't it?  If nuget is stressed by frequent releases, then a maximum release rate could be enforced. That's better than asking users to manually moderate their release rate to some unspecified frequency.

But technically speaking nuget should be able to handle hundreds of releases per day for a package.  If FAKE is acting as a stress test for that, then that seems like a good thing for the ecosystem (even if it uncovers bugs painful for FAKE users).

**Comment by csharpfritz** [comment]
Don,

No one has said that FAKE is stressing the NuGet services.  We are capable
of handling the volume.

The question is: for the typical developer, is a catalog of more than 1300
releases something valuable to them?  Does there come a point where it
makes sense to unlist older prerelease packages or incremental releases
that should not be used in favor of more modern full-featured releases?





Jeff

**Comment by dsyme** [comment]
That sounds like something to discuss on github.com/fsharp/FAKE.  But an easy way to unlist old versions would be useful.

**Comment by khellang** [comment]
If lots of old packages are a problem for NuGet, maybe it's time to introduce some package retention policy/strategy?

**Comment by csharpfritz** [comment]
I completely agree: Lets make it easier for package owners to unlist and remove  older packages. 

We have this feature on our roadmap.



Jeff

-----Original Message-----

**Comment by csharpfritz** [comment]
I'll repeat from a prior message in this thread:  NuGet is more than capable of handling the capacity.

I question the value to the packages consumers of having hundreds of older versions. Yes, we could adopt a policy around it.  This discussion is a step in that direction, as my research indicates that FAKE has by far the most releases in the repository. It's the prime candidate to discuss exactly this type of action. 

We don't want to distract your development process or force you to remove package versions from the repository. We want to help make the NuGet gallery more valuable for your customers. 

Jeff

-----Original Message-----

**Comment by forki** [comment]
thanks @csharpfritz I'm very happy that the issues are not caused by FAKE.
Regarding older packages: Basically nobody is installing FAKE through the gallery.

https://www.nuget.org/stats/packages/FAKE?groupby=ClientName shows:

![image](https://cloud.githubusercontent.com/assets/57396/7092278/9a6ecb50-dfb0-11e4-968f-1a05773a8ea4.png)

It's all Nuget command line and "Other" (which is probably mostly Paket.exe).

The normal workflow is that people just run with the latest available version and happily use the new features and bugfixes. Only in time with incompatibilities (major release change) people pin their versions to the last major. In Paket we can use the [`~>` operator](http://fsprojects.github.io/Paket/nuget-dependencies.html#Pessimistic-version-constraint) to specify this.

This approach works very well and our customers like that.

**Comment by robertmuehsig** [comment]
The average dev will just use the most recent release and I really like the fast release cycle and this is valuable. I don't see this as an issue from FAKE, it is a NuGet.org problem IMO.

Regarding the communication: It is on you to get more community involvement. The lack of a clear roadmap since a year is really disappointing.

**Comment by yishaigalatzer** [comment]
To try and conclude this long thread.

1. @forki is shipping usable stable builds every day. People like it. enough said.
2. NuGet.org had an issue, we could have communicated better about it, and we are going to find a way to do it better. One thought is to make status.nuget.org have a message from the team if something is off. We are trying to find the best way to do it (so that is reliable).
3. GitHub issues are completely fine way to report issues, we might get to them later than email to support. Feel free to do both. Support emails reaches more people faster, GitHub is more transparent. Both are acceptable.
4. The fact that we have no roadmap for a long time is a shame, I agree. My job is to fix/improve several things with NuGet (along with @csharpfritz @maartenba and the rest of the team). At the moment we are heads down on shipping Visual Studio 2015.
5. Random list of thoughts around what a roadmap could include: Solve the upload packages problem creates an inconsistent @forki and us talked about elsewhere. Better self healing of the server, Better self service on the server (like delete pacakges), its going to take time and not going to happen overnight (not even the list of things to do in some order of priority). But rest assured that we want to move NuGet forward and your feedback is being heard.

If you have more comments or personal feedback you can always find me on twitter `@yigalatz` or on my email (I tend to respond to email faster than twitter or github, just how I am) yigalatz at microsoft com

**Comment by dsyme** [comment]
That's a really good summary, thanks for posting!
