### ISSUE TITLE
Reliability: V3 search returns XML error at times

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#2431]
We have an issue reported on the client side ( not consistent repro) that at times, search from package manager dialog throws exception. This happens since the server returns XML error ( where as the client is trying to parse the json results). On retrying it works fine. 
We need to see why this happens. A reliability test (which hits the v3 search end point in a loop with a variety of search queries) would give us some insights in to it.

**Comment by johnataylor** [comment]
Regarding running reliability tests: tests on the search should include changing the data in the underlying index at the same time as hitting the service. This is because unless the data in the index changes the state in the service is pretty much static.

Regarding the bug itself. If it turns out that this is an exception that can't be handled, the exception should be caught and returned to the client as a 500.

**Comment by johnataylor** [comment]
Updating the priority because of potential information disclosue.

**Comment by maartenba** [comment]
We now return a 500 + Internal Server Error in V2V3 search and log the exception.
