### ISSUE TITLE
NuGet.org rejects package even when Package Explorer finds no issues

### ISSUE THREAD

**Issue by forki** [NuGet/NuGetGallery#2455]
As https://github.com/fsprojects/Paket/issues/812 shows we can create a nupkg that looks good (at least for the Package explorer), but NuGet.org is rejecting it with Server Error 500 (no details).

Repro: 
* clone https://github.com/fsprojects/FsReveal/tree/develop
* run build.cmd NuGet

If I extract the nupkg then there are subfolders in reveal.js folder but package explorer is not showing these files.

![image](https://cloud.githubusercontent.com/assets/57396/7444332/de42ab92-f17d-11e4-939b-206b93a63179.png)

**Comment by yishaigalatzer** [comment]
1. The package seems to be missing a nuspec file (at least from the screenshot).
2. Tried to clone and build, build fails. Can you please take a look?

![image](https://cloud.githubusercontent.com/assets/1238711/7462360/a80bacde-f265-11e4-9942-20705b63f891.png)

**Comment by forki** [comment]
Ah sorry it's on the develop branch.

**Comment by yishaigalatzer** [comment]
The develop branch builds a `0.7.2` version of FsReveal. Can you help by stashing a package somehwere where we can get to it directly?

**Comment by forki** [comment]
yes of course. Should have done this from the beginning. 

https://github.com/fsprojects/FsReveal/blob/invalid/FsReveal.0.7.4.nupkg?raw=true

> The package seems to be missing a nuspec file (at least from the screenshot).

The screenshot is only showing a subfolder in the package. The nuspec is one level up.

**Comment by bhuvak** [comment]
@forki , is the package created using NuGet "pack" command ? I am seeing an error due to invalid zip entry (for reveal.js\css). I am looking more into it, but wanted to quickly check if it is manually zipped as nuget package ?

**Comment by forki** [comment]
thanks for looking into it. The package was built using "paket pack". But
paket is only using . NET zip functionality  and the package extracts
correctly. So it's strange that you see invalid zip entries.

Our general issue is more that we don't have a good way to check what's
wrong with a given package. I really appreciate that you take the time to
look into this. But even if we get this fixed we still would like to see a
way to verify if package is valid.

**Comment by davidfowl** [comment]
Are you putting in all of the opc goop?

**Comment by forki** [comment]
?

**Comment by bhuvak** [comment]
The sub folders "css","js","test","lib","plugin" and "test" inside "reveal.js" folder  has "\" as path separator instead of "/".During package upload we ensure that "/" is used as separator to support non-windows OS. 
That's the reason why opening the package in package explorer doesn't show those folders. The same happens while trying to "install" it using nuget.exe.
I tried packing the contents using nuget pack and it get uploaded properly (in my local setup).

While creating this Zip archive was a different path separator provided for these sub folders for any chance ?

On a related note, I am working on showing proper validation error during upload process instead of 500 error.

**Comment by yishaigalatzer** [comment]
@forki you are supposed to pack with OPC rather than zip APIs. Look at nuget.exe pack functionality.

**Comment by forki** [comment]
@bhuvak thanks a lot.
