### ISSUE TITLE
Provide a more descriptive error message when uploading a package without a description

### ISSUE THREAD

**Issue by danroth27** [NuGet/NuGetGallery#2483]
If I try uploading a package without a description or an author then I get the following generic error:

![package-upload-failed](https://cloud.githubusercontent.com/assets/1874516/7695943/1db5b58c-fdac-11e4-94d2-b3837492ef8b.png)

It would be great to have a more descriptive error message saying that the description or author are missing.

**Comment by robertmuehsig** [comment]
I tried to upload a package and the issue is still there - currently I guess it would result in a heavy exception:

value cannot be null

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.NullReferenceException: value cannot be null

Line 52:             // Store description so we can show them in search results
Line 53:             field = new Field("Description", Package.Description, Field.Store.YES, Field.Index.ANALYZED);
Line 54:             field.Boost = 0.1f;

I thought I saw some validate package commits - will try to take a look at it this week.
