### ISSUE TITLE
V3 search and autocomplete throw NullReferenceException on index swap

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/NuGetGallery#2520]
Pingdom checks for search (autocomplete - id) and search (v3 - empty) fail sporadically. Root cause seems to be an exception being thrown every now and then:

```
[KeyNotFoundException: The given key was not present in the dictionary.]
   System.Collections.Generic.Dictionary`2.get_Item(TKey key) +11016965
   NuGet.Indexing.OpenBitSetLookupFilter.GetDocIdSet(IndexReader segmentReader) +51
   Lucene.Net.Search.CachingWrapperFilter.GetDocIdSet(IndexReader reader) +114
   Lucene.Net.Search.IndexSearcher.SearchWithFilter(IndexReader reader, Weight weight, Filter filter, Collector collector) +61
   Lucene.Net.Search.IndexSearcher.Search(Weight weight, Filter filter, Collector collector) +231
   Lucene.Net.Search.IndexSearcher.Search(Weight weight, Filter filter, Int32 nDocs) +79
   Lucene.Net.Search.Searcher.Search(Query query, Filter filter, Int32 n) +33
   NuGet.Indexing.ServiceImpl.AutoCompleteSearch(NuGetSearcherManager searcherManager, String q, String id, String supportedFramework, Boolean includePrerelease, Int32 skip, Int32 take, Boolean includeExplanation) +101
   NuGet.Indexing.ServiceImpl.AutoComplete(IOwinContext context, NuGetSearcherManager searcherManager) +410
   NuGet.Services.BasicSearch.&lt;Invoke&gt;d__7.MoveNext() +1054
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +93
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +52
   NuGet.Services.BasicSearch.&lt;&lt;Configuration&gt;b__1&gt;d__3.MoveNext() +443
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +93
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +52
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.&lt;RunApp&gt;d__5.MoveNext() +191
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +93
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +52
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.&lt;DoFinalWork&gt;d__2.MoveNext() +189
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) +69
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult ar) +64
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +415
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously) +155
```

@johnataylor Can you have a look at it? I'd think changing `OpenBitSetLookupFilter.GetDocIdSet` to the following should do the trick (check for the key, return null if not exists):

        public override DocIdSet GetDocIdSet(IndexReader segmentReader)
        {
            string segmentName = ((SegmentReader)segmentReader).SegmentName;

            OpenBitSet docIdSet;
            if (_bitSetLookup.TryGetValue(segmentName, out docIdSet))
            {
                return docIdSet;
            }
            return null;
        }

**Comment by bhuvak** [comment]
Will check it as part of search consolidation.

**Comment by maartenba** [comment]
From @johnataylor pointers: may have to do with index swap (versions table)

**Comment by johnataylor** [comment]
The assumption in the code is that auxiliary data structures are kept in sync with the index. "In sync" meaning that they are written to be indexed with the current documentID.

For example the arrays _versionsByDoc and _versionListsByDoc referenced in NuGetSearcherManager.GetVersions and NuGetSearcherManager.GetVersionsList are locked with the current Searcher between the searcherManager.Get() and searcherManager.Release() calls made in ServiceImpl.QuerySearch.

Because if that isn't true those array lookups will break. However, if this is true then wouldn't that imply the request handling thread waiting on some lock - which it shouldn't do!!!

In other words this code is incomplete: it is not ready for prime time.

Specifically, the notion of safely swapping the old for the new that exists for the IndxeSearcher in the SearcherManager.SwapSearcher should also somehow be applied to these arrays.

It would be nice to introduce that without changing SearcherManager significantly (because that was a clean port of some, apparently widely used, Java class.) But I imagine some change is inevitable. Basically this is a nice factoring - application specific logic in the derived class - generic factory stuff in the base, keeping this factoring seems goodness.

I haven't had time to look into this in detail - particularly around how to factor it in a clean way. (The model I had in mind was treating the extra data structures as some kind of attached property on the IndexSearcher, perhaps a subclass and then maybe rather than directly new-ing the IndexSearcher (SearcherManager line 66) you would call a virtual CreateSearcher() by all means the default implementation would be new IndexSearcher() just a thought - I haven't had a chance to explore that in code but this was basically what I was looking at.)

In other words from a class design point of view expecting this work to be done in Warm is tricky because you need to tie the lifetimes of objects. (As always, the governing principle on class factoring and relationships comes down to object lifetime:-))

Alternatively for the specific case of this versions lookup the code could do softer more forgiving "Try" style lookup by id (this is basically how v2 is getting away with it... probably!). This might seem reasonable here but is not the general case - so I think we need to solve this properly because the same problem presumably applies to any and all auxiliary data structures - filters or whatever. Anything that should be kept in sync with the index. I'm guessing that is what we are seeing in this specific stack (top of bug.)

Incidentally this bug will only show up sometimes when the index is churning. You'd need to be changing existing index documentIDs to see this. In other words the interesting stress test is when you stress the service and add (and remove) things from the index.
