### ISSUE TITLE
Your last edit to this package was not successfully applied

### ISSUE THREAD

**Issue by JamesNK** [NuGet/NuGetGallery#2528]
I have tried to edit Newtonsoft.Json-6.0.8 twice to add a NuGet icon and both times it has failed with this message:

Your last edit to this package was not successfully applied. You can edit the package and submit the edit again to retry the edit.

**Comment by nielthomas** [comment]
Same, can't save any changes to icon (even 128x128).

**Comment by yishaigalatzer** [comment]
Thanks for reporting, we believe we already fixed this and deployed last Friday June 8th 2015.

Please let us know if you still see it. Assigning to  @RanjiniM to validate 100% and provide the commit hash

**Comment by RanjiniM** [comment]
There were 2 issues.

1. Null Reference Exception was fixed with this commit - https://github.com/NuGet/NuGet.Jobs/commit/80982b2caad12a1f0c2716795c4dbf62fb74d541

2. When deployed to the VM, this job had binary mismatch that caused it to fail after this commit. The deployment issue doesn't have a commit but it is fixed and up/ running now.
