### ISSUE TITLE
Incorrect version showing

### ISSUE THREAD

**Issue by cardinal252** [NuGet/NuGetGallery#2541]
If I search for "Glass.Mapper.Sc" from within Visual Studio I do not see the same version as searching from nuget.org. Nuget.org is correctly showing the latest version where Visual Studio's seems to be behind.

**Comment by yishaigalatzer** [comment]
The right repo to file this issue is home. Moved to https://github.com/aspnet/Home/issues/670

Please let us know what version of visual studio and nuget extension you are using.

**Comment by bhuvak** [comment]
@cardinal252, it happens because when searching for package from visual studio UI, the packages are filtered based on target framework of the current project. Looks like the latest version of "Glass.Mapper.Sc" ( 4.0.1.5) doesn't support "net40" or "net45" and hence the next latest version is picked.
