### ISSUE TITLE
Bring back the old NuGet Package Manager

### ISSUE THREAD

**Issue by Daniel15** [NuGet/NuGetGallery#2603]
Sorry, I know this is the wrong place for this feedback, I just wasn't sure where to submit feedback for the Visual Studio extension.
___
The NuGet Package Manager in Visual Studio 2015 is, in a word, terrible. It's full of bugs and generally performs significantly worse than the version in Visual Studio 2013. I was hoping that it would improve by the final release of VS2015, but it doesn't seem to have seen much improvement. It has an average rating of [less than 1.5 out of 5 stars](https://visualstudiogallery.msdn.microsoft.com/5d345edc-2e2d-4a9c-b73b-d53956dc458d/), compared to [4.5 out of 5 for the old version](https://visualstudiogallery.msdn.microsoft.com/4ec1526c-4a8c-4a84-b702-b21a8f5293ca). Please consider getting the VS2013 version to run on VS2015, or at least fix the VS2015 version  so it's on par with the VS2013 version.

Thank you.

**Comment by TommasoScalici** [comment]
Following this issue.
I thought I became stupid because I'm trying out the new NuGet Package Manager and I'm not able to install packages even in new projects created from scratch.
I tried creating my own package, something very simple with a single PCL *.dll and tried installing in a UWP project: fail

At this point I stopped testing further because is clear that something very basic is broken here.

**Comment by LogikBlitz** [comment]
The new UI is very confusing and the installation of packages often silently fails.
I have often been forced to using the manager console instead to install and update packages.
Please bring back the ability to use to old UI, which had it's drawbacks but at least was very clean in its design.

**Comment by NickCraver** [comment]
I'm not voting for yanking it (mostly because that's just not feasible at this point), but I'd like to echo the big step backwards on usability on the new UI. Every Stack Overflow developer I've talked to agrees. I agree the 2013 UI was more usable and cleaner, but that's not actionable feedback. Let me enumerate several specific issues here.


1. One big complaint I had with both old and new UI was the lack of upgrade visibility. This was eventually fixed in 2013 but has regressed in 2015. Unless you're using a file store on disk, the "installed version" never appears. I have to go find it myself. I can't tell if this is a minor or major upgrade version, etc. Here's what I mean: ![http://i.stack.imgur.com/L7BPm.png](http://i.stack.imgur.com/L7BPm.png) See how installed version is blank? I can't get this to work in any combination of dropdowns, searches, etc. In essence, this has been re-broken.

2. The 2015 version simply breaks more. For instance, just now I was unable to reach out internal NuGet server which breaks installs for **all** packages. Regardless of their source. I just ran a test where I started a ASP.Net MVC 5 project (testing something for David Fowler) and tried to install `Microsoft.Owin.Host.SystemWeb`. This was nothing special, just the first search result for "owin", a test case off the top of my head. It did not install from `nuget.org` because *another* package source was down (which by the way is defined lower in the list). Here's what happened there:  ![http://i.stack.imgur.com/tDxcY.png](http://i.stack.imgur.com/tDxcY.png) [Here's the corresponding restore log](https://gist.github.com/NickCraver/b5ab1f52d585d06845ac)

3. Uninstalling packages is bad. 2013 wouldn't let you install things that are a dependency, but it was much more usable in this manner. What happens in 2015? Errors. Errors are the first hint that the package is used and can't be installed. Nowhere in the UI are you prevented from clicking right to error town. To test this: Create a new ASP.Net MVC project (File -> New Project -> Web -> MVC), all defaults. Now try and remove Newtonsoft. Here's what that looks like to a user: ![http://i.stack.imgur.com/R2gbA.png](http://i.stack.imgur.com/R2gbA.png) That's just not very usable. Oh, and there was no preview window even though the box is checked, it just errors.

4. This is a continuation of number 3. Why not show the dependency chain in this much larger amount of space the UI now takes? Where in here was I supposed to know it was a dependency for anything? ![http://i.stack.imgur.com/v907a.png](http://i.stack.imgur.com/v907a.png)

5. Why is the description repeated twice? It's in both the list and the detail pane.

6. The large real-estate tradeoff we've taken isn't (in my opinion) used well. For example, let's compare the old vs. the new (note the working "Installed version"):
![http://i.stack.imgur.com/xK2I3.png](http://i.stack.imgur.com/xK2I3.png) ![http://i.stack.imgur.com/3jFKt.png](http://i.stack.imgur.com/3jFKt.png) Why not show a dependency graph in there instead of expanding the URLs? My point is simply: there are better uses of the space.

7. This one isn't 2015 but I'll throw it in: I can't count the number of times I've seen a dev add a custom package source only to end up with `Package source`/`http://packagesource` because they didn't click "Update" before "OK". Can we get a confirmation prompt or just have it save there? I mention this one because it's another sign that third-party feeds seem largely ignored...it's an area we've hit trouble with repeatedly.

There are more items I can't recall just now, but I wanted to at least some actionable bits here. Please take this as constructive feedback. We're not saying "this is worse" without reason...we just want it on par, then better. The UI is very important now. With the direction everything is going with larger and transient dependency trees more devs than ever will be using this interface.

**Comment by Daniel15** [comment]
Oh interesting, thought the "installed version" was not working for me because I'm messing with ASP.NET 5 and the NuGet UI didn't support it for those, or something like that. I didn't realise it was broken for other people too.

I absolutely agree with all your points @NickCraver.

**Comment by maartenba** [comment]
This issue was moved to NuGet/Home#1179
