### ISSUE TITLE
Proxy package icons that are not served over SSL

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#2613]
For example on https://www.nuget.org/packages/Microsoft.Data.OData/5.0.0.50403 there is a JS security error `SEC7111: HTTPS security is compromised by http://static.tumblr.com/hgchgxz/9ualgdf98/icon.png`

**Comment by maartenba** [comment]
https://github.com/atmos/camo/blob/master/README.md

**Comment by maartenba** [comment]
Port completed - https://github.com/maartenba/CamoDotNet
We can use this if/when we decide to implement this improvement.

**Comment by 304NotModified** [comment]
+1

**Comment by maartenba** [comment]
If still needed, [CamoDotNet](https://github.com/maartenba/CamoDotNet) is still out there :-)

**Comment by NickCraver** [comment]
Wouldn't #1074 cover this? If images are brought in and hosed by NuGet (I'm not sure why https://github.com/NuGet/NuGetGallery/issues/14 was closed?) 3 issues could be solved at once:

- Mixed Content (this one, #2613)
- HTTP/HTTPS Package Icons (#2899)
- Allow Image uploading (#1074)

I'd propose that NuGet simply grabs and re-hosts the image when a package is uploaded (this wouldn't be hard to backfill as well). This of course only happens if the URL is valid. Having an on-site way for the owner to replace the image isn't crazy either.

This also prevents leaking search data to other domains, which is currently the case for any `https://` icons. The referer header is being sent to those packages, allowing them to see which searches hit their package. I'm not sure if that's a concern or not, but seeing all the IPs, etc. of users hitting NuGet.org I wouldn't think is intentional.

Thoughts?

**Comment by skofman1** [comment]
We start work on hosting icons inside the NuGet package: https://github.com/NuGet/Home/wiki/Packaging-Icon-within-the-nupkg
Since icon url will be deprecated, insecure icon URLs will not be a problem in the future. As part of the work we will also secure icons for existing packages. More details will be shared as we work on the design.
//cc: @agr , @zivkan

**Comment by devlead** [comment]
@skofman1 How is this work progressing? Browsers are starting to complain more and more about mixed mode served content as it's clearly a security risk for MITM attacks.

I.e. Microsoft  [WindowsAzure.Storage](https://www.nuget.org/packages/WindowsAzure.Storage/9.3.3) gravatar 
![image](https://user-images.githubusercontent.com/1647294/52792254-36c49e80-306b-11e9-9fa4-1f2c6014f46f.png) 
is served over http ( `http://www.gravatar.com/avatar/425be63bdaaeeffd26d0172ed2030198.png` ) 
![image](https://user-images.githubusercontent.com/1647294/52792057-c0c03780-306a-11e9-905b-7eec66cf2278.png) 
making browsers grumpy.

**Comment by skofman1** [comment]
@devlead , work is starting now.

**Comment by skofman1** [comment]
This is done. All icons are served from nuget.org's cache. Gravatar images are proxied by nuget.org.
