### ISSUE TITLE
Allow users to contact support through authenticated support form

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/NuGetGallery#2690]
This ensures support requests are sent referencing the email address linked to a user's account (no need for user to type it in, no need for operations to verify).
There's currently no way to contact support to request e.g. account deletion other than sending an email.

**Comment by AlexBHarley** [comment]
So this is not for users contacting package owners - but for contacting support in general?

![Image of form](http://i.imgur.com/RsHva0W.png)

This is the contact page, would the form go somewhere here? I worry you'd get a lot of users just using the form instead of reading the information available.

**Comment by csharpfritz** [comment]
Perhaps.. But it takes better than having support requests logged at as bug reports and increase the amount of triage work.
