### ISSUE TITLE
NuGet.org reports TFMs incorrectly

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/NuGetGallery#2719]
by @jamesqo

I've run into a bug under the new ASP.NET 5 `project.json` format where the package version will be listed as **Windows 0.0** ([example](https://www.nuget.org/packages/Enu/)) when uploaded to the website. Steps to reproduce:

**1.**

```bash
cd ~
git clone -b nuget-snapshot https://github.com/jamesqo/enu.git
```

**2.** Change the `project.json` package ID to a different name
**3.** Open the solution in Visual Studio and build
**4.** Upload it to [nuget.org](https://www.nuget.org/) and the supported versions will be:

- DotNET 5.0
- .NETFramework 4.5
- Windows 0.0

**Comment by maartenba** [comment]
Found the issue in `NuGet.Core`, more specifically this method: https://github.com/NuGet/NuGet2/blob/dev/src/Core/Utility/VersionUtility.cs#L208

The NuGet package contains a folder name "win" which is passed to `VersionUtility.ParseFrameworkName` and returns `Windows,Version=0.0`.

Possible fixes:
* Update the client to return a more meaningful version number for this
* Update the `ParseFrameworkName` method to make use of the target framework mappings defined in `VersionUtility` (using the `NormalizeFrameworkName` method`

My guess would be the latter option is the way to fix this.

Proposed fix: https://github.com/NuGet/NuGet2/commit/99e89444931d6e4dacb68f1428eef2067e00d610#diff-429cfdb033034ab032490b1e3ab4306eR310 (test: https://github.com/NuGet/NuGet2/commit/99e89444931d6e4dacb68f1428eef2067e00d610#diff-f9c7c98c3d85f453f20ab6f5895e29baR1326)

Unfortunately, this proposed fix breaks 8 existing tests. @yishaigalatzer Please reassign this issue to someone who has a notion of possible consequences of making this change in NuGet.Core.

Would it make sense to update the gallery side to show a nice label here instead of updating NuGet.Core?

**Comment by yishaigalatzer** [comment]
Lets update the gallery, and work with @emgarten on the core fix.

Going forward we need to start thinking about getting rid of nuget.core dependency in the gallery, we are almost there in the client

**Comment by maartenba** [comment]
What should the gallery display for this one? Windows? NETCore?

**Comment by maartenba** [comment]
Relates to #2720

**Comment by maartenba** [comment]
@jamesqo @yishaigalatzer What should the gallery display for this one? Just "Windows"? "NETCore"? Other?

**Comment by jamesqo** [comment]
@maartenba Probably "Windows," you don't want people getting confused because they think a ".NETCore" package is automatically compatible with their .NET Core library.
