### ISSUE TITLE
V2V3 can't find one result

### ISSUE THREAD

**Issue by joyhui** [NuGet/NuGetGallery#2757]
V2V3:
http://int-0-v3.cloudapp.net//query?q=nganimate
Return 0 record

But we can use this to find the item.
http://int-0-v3.cloudapp.net//query?q=AnimateCss
Its desription includes the "[nganimate]".

V3:
http://api-v3search-0.nuget.org/query?q=nganimate
Return 1 record

**Comment by johnataylor** [comment]
The problem is that [ ] are not removed in the tokenization process. So the token in the index is [ngAnimate] and the query needs to match that.

The fix is to also strip the [ ] characters...  I've also stripped ( ) and { } 

Incidentally I don't see this ever working on api-v3search-0.nuget.org it didn't seem to work there when I tried it. In fact I can't see how it could have worked.

**Comment by maartenba** [comment]
Has been fixed with v2v3
