### ISSUE TITLE
V3 --> V2V3 search case sensitive?

### ISSUE THREAD

**Issue by joyhui** [NuGet/NuGetGallery#2758]
V2V3:
http://int-0-v3.cloudapp.net//query?q=httpagilitypack
return 0 result

http://api-v3search-0.nuget.org/query?q=HttpAgilityPack
return 3 result.

V3:
http://api-v3search-0.nuget.org/query?q=httpagilitypack
return 1 result.

http://api-v3search-0.nuget.org/query?q=HttpAgilityPack
return 3 result.

**Comment by johnataylor** [comment]
Not all fields are tokenized in the same way. Comments here are in particular reference to the Description field but may apply to others.

This is happening because HttpAgilityPack is being tokenized with camel case, then shingled 2 deep and then lowercased. The original string is not included in the tokens. For example "HttpAgilityPack" tokenizes as "httpagility" and "agilitypack" which is fine except the missing token is "httpagilitypack" so a query for this will return no results. Query for each of the other tokens works fine.

As does a cased query - but because it is tokenized in the same way i.e. it is really a query for either "httpagility" OR "agilitypack"

The bug is that the original term should always be included in the token stream. (Possible add this ability to the CamelCaseTokenizer)

**Comment by maartenba** [comment]
Tested and verified working. (will now return 3 results everywhere)
