### ISSUE TITLE
Relevance sorting in the gallery produces strange results

### ISSUE THREAD

**Issue by Knagis** [NuGet/NuGetGallery#2842]
See for example https://www.nuget.org/packages?q=Tags%3A%22CommonMark%22

The results are basically in reverse from what I would expect to be the correct ordering:
1. CommonMarkSharp, 2014-09-17, 852 downloads
2. Pvc.CommonMark, 2014-10-21 212 downloads 
3. CommonPlex, 2015-10-19, 323 downloads 
4. CommonMark.NET, 2015-10-23, 17,348 downloads

How is a package that has not been updated for more than a year and has <1000 downloads more relevant than a library with regular updates and 17K downloads?

See also https://www.nuget.org/packages?q=markdown - the actual packages one is probably looking for is MarkdownDeep (found only on the second page) or MarkdownSharp (on the third page though it has 707K downloads) but almost certainly not the ones that are displayed on the first page.

**Comment by Knagis** [comment]
Are there any plans on improving the search relevance calculation? The two examples I mentioned are still valid.

**Comment by maartenba** [comment]
Soon ☺

**Comment by yishaigalatzer** [comment]
@Knagis working on it https://github.com/NuGet/NuGet.Services.Metadata/pull/69

I'll try to embed the boost by last updated (or reverse boost for packages that are stale). Your issue is fixed in this branch (I'm going through the issues to see how it affects the reports). This is not integrated back, so you can just see the json response from the backend search service

![image](https://cloud.githubusercontent.com/assets/1238711/15089087/d7e7e482-13b0-11e6-8b7c-f80bd2e8ca8f.png)

**Comment by maartenba** [comment]
For "Tags:CommonMark", the result is now on the first page. Still some optimization to do but this is definitely better :-)

(https://www.nuget.org/packages?q=Tags%3A%22CommonMark%22 - refresh a couple of times if the package does not show up)

We will be tweaking this further in the coming time.
