### ISSUE TITLE
Raw markdown is shown in documentation description

### ISSUE THREAD

**Issue by seansaleh** [NuGet/NuGetGallery#2915]
On this page http://docs.nuget.org/consume/package-restore/migrating-to-automatic-package-restore users see a markdown url link not an html link
It looks like markdown in the description of the document is not processed

**Comment by xavierdecoster** [comment]
I'm not seeing any malformed URL on that page. Could you perhaps highlight the paragraph or source code line on this page: https://github.com/NuGet/NuGetDocs/tree/master/NuGet.Docs/Consume/Package-Restore/Migrating-to-Automatic-Package-Restore.md

Even better would be if you could click the Edit button on that GitHub page and submit a pull request for it :) Closing the issue here, but if I missed it, feel free to reopen.

**Comment by maartenba** [comment]
Fixed, thanks for reporting!
