### ISSUE TITLE
Capture ODataException for unsupported queries

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/NuGetGallery#2916]
People are querying the v2 feeds with unsupported OData functions. These result in the gallery throwing ODataExceptions internally.

We should capture these and return BadRequest, and avoid logging these in Application Insights to reduce clutter.

* [x] Microsoft.Data.OData.ODataException in `SearchHijacker.IsHijackable` (*could not find property 'IsCached' on type 'NuGetGallery.OData.V2FeedPackage'* and *the 'substringof' function cannot be applied to an enumeration-typed argument*)
* [x] System.NotImplementedException in 'SearchHijacker.IsHijackable' (*unknown function 'cast'*)
* [x] Microsoft.Data.OData.ODataException: *Syntax error at position 9 in 'toupper (Id) eq '....'* (happens because of the space between `toupper` and `(`)

**Comment by yishaigalatzer** [comment]
I want to suggest adding validation, rather than catching the ODataException and converting it to 400 blindly.

So still return 400 to the users in all these scenarios (with a good error message), and hiding the things we don't care about from appinsights, but still show the ones we don't know about.

I'm not 100% convinced on my suggestion :) So consider it an ask for discussion on the subject nothing more.

**Comment by maartenba** [comment]
@yishaigalatzer Agreed - these are three good examples that should just be caught and not bubble up into our logging. But indeed other varieties we still want to see.

**Comment by maartenba** [comment]
@xavierdecoster can we prioritize this one a bit? Would be good to have these errors gone from the logs :)

**Comment by maartenba** [comment]
@xavierdecoster this one was fixed right?

**Comment by xavierdecoster** [comment]
They no longer show as 500's and return 400 BadRequest instead now.
