### ISSUE TITLE
api-v3search-0.nuget.org => authors are not populated

### ISSUE THREAD

**Issue by MscrmTools** [NuGet/NuGetGallery#3036]
Trying with this query : https://api-v3search-0.nuget.org/query?q=tags:XrmToolBox

Authors are never populated whereas I know they are in respective packages

**Comment by maartenba** [comment]
We have switched over (for 90%) to https://api-v2v3search-0.nuget.org/query?q=tags:XrmToolBox where author info is included. The URL you mention will be decommissioned in the coming weeks.

**Comment by MscrmTools** [comment]
Thank you very much for this feedback!

**Comment by rappen** [comment]
@maartenba This may be a stupid question - but I have failed hard when trying to find documentation for the API... Do you have a link? :)

**Comment by maartenba** [comment]
@rappen We have docs high on our list of things we want to provide, but there are some API changes we may want to make before doing so :)

**Comment by rappen** [comment]
@maartenba  :+1: Thanks.
Meanwhile..... should it be possible to use the ``@id`` property of the returned repo from e.g. this request https://api-v2v3search-0.nuget.org/query?q=id:Cinteros.Xrm.FetchXMLBuilder ?
The ``@id`` property is returned as https://api.nuget.org/v3/registration0/cinteros.xrm.fetchxmlbuilder/index.json
Pasting it in a browser works fine, but trying with an ajax request returns ``parsererror Unexpected token :`` (if trying as jsonp and crossDomain) or ``Access-Control-Allow-Origin`` error otherwise.
Any clues? (and sorry for expanding this thread a bit...)

**Comment by maartenba** [comment]
We don't have CORS enabled it seems... Feel free to open a fresh issue for that :)
