### ISSUE TITLE
Gallery UTs take a long time

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3107]
Tests in NuGetGallery.SearchClient.RetryingHttpClientWrapperFacts take minutes to complete. UTs should be fast.

**Comment by shishirx34** [comment]
`LoadBalancesBetweenValidUrisForGetStringAsync` and `LoadBalancesBetweenValidUrisForGetAsync` tests run into infinite loop when the returned RequestUris don't match the validUris. RetryingHttpClientWrapper is returning Request URIs(one with https, I have seen this happen often, not always):

Actual:
```
{http://www.microsoft.com/}
{https://www.bing.com/?toHttps=1&redig=414F637CC2A1431BACF5E4B0D0F90FF0}
```

Expected:
```
{http://www.microsoft.com/}
{http://www.bing.com/}
```

Apart from the test bug(which causes inifinite loop), the tests are failing due to mismatch of these URIs. I am not yet fully familiar with the code hence not sure if just validating the host for Uris is a sufficient test case fix. I will send out a PR and get feedback on understanding what the correct validation would be here.

**Comment by maartenba** [comment]
These are more of an integration test, so not sure if they should be part of the UT suite (although they test a critical path in the gallery code base).

Regarding the loop bug, feel free to fix.
