### ISSUE TITLE
Gallery should verify package correctness before upload

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3108]
Related to the failures in HandlePackageEdits job: https://github.com/NuGet/NuGetGallery/issues/3102

To prevent those failures, the gallery needs to verify package correctness using the same logic as done in the client.

**Comment by shishirx34** [comment]
This issue seems to be fixed with the addition of URL validation on nuget gallery by this https://github.com/NuGet/NuGetGallery/pull/3139, other than that I think we want to allow empty license url on the Gallery. I am not sure if there are any other package correctness verification required on the gallery.
@skofman1 do you think this issue could be closed?

**Comment by maartenba** [comment]
Check with @emgarten, we may also want to replace packageidvalidator in both gallery and job with the validator that is i the client

**Comment by xavierdecoster** [comment]
Related issue for package id validation: https://github.com/NuGet/NuGetGallery/issues/3142

**Comment by skofman1** [comment]
@yishaigalatzer wanted to leave the gallery validation as is, but to make sure the HandlePackageEdits job validation is aligned with the gallery. I think this issue can be closed.

**Comment by shishirx34** [comment]
This PR: https://github.com/NuGet/NuGet.Jobs/pull/60 aligns the package edits same as gallery. Will close this issue, since #3142 tracks the changes needed to add package id validation.
