### ISSUE TITLE
Indexing of tags appears to have a break

### ISSUE THREAD

**Issue by drewgil** [NuGet/NuGetGallery#3168]
--from support request SR-473

Packages from sotech (https://www.nuget.org/packages?q=sotech) have tags, but clicking on them does not yield a list of packages with that tag. Also, in the list this list, the tags on the line items don't match the tags in the packages. For example, https://www.nuget.org/packages/DOTSAddressValidationCanada2/ has a number of tags but we don't see them in the above list's line items.

Click on the DOTSWebServices tag in this package and we get an empty list, even though there should be 6 packages listed:
https://www.nuget.org/packages/DOTSAddressValidationCanada2/
https://www.nuget.org/packages/DOTSAddressDetective/
https://www.nuget.org/packages/DOTSEmailValidation3/
https://www.nuget.org/packages/DOTSAddressValidationPlus/
https://www.nuget.org/packages/DOTSGeocoderCanada/
https://www.nuget.org/packages/DOTSGeocoderUS/

@qianjun22 @maartenba

**Comment by scottbommarito** [comment]
It appears that every tag after and including `DOTSWebService` gets removed from the list of searchable tags. Probably some issue here with how `DOTSWebService` is handled by our tag infrastructure.

**Comment by maartenba** [comment]
Investigation shows that:
* The packages were originally uploaded without tags
* The packages were then edited via the NuGet.org website to add tags
* The original binary was cached on our CDN, and the feed2catalog job would always use this cached version instead of the updated binary, hence not recognizing tags

Here are two PR's that will fix this: 
* https://github.com/NuGet/NuGet.Services.Metadata/pull/82
* https://github.com/NuGet/NuGetGallery/pull/3171

**Comment by maartenba** [comment]
Fixes have been merged, although it will be a bit before this hits production.

If you want to work around this issue, make sure to edit your .nuspec files and add tags during upload (instead of editing the package via the NuGet.org UI).

**Comment by maartenba** [comment]
Clsoing the issue for now, this will resolve itself in the coming weeks. Thanks for reporting!

**Comment by maartenba** [comment]
This should now be fixed.
