### ISSUE TITLE
Enable NuGet Account Deletion workflow

### ISSUE THREAD

**Issue by karann-msft** [NuGet/NuGetGallery#3204]
Status: **Implemented**

Issue to track new feature work around enabling NuGet Account Deletion workflow.

Here is the [link to the spec](https://github.com/NuGet/Home/wiki/NuGet-Account-Deletion-Workflow).

Feel free to comment below with your feedback.

**Comment by tomkerkhove** [comment]
Spec looks good to me, only question I have are
- **Will I as consumer still be able to restore/install the package?** I should not be impacted because the owner deleted his account imo.
- **Can it be transferred to another owner after the fact?** Imagine that this is a big community project and the owner just deletes his account - Can somebody pick it up later on again to bring new life to it?

**Comment by anangaur** [comment]
> Will I as consumer still be able to restore/install the package?

Yes. As the spec mentions, the packages will be orphaned but still be available (though unlisted)

> Can a package be transferred to a new owner after the fact? 

This is out of scope for the spec. However a very viable scenario. We need to come up with a plan - TBD. /cc: @karann-msft

**Comment by karann-msft** [comment]
@tomkerkhove, Can a package be transferred to a new owner after the fact? - yes it is possible.
