### ISSUE TITLE
Hosted Nuget.Server returning 500 on push

### ISSUE THREAD

**Issue by taschmidt** [NuGet/NuGetGallery#3230]
This worked before but I don't know what changed.  I tried upgrading to the newest package (NuGet.Server v2.11.2).  Listing packages seems to work fine but a push returns a 500.  The response doesn't give me any more detail than that.  Failed request logging in IIS wasn't any more helpful either.  Is there something I can do to troubleshoot this further?

**Comment by taschmidt** [comment]
Disregard.  I fixed this by disabling WebDAV.

**Comment by Outlivier** [comment]
I had the same problem with nuget.server 2.11.2 : Removing the webdav handler and module in web.config is not sufficient enough, I had to create a second website in IIS with webdav deactivated AND be sure that the folder in wich are the nuget.server asp sites is not in a folder where WevDav exists because of our default website.
Maybe the [documentation](https://docs.nuget.org/ndocs/hosting-packages/nuget.server) should emphasis on the webdav Incompatibility as it's hard to troubleshoot.
