### ISSUE TITLE
When changing a password user shouldn't re-enter the same password

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3295]
Please work on defining the minimal set of rules require here?

Example:
Should we preserve the last few passwords and prevent them?
Should we prevent similar passwords as well?

CC @blowdart

**Comment by shishirx34** [comment]
@skofman1  - Is this task still on defining the rules? Or is this feature ready to be implemented with minimal requirements?

- Preventing users from reusing their old password should be fairly straightforward. What about the case when a user is trying to reset a password if they have forgotten their password? In that case I believe that we should let the users set their old password.
- If we desire to maintain a history of passwords and not let reuse the last used passwords, it could be possible.
- We cannot implement prevention of similar passwords, without storing the old passwords in raw format instead of hashed. I do not think that is the desire here and we shouldn't consider it in my opinion.

**Comment by scottbommarito** [comment]
What is the benefit to preventing users from setting the same password again? I could understand it if we forced our users to change their password at a regular interval, but given that we don't, I don't think this is likely to accomplish anything and is more likely to encourage users not to change their password.

I like @shishirx34's suggestion to allow setting a password to a previously used password when a user has forgotten their current password, but the issue there is that then any user could pretend to forget their password and set it back.

**Comment by shishirx34** [comment]
Good point @scottbommarito. I think we might want to have a story to actually expire passwords at regular interval. These changes make sense in that regards. I will start out a thread with @blowdart

**Comment by blowdart** [comment]
Studies have shown enforced password changes do more damage than good. I wouldn't implement this. 

https://arstechnica.com/security/2016/08/frequent-password-changes-are-the-enemy-of-security-ftc-technologist-says/

https://www.wired.com/2016/03/want-safer-passwords-dont-change-often/

**Comment by skofman1** [comment]
@blowdart , the proposal here wasn't to force the user to change a password, but to disallow him to enter the same password in case he chooses to change it himself, or because he forgot the password and used the reset e-mail.

**Comment by blowdart** [comment]
OK so just the current one? Similar and historical are *hard* and serve little purpose.

**Comment by skofman1** [comment]
Yeh, just the current one. Do you think it's worth doing?

**Comment by blowdart** [comment]
You  end up with a scenario that says "This password is invalid", when it meets the complexity requirements, so people will realise "Oh that's my current password, I'll stop the reset process". Meh, I think there are better things to spend your time on.
