### ISSUE TITLE
.NET Core App project.json local feed Nuget.Server getting HTTP 400 Bad Request

### ISSUE THREAD

**Issue by gencebay** [NuGet/NuGetGallery#3301]
Nuget.Server configured as a local feed for ASP.NET Core application but getting HTTP 400 when typing the package name to the project.json. The package integrated CI deployment to the our local feed. Monitoring with fiddler and getting below result:

> `http://localhost/nuget/Packages()?$orderby=DownloadCount%20desc&$select=Id&$skip=0&$top=40&$filter=(Id%20ne%20null)%20and%20substringof('CustomPackageName',tolower(Id))%20and%20IsAbsoluteLatestVersion&includePrerelease=true&$format=json`
> HTTP 400
> The query parameter '$format' begins with a system-reserved '$' character but is not recognized.

**Comment by scottbommarito** [comment]
Hey @gencebay. I looked into this yesterday and was not able to reproduce the issue.

What version of Visual Studio are you using? The query that you saw when you tried to download the package is much different than what I saw using my version of Visual Studio, which was a query using `FindPackageById()`. I also tried to run your query on the gallery (`www.nuget.org`) and it was invalid there as well, which suggests that potentially you are using an outdated version of Visual Studio (or some other IDE) which makes a query that is no longer supported.

I would also try using the NuGet Package Manager to add your dependency and see if that resolves it.

Adding a couple people from the client team since this seems to be more of a client issue than a server issue...@rrelyea @joelverhagen @zhili1208 @drewgil
