### ISSUE TITLE
Search service memory issue

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3372]
Search service suffers from memory issues.
The process reaches 12GB of memory consumption before GC collection is initiated, on machines with 14GB of memory.
This causes IIS to stop functioning, and the service is shutdown.

**Comment by joelverhagen** [comment]
This issue is on-going. 
https://icm.ad.msft.net/imp/v3/incidents/details/36045155/home
https://icm.ad.msft.net/imp/v3/incidents/details/36087582/home
https://icm.ad.msft.net/imp/v3/incidents/details/36112252/home
https://icm.ad.msft.net/imp/v3/incidents/details/36112253/home

The last case (93%) occurred on a prod USSC staging slot. This indicates an issue with index reload (given that staging slots get no traffic).
