### ISSUE TITLE
Email verification should not require being logged in

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#3384]
We had a user that created an account and forgot his password before verifying his email. As a result, he couldn't verify his email and also couldn't recover his password because it requires a verified email. We should not require being logged in for email verification so that users cannot get into this situation that locks them out of their account.

**Comment by shishirx34** [comment]
I think this is a standard practice for account verification. You need to login after you click on the URL to verify that you were the same person. Ideally one shouldn't forget their password before verification, since the url tends to expire in a day. I don't know what better way could be to ensure that you are the same person who created the account for a given email.

**Comment by scottbommarito** [comment]
@blowdart Any thoughts?

**Comment by blowdart** [comment]
This is by design (in identity). We don't want people hijacking the verification.
