### ISSUE TITLE
ImportAzureCDNStatistics fails on platforms with unicode letters

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3409]
In one of the log file the following platforms appeared: Хуй, ХУЙ
Both are a Russian word, and not a platform at all. 

There was an exception thrown by this line: https://github.com/NuGet/NuGet.Jobs/blob/master/src/Stats.ImportAzureCdnStatistics/Warehouse.cs#L1003

because both "platforms" were translated to "???"

**Comment by xavierdecoster** [comment]
@skofman1 Can you share the full stack trace of the exception, as well as the full raw record from the W3C log that caused this exception?

Either there's an issue in the parsing of the custom HTTP header we fetch from the logs, or this is a duplicate key exception caused by some string casing (in)sensitivity issue. Or something else I'm currently not thinking of (need more data).

**Comment by skofman1** [comment]
Log file: wpc_DB16_20161014_0030.log.gz

Exception: An item with the same key has already been added.
Stack trace: 
```

   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Stats.ImportAzureCdnStatistics.Warehouse.<RetrievePlatformDimensions>d__31.MoveNext() in C:\Nuget\NuGet.Jobs\src\Stats.ImportAzureCdnStatistics\Warehouse.cs:line 1003


```

**Comment by skofman1** [comment]
Further investigation showed that we use varchar in the DB, so we don't support unicode user agents:
```
CREATE TYPE [dbo].[ClientDimensionTableType] AS TABLE(
	[UserAgent] [varchar](max) NULL,
	[ClientName] [varchar](128) NULL,
	[Major] [varchar](50) NULL,
	[Minor] [varchar](50) NULL,
	[Patch] [varchar](50) NULL
)
```
