### ISSUE TITLE
NuGet.Server hints at new features nowhere to be seen

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#3437]
NuGet.Server hints at new features nowhere to be seen on the NuGet repositories (thinking "RFC/spec")..

In the PR at https://github.com/NuGet/NuGet.Server/pull/26, a comment is made:

> (...) for upcoming NuGet.Server features

Looking at the commits in that PR, this seems to hint at signed NuGet packages. More specifically, this is visible in these commits (that are reverted later):
* https://github.com/NuGet/NuGet.Server/pull/26/commits/681c898331ff313c61d98d8bc52fd50107b47ff0
* https://github.com/NuGet/NuGet.Server/pull/26/commits/631e89dd178233eadd29a2e9944a1c20772e7475
* https://github.com/NuGet/NuGet.Server/pull/26/commits/4b9726f243af153e2bd5c776f278e2fa786b75d7

Based on these commits:
* Is there an open RFC/spec/document available on what these features are, how other parties can implement them, etc.?
* Is there a client version/commit that can be used to test the server-side with?
* Will the OData format be broken for older clients? ([`Owners` becoming a collection](https://github.com/NuGet/NuGet.Server/pull/26/commits/681c898331ff313c61d98d8bc52fd50107b47ff0#diff-b4305a104b36ed12960995470c473395L28) rather than a string)

**Comment by joelverhagen** [comment]
🕵️ 👍 

> Looking at the commits in that PR, this seems to hint at signed NuGet packages. More specifically, this is visible in these commits (that are reverted later):

Yup, intentional. The PR mentioned is not supposed to introduce any new features but lay the groundwork for it (thus the revert). I think you make a good point though, these commits are more confusing to the community without the spec context than valuable to internal reviewers. I'll squash 'em out.

> Is there an open RFC/spec/document available on what these features are, how other parties can implement them, etc.?

Not open yet. The spec is still in progress.

> Is there a client version/commit that can be used to test the server-side with?

Nope, not yet. @dtivel and I are working through this in the coming year.

> Will the OData format be broken for older clients? ([`Owners` becoming a collection](https://github.com/NuGet/NuGet.Server/pull/26/commits/681c898331ff313c61d98d8bc52fd50107b47ff0#diff-b4305a104b36ed12960995470c473395L28) rather than a string)

The intention is that the OData format will not be broken. For the particular case of `Owners`, I checked the [NuGet.org](https://www.nuget.org/api/v2/$metadata), VSO, and [MyGet](https://dotnet.myget.org/F/nuget-build/$metadata) OData `$metadata` documents and none of them mentioned `Owners`. I took the leap that the schema could therefore change for NuGet.Server. Should we rethink that change?

**Comment by maartenba** [comment]
> The intention is that the OData format will not be broken. For the particular case of Owners, I checked the NuGet.org, VSO, and MyGet OData $metadata documents and none of them mentioned Owners. I took the leap that the schema could therefore change for NuGet.Server. Should we rethink that change?

Good question :-) Not sure what 2.8.6 through 4.x think about it...

Other than that, if there's an early spec it would be good to share to at least be able to review/comment before accepting it as a standard across the board.

Happy New Year @joelverhagen !

**Comment by joelverhagen** [comment]
I am going to follow up with @dtivel about the `Owners` breaking change. My current thought it that, despite the fact that nuget.org does not support this field, we should not break NuGet.Server. I think the right thing to do it to introduce a new field for our new needs.

**Comment by maartenba** [comment]
Wondering if theres'an (early) spec on this?
