### ISSUE TITLE
Licence information is not visible in NuGet.org

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3441]
According to blog here: http://blog.nuget.org/20131011/friendly-license-names.html 
we should be seeing licence info in packages page and per package pages, but we don't. Investigation required.
![image](https://cloud.githubusercontent.com/assets/16807822/21573239/d9a0eb2e-ce96-11e6-819d-fb1ca9906847.png)

**Comment by skofman1** [comment]
This happened before: https://github.com/NuGet/NuGetGallery/issues/1837
https://github.com/NuGet/NuGetGallery/issues/2396

**Comment by scottbommarito** [comment]
The `UpdatePackageLicenseReports` job is running correctly and processing new license reports from Sonatype, but it appears there have been no licenses processed since June/July. I was unable to find how any documentation on how our interaction with Sonatype works or how we enqueue packages to be processed so I have reached out to some people who may know and am waiting on their response.

**Comment by scottbommarito** [comment]
I have reached out to Sonatype and they have affirmed that the issue is on their side. I will update this issue as I get updates from them.

**Comment by scottbommarito** [comment]
Sonatype has fixed the issue.
