### ISSUE TITLE
Misleading Wiki page about self-hosting

### ISSUE THREAD

**Issue by shanabus** [NuGet/NuGetGallery#3462]
On step 13 of this page: https://github.com/NuGet/NuGetGallery/wiki/Hosting-the-NuGet-Gallery-Locally-in-IIS, it says to update **dbo.GlobalSettings** to match your desired configuration.  With this migration, 201302072118537_MovingGallerySettingsToConfiguration, it looks like columns from that table were dropped to prefer a web.config based configuration.

Should this be updated to say something like this?

13) Update the appropriate Web.Config appSettings to match your desired SMTP/Email and Branding settings

I spent a few minutes tripping over this to find that the GlobalSettings table is no longer intended for email configuration.

**Comment by scottbommarito** [comment]
Yes, those instructions are very out of date. Apologies for that. [The up-to-date instructions are located here.](https://github.com/NuGet/NuGetGallery#build-and-run-the-gallery-in-arbitrary-number-easy-steps)

**Comment by scottbommarito** [comment]
I have added a notice to the wiki page directing to the instructions in our `README.md`. I don't think we can entirely remove the outdated instructions because they concern hosting the gallery on IIS, which is not covered by the `README.md` instructions. This issue can be used for tracking of the eventual modernization of the instructions for IIS.

**Comment by skofman1** [comment]
We have additional users asking for instructions: https://github.com/NuGet/NuGetGallery/issues/5621

**Comment by skofman1** [comment]
Removed the misleading instructions.
