### ISSUE TITLE
Problem with https

### ISSUE THREAD

**Issue by coolstar68** [NuGet/NuGetGallery#3490]
Hi,
According to http://readme.localtest.me/, https is no longer supported: 

> Update: The CA revoked our certificate because they considered the private key to be compromised. I'm not entirely sure how they detected this, but they refuse to reissue it. My best idea is to get a new key elsewhere and make the key accessible but through a CAPTCHA or something so that a bot can't discover it. Any better ideas would be appreciated.
>

I believe this is the reason I get this error when running the application in visual studio:

> Hmm, we can't reach this page.
Try this
Make sure you’ve got the right web address: https://nuget.localtest.me
>

Can someone please explain how I can run the site without https?

/Regards

**Comment by joelverhagen** [comment]
Hey @coolstar68, have you tried executing the `tools\Enable-LocalTestMe.ps1` scripts from an admin PowerShell window? This actually generates and trusts a self-signed certificate rather than using the localtest.me certificate.

I would recommend following the steps in the [README.md](https://github.com/NuGet/NuGetGallery/blob/master/README.md) at the root of the repository.

**Comment by coolstar68** [comment]
YES, it worked! 
Thank you very much.
