### ISSUE TITLE
Unable to install PayPal.Forms 2.15.7 using v3 package source

### ISSUE THREAD

**Issue by mrward** [NuGet/NuGetGallery#3494]
Please read the following information before posting the issue.

To repro:

1) Create a new C# console project in Visual Studio 2015.
2) Right click the project and select Manage NuGet Packages.
3) Search for PayPal.Forms.
4) PayPal.Forms 2.15.7 is listed. Try to install it by clicking the Install button:

```
Attempting to gather dependency information for package 'PayPal.Forms.2.15.7' with respect to project 'ConsoleApplication7', targeting '.NETFramework,Version=v4.5'
Package 'PayPal.Forms 2.15.7' is not found in the following primary source(s): 'https://api.nuget.org/v3/index.json'. Please verify all your online package sources are available (OR) package id, version are specified correctly.
```

The PayPal.Forms NuGet package is very large - 178MB. The download link seems to be OK. Also the NuGet v2 package source seems to be OK - at least it tries to download it and does not report an error.

**Comment by joelverhagen** [comment]
Thanks for the report @mrward. We had a bug last year where in rare cases packages available on the V2 feed would not be available on the V3 feed. This has since been resolved. I have reflowed the package through the pipeline. I was able to install it via Visual Studio. Please re-open if you are still facing the problem.
