### ISSUE TITLE
Nugetgallery with only one administrator

### ISSUE THREAD

**Issue by anthes** [NuGet/NuGetGallery#3549]
I have installed a nugetgallery script but I'd like to be the only administrator of my repository.
So my questions are:
1) Is it possibile disable registration for other users?
2) Is it possible obscure the nugetgallery site and allow to other users only command line use (they can only download new packages not push new ones)?

**Comment by skofman1** [comment]
@anthes, this scenario has no built in support. 
One option is to fork our repo, and add support. 
Another option I can suggest is to use the available configuration to make creating new users virtually impossible. It's pretty hacky, so I'm not sure if it's the route you want to take. 
For example, you can use this configuration: https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Web.config#L85
To set an extremely complex password requirement (or even a password value known only to you), so that no one can create a new user without knowing this value.
