### ISSUE TITLE
Can not remove Microsoft accounts 

### ISSUE THREAD

**Issue by Bomret** [NuGet/NuGetGallery#3556]
I have three Microsoft accounts linked to my NuGet account. Two of those are quite old and unused and I want to remove them from being able to access my NuGet account. But whenever I use the `Remove` button on them, the following page occurs and the accounts stay linked.
<img width="966" alt="error page" src="https://cloud.githubusercontent.com/assets/246014/22863409/ce1e01d0-f13f-11e6-8e97-5d25697f364f.png">

I have tried to unlink those accounts for quite some time now (months).

**Comment by skofman1** [comment]
@ryuyu , can you please take a look?

**Comment by shishirx34** [comment]
@Bomret - Apologies on the delay in addressing this issue. I tried testing the scenario with my MSFT account and was able to successfully remove my MSFT account.

I wonder if this is unique to your account. Do you mind sending us the emails associated with the Microsoft accounts you are trying to remove. You can send us an email at support[at]nuget.org 

When you try to remove the account, which account are you signed in into? One of your MSFT account or nuget.org account(using email/password)?

Please specify this issue and my handle in the email so that it gets directed to me. At the very least I should be able to help you remove those accounts. Meanwhile, I will try testing adding multiple MSFT accounts and remove one of those accounts.

**Comment by shishirx34** [comment]
I was able to repro this issue, you need to have multiple MSFT accounts linked to your nuget.org account, which results in the issue seen above. I think I can debug and fix the issue now.

**Comment by shishirx34** [comment]
This fix cannot be verified in dev because dev doesn't have MSFT accounts enabled. Will test it on INT.

**Comment by Bomret** [comment]
@shishirx34 Do you still need input from me?

**Comment by shishirx34** [comment]
@Bomret - no need, thank you. I have the fix merged and it will be deployed to gallery next week. Will let you know.

**Comment by shishirx34** [comment]
@Bomret - The fix has been deployed to production. You should now be able to remove your associated defunct microsoft accounts. Please let us know if you see any issues.

**Comment by Bomret** [comment]
Thanks, it worked!
