### ISSUE TITLE
Getting latest version & download link from a PowerShell script

### ISSUE THREAD

**Issue by pascalberger** [NuGet/NuGetGallery#3568]
I'm looking for a way to get the latest stable version of NuGet and the appropriate download link, for packaging it in a [Chocolatey](https://chocolatey.org/) Package. While the latest version can easily be downloaded from `https://dist.nuget.org/win-x86-commandline/latest/nuget.exe`, I couldn't find a way to get the latest version number, since the version number on the [download page](https://dist.nuget.org/index.html) is filled by a client-side Knockout binding and therefore not available if the site is scrapped from PowerShell.

Of course if you are interested in maintaining the Chocolatey package yourself, as part of the NuGet build pipeline this would be even better, and I would be happy to assist you in implementing it 😃

**Comment by skofman1** [comment]
Hi @pascalberger ! Thanks for your work!
Regarding getting the version number, one solution I can suggest it running the nuget.exe you downloaded, and getting the version number from the output. 
Example:

> C:\Users\skofman>NuGet.exe
> NuGet Version: **4.0.0.2268**
> usage: NuGet <command> [args] [options]
> Type 'NuGet help <command>' for help on a specific command.
> 
> Available commands:...

Let me know if this helps.

**Comment by pascalberger** [comment]
@skofman1 While theoretically possible this would make checking for updates much more complicated. Normally we periodically just scrap a certain website for the latest current version and according download link, if the current version is newer we download the software, package it and make the package available on chocolatey.org. With your suggested approach we would for every check need to download nuget, extract it, run nuget.exe, parse its output and then proceed with packaging.

**Comment by skofman1** [comment]
@joelverhagen , any suggestions?

**Comment by joelverhagen** [comment]
@pascalberger, a couple options I can think of:

1. Get nuget.exe from the [NuGet.CommandLine package](https://www.nuget.org/packages/NuGet.CommandLine/) (`tools` directory).
1. Hit the `index.json` on our downloads website: http://dist.nuget.org/index.json

The first option is probably the best because the version number is easily readable from the .nuspec in the NuGet.CommandLine package and there is a well-known protocol for acquiring these packages 😄.

The second option is potentially easier since the download URL and version string are right there. You can simply ignore the "latest" link since we always have the latest link duplicated under a versioned link:
![image](https://cloud.githubusercontent.com/assets/94054/23281675/272155f2-f9d3-11e6-8a62-be942f056816.png)

**Comment by pascalberger** [comment]
@joelverhagen Thanks! The JSON was exactly what I was looking for (since actually I'm scripting the update for the NuGet.Commandline package :) )

**Comment by joelverhagen** [comment]
Hey @pascalberger, we've improved this experience by formalizing a list and providing a couple more guarantees here:
[http://dist.nuget.org/**tools.json**](http://dist.nuget.org/tools.json)

This is better than the index.json mentioned before because:
1. The schema is formalized and explained here: http://dist.nuget.org/tools.schema.json
1. We will never remove release versions of NuGet.exe
1. This is meant for this sort of scenario whereas index.json is really an implementation detail.

If possible, move over to tools.json to avoid issues in the future if we ever change schema of index.json.
