### ISSUE TITLE
Gallery audit trail does not show full version string

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3738]
For this package:
https://www.nuget.org/packages/NDesk.Options.Redpoint/0.2.1

Audit trail shows:
```json
      "Version": "0.2.1",
      "NormalizedVersion": "0.2.1",
```

The .nuspec of this package contains:
```xml
<version>0.2.1+git.unspecified</version>
```

Not sure if this is repro'ing with `dev` code or not. Saw it on PROD.

**Comment by xavierdecoster** [comment]
@joelverhagen What was the event for this audit record?

**Comment by joelverhagen** [comment]
Create, I think.

**Comment by xavierdecoster** [comment]
Could not find a code path that could explain this behavior in current `dev` branch (and the audit entry dates from January 7, 2017). Will try to repro on the `feature/semver2` branch (as semver2 validation rejection currently prevents from reproducing this issue on `dev`).

**Comment by xavierdecoster** [comment]
Managed reproducing against `feature/semver2` branch, so there's definitely an issue here. My current investigation leads me to the `PackageArchiveReader`. Will update this issue as I find out more.

**Comment by xavierdecoster** [comment]
The issue is in what looks like a change in behavior of `NuGetVersion.ToString`, which the gallery assumes to return the **original** version string, instead of the normalized version string.

The gallery's `PackageService` is heavily relying on that behavior when adding packages: 
https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Services/PackageService.cs#L545

Proof that `NuGetVersion.ToString` returns the **normalized** version instead for SemVer2 packages:
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Versioning/NuGetVersion.cs#L154

This means that the `Version` property of the package returned by `PackageService.EnrichPackageFromNuGetPackage` (and by extent from `PackageService.CreatePackageAsync`) will not contain the original version for SemVer2 packages, but the normalized version instead.

The fix is to use `.ToFullString` in the gallery where we mandate the original version string.

**Comment by joelverhagen** [comment]
This behavior changed from 3.4.4 to 3.5.0.

http://nugettoolsdev.azurewebsites.net/3.4.4-rtm-final/parse-version?version=0.2.1%2Bgit.unspecified
> The result of `ToString()` is `0.2.1+git.unspecified`.

http://nugettoolsdev.azurewebsites.net/3.5.0-beta-final/parse-version?version=0.2.1%2Bgit.unspecified
> The result of `ToString()` is `0.2.1`.

**Comment by joelverhagen** [comment]
In general, we should not depend on plain old `ToString()`.

We should either specify a format string, call `.ToFullString()`, or call `.ToNormalizedString()`.

**Comment by xavierdecoster** [comment]
For whatever reason - the gallery has [a unit test that asserts that the original version string from the nuspec is returned](https://github.com/NuGet/NuGetGallery/blob/master/tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs#L387 ) in the `Package.Version` property upon calling `PackageService.CreatePackageAsync`. 

This assertion relies on the fact that `NuGetVersion.ToString()` was called instead of `NuGetVersion.ToFullString()`. 

E.g. when nuspec contains a version `01.0.42.0`, the expectation in this test seems to be that `Package.Version == "01.0.42.0"`. However, the change to calling `.ToFullString()` results in a the leading zero to be stripped off and returns `1.0.42` instead, which no longer is the original version string as defined in the nuspec.

See below for change in behavior:
http://nugettoolsdev.azurewebsites.net/3.4.4-rtm-final/parse-version?version=01.0.42.0
http://nugettoolsdev.azurewebsites.net/3.5.0-beta-final/parse-version?version=01.0.42.0

It seems that neither `.ToString()` nor `.ToFullString()` can be reliably used to get a hold of the original version string as defined in the nuspec.

Note that I am uncertain about the gallery's requirement for this, I just found that there is a test that asserts this behavior. In particular the following test:
https://github.com/NuGet/NuGetGallery/blob/master/tests/NuGetGallery.Facts/Services/PackageServiceFacts.cs#L387

**Comment by xavierdecoster** [comment]
Think we should use `.ToFullString` in the gallery where we expect the *original yet sanitized* version string, and fix the tests that are failing on this.

**Comment by xavierdecoster** [comment]
Verified in DEV, fix part of `feature/semver2` branch.
