### ISSUE TITLE
NugetGallery install documentation

### ISSUE THREAD

**Issue by officeguy** [NuGet/NuGetGallery#3777]
Hi,

Can you please create full documentation of the set up and configuration for NugetGallery. 
The requirement is to have it running on IIS on an AWS EC2 instance, with a remote SQL database on AWS RDS SQL.
I have read what seems like every NugetGallery document on the internet, plus the ProNuget textbook, yet no where is there a fully documented procedure to get the site up and running.  There are many basic docs which provide hints for some parts of the configuration process but nothing that could be classed as comprehensive enough to use in a corporate setting to support our 1600 staff.
In addition, I have recently taken over support of an on-prem NugetGallery implementation and need to migrate this to AWS with the database on RDS SQL. No existing documents refer to a migration procedure.

thanks

**Comment by skofman1** [comment]
Hi @officeguy ,

NuGetGallery supports out-of-the-box to be deployed either locally (and use the file system, SQL express), or Azure blob storage (and user Azure blob storage, Azure SQL).
In order to deploy Gallery on AWS, you will need to implement storage access and SQL access yourself.
Something you might look into, is deploying NuGet.Server. This is a smaller product that wraps a file system directory and exposes a NuGet API.
