### ISSUE TITLE
Problems with Forgot password & confirmation email

### ISSUE THREAD

**Issue by OndraFiedler** [NuGet/NuGetGallery#3812]
I created account Recombee with email address support@recombee.com. The password was set to a generated strong password with the assumption that I (or someone else with access to support@recombee.com) reset it, when will need to log in in the future.

However these problems happened:
1) We never received the confirmation email (tried multiple times, checked spam folder)
2) I cannot reset the password, as https://www.nuget.org/account/ForgotPassword tells me "Could not find anyone with that email.". This is a bug in my opinion as it should work also for account which hasn't been confirmed yet. Other thing is that it returns error ("Error: Oh no, we broke something!") when an invalid email address (for example just "recombee") is used.

I tried to contact support@nuget.org but it has been a week without any reply.

**Comment by scottbommarito** [comment]
Apologies about the late response--our support request system had an issue which caused us to lose the request. I found your email and responded to it.

Regarding 2, this behavior is intentional. If your email address has not yet been confirmed yet, we do not know if it is yours and if we can send emails to it.
