### ISSUE TITLE
https://api.nuget.org/v3/index.json needs "Content-Type: application/json"

### ISSUE THREAD

**Issue by fenchu** [NuGet/NuGetGallery#3841]
Please add "Content-Type: application/json" to header, then any json filter plugin can catch this.
Now this generates a download request

```
curl https://api.nuget.org/v3/index.json

StatusCode        : 200
StatusDescription : OK
Content           : {123, 13, 10, 32...}
RawContent        : HTTP/1.1 200 OK
                    Access-Control-Allow-Origin: *
                    Access-Control-Expose-Headers: x-ms-request-id,Server,x-ms-version,Content-Length,Date,Transfer-Encoding
                    Content-MD5: fcCClYvV4jCDNa1yDUmTfg==
                    Vary: ...
Headers           : {[Access-Control-Allow-Origin, *], [Access-Control-Expose-Headers, x-ms-request-id,Server,x-ms-version,Content-Length,Date,Transfer-Encoding], [Content-MD5, fcCClYvV4jCDNa1yDUmTfg==], [Vary, Accept-Encoding].
                    ..}
RawContentLength  : 6070
```
Thanks

**Comment by scottbommarito** [comment]
I was always wondering why it generated a download request and didn't just open it in the browser.

I just looked into this and noticed that we currently have `Content-Type: application/ld+json` marked for our index page. I think the reason we did this initially is that we use RDF to generate our JSON, so we might as well mark it as JSON-LD, which it technically is. The problem here is that nothing seems to understand `application/ld+json` like it should: a smart JSON filter plugin should catch this and process it the same way, but it doesn't seem like that's the case, at least with regard to the plugins I've used in the past.

An additional confusion here is that all of our other V3 resources are marked as `application/json`, despite also being generated using RDF and thus being in JSON-LD form. Registration index pages, registration leaf pages, and flat-container index pages are all marked as `Content-Type: application/json`.

I agree that we should consider changing our https://api.nuget.org/v3/index.json to be marked as `Content-Type: application/json` to be consistent with the rest of our resources and to be more compatible with everything else.

**Comment by scottbommarito** [comment]
Discussed this some more. You should be able to tell your browser to use have a different behavior for `Content-Type: application/ld+json` and resolve the issue. What browser or json filter plugin are you using?

**Comment by skofman1** [comment]
@emgarten , @joelverhagen , is there a reason to keep index.json with Content-Type: application/ld+json?

**Comment by emgarten** [comment]
I would like to see the index use standard json content type instead of ld+json purely so I can open it in firefox.

The last comment on this mentioned it was for historical reasons: https://github.com/NuGet/NuGetGallery/issues/2663#issuecomment-246409611

**Comment by joelverhagen** [comment]
I looked at this with this @scottbommarito and it looks like it's not easy to make Firefox view `application/ld+json` in the browser. For some reason only a specific set of content types can be handled by Firefox and there's no way to override this.

This seems like a big enough usability fail to switch to `application/json`.

`application/ld+json` is technically correct and viewers _should_ be able to be configured to support this content type. Since Firefox can't, let's just fix it.
