### ISSUE TITLE
Debuging Gallery will cause browser to redirect future visit to http://localhost to https://localhost

### ISSUE THREAD

**Issue by zanqi** [NuGet/NuGetGallery#3892]
After running Setup-DevEnvironment.ps1, NuGet Gallery can be debug with F5.

Now use Visual Studio to create a new Asp.net MVC project, press F5. The browser is launched but could not opened the Home page.

**Comment by skofman1** [comment]
@zanqi , can you provide more details? What VS version are you using? Did you have a previously deployed Gallery or is it the first time you are running the project?

**Comment by zanqi** [comment]
I am using VS2017. This is the first time I am running the project.

**Comment by zanqi** [comment]
I am actually unable to connect to localhost. Anything to do with Gallery switching local development address to localhost?

**Comment by loic-sharma** [comment]
Out of curiosity, what protocol are you using to connect to localhost - HTTP or HTTPS? If HTTPS, could you try and see if HTTP works? Also, did `Setup-DevEnvironment.ps1` complete without any issues?

**Comment by zanqi** [comment]
Now I see the problem. (My default browser for VS debug) Chrome is automatically redirecting `http://localhost` to `https://localhost`. This works when debugging NuggetGallery, but not for a brand new ASP.NET project that has not enabled https

This could be due to NuggetGallery has a Strict-Transport-Security header. Once Chrome visit NuggetGallery at localhost, future visit to localhost will be redirected to https.

A temp solution from the link below is to remove localhost from Chrome's memory, but it needs to be done every time after debugging NuggetGallery
[https://superuser.com/questions/565409/chrome-how-to-stop-redirect-from-http-to-https](url)

**Comment by loic-sharma** [comment]
The Gallery does set the `Strict-Transport-Security` header - this intended behavior even on development environments. Can you verify that the `Setup-DevEnvironment.ps1` script properly created a certificate? You can do this by checking that your Local Machine's Root certificate store contains a certificate issued to `localhost` by `localhost`.

1. Open `mmc` (aka, `Microsoft Management Console`)
2. Go to `File` > `Add/Remove Snap-in`
3. Select `Certificates`, press the `Add >` button, select `Computer account`, and then press the `Finish` button followed by the `Ok` button
4. Open the `Trusted Root Certification Authorities` folder, and double-click on `Certificates`. The `localhost` certificate should be here.

Also, can you provide the full error message that you see? Chrome should provide an error code like `ERR_CONNECTION_RESET`. Lastly, could you try accessing `https://localhost` on a different browser?

**Comment by zanqi** [comment]
Yes, localhost certificate can be found in mmc.

I have no error debugging NugetGallery.

I have error when I close NugetGallery and go debugging a brand new ASP.NET project at localhost. Errors code are:
ERR_SSL_PROTOCOL_ERROR in chrome.
"we can't reach this page." In Edge

This makes sense since a new ASP.NET project don't have https enabled.

**Comment by robertmuehsig** [comment]
I'm facing the same issue and maybe I did something stupid, but I'm not sure how to fix it.

It seems I had an older localhost certifact which was valid until last month and I got the "ERR_CONNECTION_RESET". After some googling the suggestion was: Just delete the old cert and it should be ok.

I did that and executed the Setup Powershell Script again. But the issue was still the same. I noticed that there are multiple localhost certs and I deleted all of them - which was maybe stupid.

The error was not solved by this so I decided to do a repair of my local Visual Studio installation.

After that I had only one cert in my local machine store:

![image](https://user-images.githubusercontent.com/756703/46575979-40087500-c9c0-11e8-9069-f1340c3941e5.png)

Then I used the Setup powershell script with this output:


And I ended up with these certs:

PS D:\Code\GitHub\NuGetGallery\NuGetGallery> .\tools\Setup-DevEnvironment.ps1
[BEGIN] Setting up IIS Express
SITE object "NuGet Gallery (localhost)" added
APP object "NuGet Gallery (localhost)/" added
VDIR object "NuGet Gallery (localhost)/" added
[DONE] Setting up IIS Express
[BEGIN] Setting SSL Certificate
Generating a Self-Signed SSL Certificate for localhost
Using SSL Certificate: BCA12A6953CDD6A2E122432050ACD9B31F53612A
[DONE] Setting SSL Certificate
[BEGIN] Running Migrations
Updating Nuget Gallery database...
No pending explicit migrations.
Running Seed method.
Updating Nuget Gallery Support request database...
No pending explicit migrations.
Running Seed method.
Update Complete!
[DONE] Running Migrations
PS D:\Code\GitHub\NuGetGallery\NuGetGallery>


![image](https://user-images.githubusercontent.com/756703/46575987-59a9bc80-c9c0-11e8-996a-cd113b0b84aa.png)

When I started the debugging in VS it showed me these dialogs:

![image](https://user-images.githubusercontent.com/756703/46576000-8067f300-c9c0-11e8-98c1-78f91d02bbec.png)

![image](https://user-images.githubusercontent.com/756703/46576001-85c53d80-c9c0-11e8-92ca-d99ba69d3497.png)

(notice: The thumbprint is different)

So... I deleted everything again and did a reinstall a second time, but I'm more or less not one step closer to my goal :)

I think I "confused" my system somehow, because when I use "netsh http show sslcert" I see a cert, but I can't execute a netsh http delete sslcert because of "error 2".

I think I will either try to reinstall my whole machine or try a 3rd reinstall.

Maybe someone has experienced the same issue or is there a way to disable HTTPS? I know that this was possible in the past, but it seems to redirect me even when I disable the SSL stuff via the web.config setting.

**Comment by robertmuehsig** [comment]
Ok... I noticed that the IISExpressAdminCmd.exe created cert was stored under personal - to avoid the Chrome error I moved it to trusted authorities and it seems to be OK now. Still... crazy stuff. Needed some nights to resolve this issue.

**Comment by skofman1** [comment]
Hi @robertmuehsig , you can turn off SSL by changing those setting:
https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Web.config#L122 
https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Web.config#L290
