### ISSUE TITLE
Media type binary/octet-stream is bogus. Should be application/octet-stream

### ISSUE THREAD

**Issue by eric-miller-cdfw** [NuGet/NuGetGallery#4019]
A couple of years ago, the media type for NuGet package downloads was changed to binary/octet-stream. However, that is a bogus media type. The correct media type is application/octet-stream for generic binary data.

Please use a valid media type.

Ref: https://github.com/NuGet/NuGetGallery/issues/2740
Ref: http://www.iana.org/assignments/media-types/media-types.xhtml
Ref: https://www.iana.org/assignments/media-types/application/octet-stream

**Comment by skofman1** [comment]
Thanks for the feedback @eric-miller-cdfw !
NuGet changed the media type from application/octet-stream to binary/octet-stream two years ago: https://github.com/NuGet/NuGetGallery/issues/2740
The reason was to avoid IE/Edge automatically trying to open/save them as zip.
Although binary/octet-stream is not officially documented, it's widely used as the default MIME type for Azure and AWS blobs.
