### ISSUE TITLE
Why can't upload the package

### ISSUE THREAD

**Issue by librame** [NuGet/NuGetGallery#4070]
---------------------------------------------------------------------------------------------------------------
The ID of your package, 'LibrameCore' (1.1.1706.72), is similar to the title of an existing package, which can cause confusion with our users. Please modify the ID of your package and try uploading again.
---------------------------------------------------------------------------------------------------------------
But I has been uploaded successfully again.
---------------------------------------------------------------------------------------------------------------
Librame 1.1.1706.71 (this version)	0	2017年6月7日	yes
Librame 1.1.1706.51	14	2017年6月5日	yes
Librame 1.1.1705.2	21	2017年5月28日	yes
**LibrameCore 1.1.1705.1	25	2017年5月28日	no**

**Comment by shishirx34** [comment]
@librame - When you upload a package to nuget.org, we validate if your new package Id(in this case LibrameCore) does not conflict with an existing Package **ID** and **Title**, this is to ensure that we don't allow conflicting/confusing packages to be uploaded.

In your case, I see that you have one package, details below, with the title **LibrameCore** which has been unlisted.

ID: **Librame** 
Version: **1.1.1705.1**
URL: https://www.nuget.org/packages/Librame/1.1.1705.1
Title: **LibrameCore**

In your description above you mentioned you already have uploaded package **LibrameCore** I think you are mistaken, the package ID is **Librame** and not **LibrameCore**, its the title.

The good thing is since you already own the package whose title conflicts with the ID you desire, to upload a package with ID **LibrameCore**, I suggest you edit the unlisted package [Librame 1.1.1705.1](https://www.nuget.org/packages/Librame/1.1.1705.1) and rename/remove the title to NOT include LibrameCore. Once that's done, you should be able to upload a new package with ID **LibrameCore**

Let me know if you have anymore questions.

**Comment by librame** [comment]
Thank you for your solution.
The problem that has been bothering me has finally been solved.
