### ISSUE TITLE
Document V3 APIs with samples

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#4103]
The documentation page is here: https://docs.microsoft.com/en-us/nuget/api/nuget-api-v3
I see it refers to blogs that have getting started with V3 APIs.

**Comment by maartenba** [comment]
Those are client SDK docs, right?

**Comment by joelverhagen** [comment]
Yes, same question as @maartenba. We need client-agnostic docs about available V3 endpoints, describing the protocol in terms of HTTP requests and responses. Important information includes list of endpoints, high level concepts, common scenarios, etc.

For example, consider the GitHub API. There are tons of client libraries written in all sorts of languages, but the GitHub API docs just talk about the raw HTTP responses. They pick the simplest of clients: `curl`.
https://developer.github.com/v3/

FWIW, I started a while back to document the V2 API and the different "quirks" between existing implementations:
https://joelverhagen.github.io/NuGetUndocs/

Given V3 protocol has already been implemented by at least three parties (NuGet.org, MyGet, VSTS) there will possibly be some nuanced differences between the three implemations. For my own V2 docs side project, I chose to document each case where the implementations vary rather than picking one. Not sure if the same should be done here.

**Comment by maartenba** [comment]
I may actually have some starting docs on V3 (server!) if I can find them. Fine with contributing them. If not urgent I can contribute them when back from vacation.

**Comment by skofman1** [comment]
@joelverhagen , agree with the approach of documenting the protocol in terms of HTTP requests and responses.
Regarding the multiple implementations - IMO the protocol is the "contract" between the client and server, hence we should document only the parts of NuGet.org implementation that are required/used by the client. For example: catalog is out of scope, any data that appears in registration blobs but is not used by any client is out of scope as well.

**Comment by maartenba** [comment]
Found the file I started a while back. If there is a repo for it I can do a PR and contribute as-is so you can copy/paste from it :-)

**Comment by anangaur** [comment]
Agree, these should be http requests responses. My bad, I didnt check what the blog contents were :D 

Similar to VSTS APIs documentation: https://www.visualstudio.com/en-us/docs/integrate/api/rm/releases

**Comment by anangaur** [comment]
An example of markdown based API documentation that I had done sometime back for VSTS Release service:
https://www.visualstudio.com/en-us/docs/integrate/api/rm/releases

**Comment by anangaur** [comment]
More users looking for the documentation: https://twitter.com/mholo65/status/902631455922298880

**Comment by nathanaeljones** [comment]
I can't seem to find a way to push a package up to NuGet with CURL. 
I've tried:

```
curl --verbose -X POST "https://www.nuget.org/nuget" -H "X-NuGet-ApiKey: ${NUGET_API_KEY}" -H "X-NuGet-Client-Version: 4.1" -F "data=@$NUGET_TEST_PACKAGE"
(404)

curl --verbose -L -X POST "https://www.nuget.org/v1/PackageFiles/${NUGET_API_KEY}/nupkg" -H "X-NuGet-ApiKey: ${NUGET_API_KEY}" -H "X-NuGet-Client-Version: 4.1" -F "data=@$NUGET_TEST_PACKAGE" 
(401) - double-checked api key

curl --verbose -L -X POST "https://www.nuget.org/api/v2/package" -H "X-NuGet-ApiKey: ${NUGET_API_KEY}" -H "X-NuGet-Client-Version: 4.1" -F "data=@$NUGET_TEST_PACKAGE"
(404)

```
NuGet.... I've not words.

**Comment by nathanaeljones** [comment]
This works:
` curl -L "https://www.nuget.org/api/v2/package" -H "X-NuGet-ApiKey: ${NUGET_API_KEY}" -H "X-NuGet-Client-Version: 4.1.0" -A "NuGet Command Line/3.4.4.1321 (Unix 4.4.0.92)" --upload-file "${NUGET_PACKAGE_PATH}" `

**Comment by joelverhagen** [comment]
This item needs to be broken up into tasks.

**Comment by joelverhagen** [comment]
The V3 API has been documented.
https://docs.microsoft.com/en-us/nuget/api/overview

There is a guide available here on how to use the catalog:
https://docs.microsoft.com/en-us/nuget/guides/api/query-for-all-published-packages
