### ISSUE TITLE
Browser.xUnit 0.1.1 is missing from V3 registration

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#4202]
[Browser.xUnit 0.1.1](https://www.nuget.org/packages/Browser.xUnit/0.1.1) is missing from registration2-gz.
Note that it exists in [registration1](https://api.nuget.org/v3/registration1-gz/browser.xunit/0.1.1.json), but not [registration2-gz](https://api.nuget.org/v3/registration2-gz/browser.xunit/0.1.1.json)

**Comment by skofman1** [comment]
Seems like a bug with lightning job.

**Comment by joelverhagen** [comment]
Not a bug in lightning. Looks like bad data in the catalog:

0.1.1 is available, listed, and not deleted on the gallery:
https://www.nuget.org/packages/Browser.xUnit/0.1.1

This is the first entry for the package in the catalog:
https://api.nuget.org/v3/catalog0/data/2016.03.14.21.38.00/browser.xunit.0.1.1.json

This one looks fine as it represents the initial package upload.

However, there is a second:
https://api.nuget.org/v3/catalog0/data/2016.03.14.21.38.00/browser.xunit.0.1.1.json

This represents a hard delete. The hard delete has some build metadata `0.1.1+2` which is odd but seems unrelated since the delete is still the latest event. 

Will investigate more.

**Comment by joelverhagen** [comment]
There are no other audit entries for this package. The fix here is to reflow the package so that the latest catalog entry for that package is a `PackageDetails` instead of `PackageDelete`.

**Comment by joelverhagen** [comment]
It's unclear what happened to begin with. The package delete in the catalog is an error, as there is no other clue in V3 or database that this package should be deleted.

I reflowed the package and it is now appearing in the registration blobs just fine.
