### ISSUE TITLE
Enable Azure Active Directory for NuGet Gallery

### ISSUE THREAD

**Issue by alexander-frolov** [NuGet/NuGetGallery#4238]
We have NuGet Gallery deployed in Azure and want to enable connection to our Azure Active Directory. I see Auth.AzureActiveDirectory.* settings in the Web.config. I know the ClientId, but don't know what to put to the Authority and Issuer. 

Are there any instructions available?

**Comment by shishirx34** [comment]
Hi @alexander-frolov, I am not sure if this(Azure AD) is being used by any of our customers yet. But I would love to help you out setting this up. I am sorry this hasn't been documented anywhere for NuGet, once we can help you get this resolved, I will get it documented as well.

Please note, the way we have this setup currently in NuGet Gallery, even after logging in with AD the very first time, you need to create a local account(or have an existing one on the gallery you setup), we simply link this, the external credential(AD), with the local existing account. Next time you can use AD to login. 

Please add following config values to the web.config of your gallery instance. 
- The **TenantId** is the GUID of your Azure Active directory instance, also known as the Directory ID. Go to your AAD instance on Azure portal -> Properties -> Directory ID. 
- This is not the ClientId(ApplicationID). The ClientId value is the application Id of the APP created in your AAD. To get the ClientId, in your azure portal, go to AAD instance -> App registrations. Copy the **Application ID** for the app you wish to use to configure for NuGet gallery(create one if you need to). - Along with this, you need to configure the Reply URL on your AD app. Go to Azure portal -> AAD instance -> App registrations -> Your App-> Reply URL. You need to add a Reply URL to your deployed gallery instance on Azure. This is a MUST otherwise, the gallery won't be able to connect to your AD app correctly. eg:`https://mynugetgallery.azurewebsites.net/`

```
    <add key="Auth.AzureActiveDirectory.Enabled" value="true" />
    <add key="Auth.AzureActiveDirectory.ClientId" value="<AppId/ClientId>" />
    <add key="Auth.AzureActiveDirectory.Authority" value="https://login.microsoftonline.com/<TenantId>/" />
    <add key="Auth.AzureActiveDirectory.Issuer" value="https://sts.windows.net/<TenantId>/" />
    <add key="Auth.AzureActiveDirectory.ShowOnLoginPage" value="true" />
```

Restart the app to reload your config changes. This should show you the AD login on login page:

![image](https://user-images.githubusercontent.com/1646506/27399060-71e3aaa0-5670-11e7-8773-e929c784117b.png)

[This](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-how-to-configure-active-directory-authentication) documentation gives some relevant information about configuring AD app.

Like I said currently you need to create a local account with the nuget gallery as well to use AD login. We do have a backlog item to move off of local login completely. Until then this is the way to use AD logins.

Please let me know if this works for you and if you need any help.

**Comment by alexander-frolov** [comment]
Hi @shishirx34, thank you very much. I have successfully set it up. The problem I faced after that is probably what you described. We wanted to force Azure credentials for authentication by setting the Auth.LocalUser.Enabled to false. However, when I do this, it is not possible to login with Azure AD account anymore.

**Comment by shishirx34** [comment]
Yes, currently we do not support any scenario where LocalUser is disabled. We do have a backlog item to move off completely to stand alone external credential login(MSA, AD etc) Until then I am afraid you will need to work with both.

Meanwhile, I know this is a bit extra work but, all a user would need to do would be to create a local user the very first time after logging in with the AAD. Subsequently the user can login with their AAD account and NuGet Gallery would automatically verify the linked account and log the user in(same is the flow for login with MSA on nuget.org). Would that not work for you?
