### ISSUE TITLE
[Redesign] Expander heading styles are applying to package titles

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4305]
/cc @ryuyu 

Package titles on the profile, search, and manage package pages. These should probably not be `<h2>`

**Comment by scottbommarito** [comment]
This is because we introduced CSS that makes every `<h2>` have no text styling for the purpose of the expanders, right?

IMO it seems a bit overkill to apply that styling to every single `<h2>` given that we really just want to apply it to the expanders. Could we add a class or something to the expanders so that we can make our selector more specific?

We may want to make a `ViewHelpers` method that helps construct the expanders, given that there's a lot of required HTML for them.

**Comment by joelverhagen** [comment]
Address with https://github.com/NuGet/NuGetGallery/pull/4309.
