### ISSUE TITLE
Licence URL "autopopulation" is American-centric

### ISSUE THREAD

**Issue by frankshearar** [NuGet/NuGetGallery#4415]
https://preview.nuget.org/packages/Fred/0.1.0/ has an automatically populated "License Info" field. That's great... except that it gets the URL wrong. It puts "https://github.com/frankshearar/Fred/blob/master/LICENSE" when the correct URL is "https://github.com/frankshearar/Fred/blob/master/LICENCE". (Note the "C", because this is a noun. I'm not an American English speaker, and this is the correct spelling for my English dialect.)

There is no way to simply correct the error myself.

Perhaps the licence info can be detected and recorded by a GET on LICENSE and LICENCE and selecting the one that doesn't 404.

Or just let a package maintainer set the URL.

**Comment by cdrnet** [comment]
The license url can be set freely in the package metadata (nuspec) when you create the package.

**Comment by joelverhagen** [comment]
@frankshearar, how do you produce this package? I would like to help you identify the tool that is defaulting to `LICENSE` instead of `LICENCE`. Perhaps that tool could become more aware of the user's context and pick a different default. That being said, if GitHub is itself not clever enough to switch the default license URL based on English dialect when creating a new repository, then we would need to balance the options.

There's a variety of ways to produce a NuGet package (.nupkg). NuGet.org just reads the license URL that is already present in the .nuspec (which is inside the .nupkg) and shows it on the package details page, which you have linked above.

Your .nuspec looks like this right now:

```xml
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
  <metadata>
    <id>Fred</id>
    <version>0.1.0.0</version>
    <authors>Frank Shearar</authors>
    <owners>Frank Shearar</owners>
    <licenseUrl>https://github.com/frankshearar/Fred/blob/master/LICENSE</licenseUrl>
    <projectUrl>https://github.com/frankshearar/Fred/</projectUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Parsing with derivatives</description>
    <summary>Parsing with derivatives</summary>
    <releaseNotes />
    <copyright>Copyright Frank Shearar 2014</copyright>
    <tags>F# regular expression</tags>
  </metadata>
</package>
```

Perhaps you can get all the information you need from the NuGet documentation on [how to create a NuGet package](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package).

**Comment by frankshearar** [comment]
Clearly I need to catch up on my sleep. You're quite right. There's no need for the UI to do anything re licence URI because the nuspec is what defines it. Apologies for wasting your time :/.
