### ISSUE TITLE
[Bug] Error when uploading nuget package

### ISSUE THREAD

**Issue by Workshop2** [NuGet/NuGetGallery#4428]
When I try and upload the [following nuget](https://github.com/noobot/SlackConnector/releases/download/3.1.253/SlackConnector.3.1.253.nupkg) package I get an error screen:
![image](https://user-images.githubusercontent.com/1476513/28384635-4a62eb04-6cbd-11e7-9681-2365365c2882.png)

**Comment by OsirisTerje** [comment]
I get the same error.

**Comment by scottbommarito** [comment]
I was just able to submit a package. Can you try again and see if it's still blocked?

If it still doesn't work, can you tell me more information about the package you were trying to submit so that I can try to find your request in our logs? Your account name, package id, and package version should be sufficient.

(Feel free to send it to support@nuget.org if you don't want to put it in this issue.)

**Comment by OsirisTerje** [comment]
Can confirm it now worked (NUnit3TestAdapter)  :-)   Thanks !

**Comment by scottbommarito** [comment]
I just investigated this.

It seems that we had a spike in database write timeouts around `2017-07-19T18:00:00Z` which led to failures in upload requests. V2 OData requests were unimpacted.

Unfortunately, I was unable to determine the cause of the spike,, but the issue has resolved itself now. I apologize for the inconvenience. You should be able to upload now without any issues.

I'm leaving this issue open for now because I was unable to find the root cause.

**Comment by joelverhagen** [comment]
@skofman1 @loic-sharma, this is in PROD and fixed?

**Comment by skofman1** [comment]
@loic-sharma , can you please check that this didn't repro?

**Comment by xavierdecoster** [comment]
@loic-sharma did you have any findings on this?

I'm not seeing any recent upload failures besides the occasional HTTP 409 Conflict, but I do see a bunch of HTTP 500 failures in AppInsights on `GET Packages/UploadPackageProgress` against the preview.nuget.org web site (which likely is unrelated).

```
requests
| where timestamp > ago(24h) and success == "False" and name == "GET Packages/UploadPackageProgress" 
| join kind= inner (
   exceptions
   | where timestamp > ago(24h) 
) on operation_Id 
```
