### ISSUE TITLE
[Redesign] Focus search element immediately when landing on the front page

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#4458]
It would be nice for the search box to be focused immediately when visiting the new NuGet.org website, much like on NuGet.org vCurrent. This would mean people are able to just start typing, hit enter, find results. No need to move the mouse and click the search box.

**Comment by joelverhagen** [comment]
We need to check about the accessibility guidance of this (/cc @microsoftsam), but I like the idea.

**Comment by NickCraver** [comment]
If not on the homepage, it really should still happen on `/packages` IMO.

**Comment by microsoftsam** [comment]
I think a better way to solve this is to provide a mechanism to bypass blocks, since you have content that's repeated on multiple pages (each page has a search box, each page has the menu, and each page has the content section).

This is the "hidden menu" concept we've previously talked about. A menu when focused provides the user the ability to "Jump to Search", or "Jump to Content", or "Change language", etc. 

So I think focusing the search box should only be done on pages where that is the likely first intractable element for a user.

MAS Standard in question here: WCAG 2.0 2.4.1 Bypass Blocks

**Comment by maartenba** [comment]
Any chance a "focus the element when user starts typing" could be added within those rules?

**Comment by microsoftsam** [comment]
^^ That's what github does. You'd want to make sure you'd on no activeElement in your handler, but that could work.

**Comment by joelverhagen** [comment]
Fixed and deployed to https://preview.nuget.org/.
