### ISSUE TITLE
catalog2registration can skip packages

### ISSUE THREAD

**Issue by dtivel** [NuGet/NuGetGallery#4497]
Package E2E.SemVer2PrerelRelisted.170802.135634.0702648 1.0.0-alpha.1 is in [catalog](https://api.nuget.org/v3/catalog0/page2646.json) and in [flat container](https://api.nuget.org/v3/catalog0/page2646.json), but not in any registration ([registration2](https://api.nuget.org/v3/registration2/e2e.semver2prerelrelisted.170802.135634.0702648/1.0.0-alpha.1.json), [registration2-gz](https://api.nuget.org/v3/registration2-gz/e2e.semver2prerelrelisted.170802.135634.0702648/1.0.0-alpha.1.json), [registration2-gz-semver2](https://api.nuget.org/v3/registration2-gz-semver2/e2e.semver2prerelrelisted.170802.135634.0702648/1.0.0-alpha.1.json)).

**Comment by scottbommarito** [comment]
It's in [`registration2-gz-semver2`](https://api.nuget.org/v3/registration2-gz-semver2/e2e.semver2prerelrelisted.170802.135634.0702648/1.0.0-alpha.1.json). It's not expected to be in the other registrations because it is a SemVer 2 package.

Also, my monitoring job was able to successfully validate it.
