### ISSUE TITLE
Usefulness of AppConfigIsCorrectlyApplied tests

### ISSUE THREAD

**Issue by tylerl0706** [NuGet/NuGetGallery#4521]
I was looking at the tests defined here and I was curious if these tests offer any value to the project.

https://github.com/NuGet/NuGetGallery/blob/master/tests/NuGetGallery.Facts/AppConfigIsCorrectlyApplied.cs

The first test seems to test if the app.config is loaded properly - which seems silly because it's testing a feature of .NET rather than anything related to the NuGet Gallery.

The second test seems to test that the binding redirect is working for System.Web.Mvc but I'm pretty sure the same version of System.Web.Mvc is used everywhere so testing binding redirect for this seems pointless.

This issue is more about proving me wrong and less about fixing the issue - I'm really just curious if these tests are actually offering any sort of usefulness to the project

**Comment by scottbommarito** [comment]
They look like very old tests that were written when the person couldn't figure out what exactly was wrong with their code (note `ConfigurationManager.AppSettings["YourTestsAreNotGoingInsane"]` lol). It potentially may have been due to a lapse of tooling in the past that these tests were necessary. I agree with you that they don't seem to be very useful but at this point there isn't really any value in removing them.
