### ISSUE TITLE
Cannot see actual date of package

### ISSUE THREAD

**Issue by onovotny** [NuGet/NuGetGallery#4574]
In the new gallery, you can no longer easily see the publish date of a package. It shows the "friendly" version, but that hides the details. Both on the list of versions and on the package view itself, you see this:

![image](https://user-images.githubusercontent.com/1427284/29436471-ba6c7c76-8379-11e7-8d74-ac9c20d19951.png)

Please bring back the actual publish date.

**Comment by robertmuehsig** [comment]
As a tooltip or do you prefer to see the actual date everytime (which would also work for mobile / screenreader (?))

**Comment by anangaur** [comment]
Friendly version helps to understand 'quickly' the updated timeframe. This gives an idea of how updated the given package is without doing any mental calculation.

In the list view though, the actual publish date can make sense because someone looking at the versions is now doing a deeper dive than while looking at the info.

**Comment by onovotny** [comment]
I'd be okay with it just in the list view since that shows the details.

**Comment by joelverhagen** [comment]
The current approach is to show the absolute date via a tooltip. Try mousing over any relative date to see the ISO timestamp. This however is not a great situation for phones, as mentioned above.

Also, for dates that would show "x years ago", we show the absolute date (e.g. 8/18/2017) instead since having a bunch of versions next to each other with "1 year ago" is not very helpful (thanks @NickCraver, https://github.com/NuGet/NuGetGallery/issues/4424).

Consider the case where a version is released every couple of months. Is it more helpful to show relative dates or absolute dates? I'm not sure one way or another! My gut says that relative dates make it easier to quickly assess roughly how frequently the package author releases new versions.

Perhaps we can leave this issue open and allow the community to voice their opinions one way or another?

**Comment by skofman1** [comment]
We had no upvotes on this issue over the last year. Seems like the current UI is good enough.
Will reopen if you disagree.
