### ISSUE TITLE
URL with non-existing version number returns latest package version

### ISSUE THREAD

**Issue by khellang** [NuGet/NuGetGallery#4624]
Try going to https://www.nuget.org/packages/Newtonsoft.Json/1337.42.42.0 (or ending with any other valid version number).

It returns back a 200 response with the information of the latest package, as if you've gone to https://www.nuget.org/packages/Newtonsoft.Json.

I'd expect this to return a 404 😄

**Comment by skofman1** [comment]
We had a discussion about the correct behavior when a user tries to access a version that doesn't exist. The conclusion is that the best experience for users is to redirect to the latest version page and show a banner.

**Comment by zivkan** [comment]
I agree that it's good to at least show the versions that are available, and I think it's fine to show the latest version. However, I think it should be more clear that the requested version does not exist. Viewing an unlisted package shows a warning, so I think requesting a missing version should as well. And the version history list shouldn't look misleading. If I got onto the page from a link, rather than typing the URL, it won't be obvious to me that the version shown is different to the version in the URL.

As the original comment says, having the HTTP status code 404 would probably be better, or at least more technically correct. Particularly since it would make sure that search engines don't index versions that don't exist when following links from other sites.

**Comment by rocklan** [comment]
I've submitted pull request #8155 so that it displays a warning telling you that the specified version was not found. This is at least one step better than what happens at the moment. It's not doing a redirect though, but it's not clear to me if that's what @skofman1 was wanting.

It's arguable if it should display a 404 - npm (javascript) and pypi (python) do this, but maven (java) and packagist (php) don't... Personally I think you can't really win - a 404 is really unhelpful for users, but makes sense programmatically, but a 302 is  technically not correct.  🤷‍♂️

**Comment by joelverhagen** [comment]
@rocklan, we can phase this in if you'd like:

- Phase 1: show the banner but no redirect yet (your current PR)
- Phase 2: redirect and show a banner that you were redirected. There is code that shows one-time messages so we can leverage that I think.

I think it's fine to do phase 1 first and phase 2 later. Or, if you'd like, you can implement both at the same time. Showing the banner without redirecting is still an improvement on the current behavior.

Thanks taking an interest in helping out!

**Comment by joelverhagen** [comment]
@rocklan, your change is deployed to nuget.org. Thanks again for your contribution!

**Comment by rocklan** [comment]
@khellang this is in production now if you'd like to close this issue

**Comment by khellang** [comment]
@rocklan Looks good! Thanks 😘
