### ISSUE TITLE
update to v2017.09.01 upload new package cann't be listed

### ISSUE THREAD

**Issue by liurongwei** [NuGet/NuGetGallery#4628]
https://github.com/NuGet/NuGetGallery/tree/v2017.09.01

update from v2017.08.14, when a new package uploaded , cann't list in the packagelist page, when I rebuild  the lucene index , it still cann't list until I restart the website , it displayed.

**Comment by joelverhagen** [comment]
Hey @liurongwei, thanks for taking the time to report this issue. I was able to reproduce this on v2017.08.14 without even moving to v2017.09.01. I think the behavior you are seeing is caching of the first page of the search results. See this code:
https://github.com/NuGet/NuGetGallery/blob/9eb4bc49f7f34339b0fc4a6183f9265509961cdd/src/NuGetGallery/Controllers/PackagesController.cs#L552

This result cache lasts for 10 minutes or, as you saw, until the server is restarted. You can use a tool like `luke` (Lucene index viewer) to verify that the package is indeed indexed for searching when it is uploaded, but the search results are stale due to caching.
