### ISSUE TITLE
build failed Nuget.resources not found.

### ISSUE THREAD

**Issue by oliviergauthier** [NuGet/NuGetGallery#4637]
I can't build NugetGallery. It throw the next exception :
 Impossible de charger le fichier ou l'assembly 'file:///C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin\fr\NuGet.resources.dll'

it's seems related to this issue : https://github.com/NuGet/Home/issues/4780
I have updated Nuget with command :   .\.nuget\NuGet.exe update -self but when i launch build command again, it reset Nuget version to 4.0.0.2275

**Comment by scottbommarito** [comment]
Issue moved to [NuGet/Home #5876](https://github.com/NuGet/Home/issues/5876) via [**ZenHub**](https://www.zenhub.com/)

**Comment by scottbommarito** [comment]
Moved because it is a client issue and not a server issue.

**Comment by scottbommarito** [comment]
So we determined this was actually an issue with our build script and not related to the client.

Currently, our build script uses https://dist.nuget.org/win-x86-commandline/latest-prerelease/nuget.exe, which points to v4.0.0 instead of v4.1.0.

Fix is at https://github.com/NuGet/ServerCommon/pull/56

@oliviergauthier You can work around this by running the build script with the parameter `-BuildBranch sb-fixnugetversion`.

E.g.
```
nuget.exe -BuildBranch sb-fixnugetversion
```

**Comment by skofman1** [comment]
The work left here is to update all build scripts to use the latest commit SHA from server common.

**Comment by tyteen4a03** [comment]
Just ran into this issue today - what do I need to change in my build script? I don't see any references to `nuget.exe`.

**Comment by scottbommarito** [comment]
Woops, had a typo in the original resolution steps, it should be `build.ps1` instead of `nuget.exe`. Updated it above.

Regardless, the old fix no longer works because the PR on ServerCommon was merged and the branch `sb-fixnugetversion` was deleted. You should be able to get around this issue by either
1 - updating the build script (`build.ps1`) and replace
```
[string]$BuildBranch = '37ff6e758c38b3f513af39f881399ce85f4ff20b'
```
with
```
[string]$BuildBranch = 'bab0ca83214a4a94f682d7c072f227a138fd471a'
```
2 - running the following command to build
```
.\build.ps1 -BuildBranch "bab0ca83214a4a94f682d7c072f227a138fd471a"
```
