### ISSUE TITLE
It takes 27.41 seconds to load this NuGet page...

### ISSUE THREAD

**Issue by bchavez** [NuGet/NuGetGallery#4862]
![chrome_707](https://user-images.githubusercontent.com/478118/31702141-c670a6d8-b389-11e7-82d2-d5daa415663c.png)

/cc @skofman1 ref: https://github.com/NuGet/NuGetGallery/issues/4859#issuecomment-337455878

https://www.nuget.org/packages/FAKE/

```
$(".version-history tr").length
1627
```

Tool used to check page load performance: https://tools.pingdom.com

----

~~Also, my other NuGet issue #4494 is now 77 days old and still a blocking issue to this day. As a reminder, #4494 is a server-side issue (and optionally a client-side issue) that needs to get fixed. I would ***really appreciate*** it if someone at Microsoft can put some effort into getting these issues fixed instead of pushing issues to a **"future"** label.~~

~~Again, as a quick refresher, I dare anyone to install the `Baseline` NuGet package via **Command Line**:~~

![cmd_712](https://user-images.githubusercontent.com/478118/31702709-9f0898b8-b38d-11e7-81d7-4521ff1060ac.png)

Thank you

**Comment by loic-sharma** [comment]
Thanks for reporting! The Gallery should not display thousands of versions on the package display page. An easy fix here would be to display only the latest 100 versions, and displaying a message if there may be more versions.

**Comment by bchavez** [comment]
The actual reason for me to go to the F# FAKE NuGet page was to look for a specific version in the version history that was published 10 months ago. I needed to go back 10 months so I could resolve an build issue and lock down my dependencies to that specific version number. Additionally, I needed to lock down other dependencies around that similar timeframe. In summary, version history is useful.

I think the best idea is not to truncate information from your website but to make it more accessible.

**Comment by skofman1** [comment]
The page is loading slowly even for packages that have ~100 versions. We need to fix this.

**Comment by joelverhagen** [comment]
There is some pretty bad performance on the most popular packages. I tried the top fix on the search results:


ID | Duration (seconds) | Performance Result
-- | -- | --
Newtonsoft.Json | 6.84 | https://tools.pingdom.com/#!/bxyIsD/https://www.nuget.org/packages/Newtonsoft.Json/
NUnit | 4.3 | https://tools.pingdom.com/#!/vLiaw/https://www.nuget.org/packages/NUnit/
EntityFramework | 5.54 | https://tools.pingdom.com/#!/nmZ2y/https://www.nuget.org/packages/EntityFramework/
jQuery | 7.93 | https://tools.pingdom.com/#!/dmuzMt/https://www.nuget.org/packages/jQuery/
HtmlAgilityPack | 6.3 | https://tools.pingdom.com/#!/bDSeBl/https://www.nuget.org/packages/HtmlAgilityPack/

Something has regressed since the redesign.

**Comment by chenriksson** [comment]
It looks like the issue is that we're executing a lot of unnecessary EF queries on cshtml execution.

A CPU profile shows 62% inclusive spent on DisplayPackage.cshtml execution, and just 18.4% on the controller action:
![image](https://user-images.githubusercontent.com/15364949/33392588-5ee038ce-d4f1-11e7-901c-6b16f9f9b4f7.png)

The controller executes 2 queries:
- line 415; package = _packageService.FindPackageByIdAndVersion(...)
- line 427; packageHistory = ...

The razor view executes (# of versions) + 1 queries, seemingly to populate the Dependencies relation for every package version.

We should probably fix by including the Dependencies relation on the specified (or latest) version, but exclude and don't query Dependencies on all other versions. Still need to test and verify if that will resolve the performance issue.

**Comment by chenriksson** [comment]
Validation of FAKE package...

| Scenario | Baseline Env | Baseline Result | Env | Result | %Diff |
| --- | --- | --- | --- | --- | --- |
| DisplayPackages (1360 versions) | INT-USSC | 3217ms | INT0 | 768ms | -76% |

**Comment by chenriksson** [comment]
@bchavez You should see faster load times on this page now. I couldn't repro the 27s load time, but saw about 6s load times on average. If I find more optimizations, I'll open new issues to track.

**Comment by bchavez** [comment]
@chenriksson thank you! I did notice recently page times are so much faster now. It's amazing. It's really wonderful to have NuGet working really good once again.

Again, super thanks for working on this and making everything so fast. :+1: :airplane:
