### ISSUE TITLE
504 Gateway Timeout

### ISSUE THREAD

**Issue by yshahin** [NuGet/NuGetGallery#4959]
date && curl -i -XGET  https://api.nuget.org/v3-flatcontainer/microsoft.extensions.fileproviders.physical/index.json

Mon Nov  6 12:11:06 STD 2017
HTTP/1.1 504 Gateway Timeout
Content-Type: text/html
Date: Mon, 06 Nov 2017 20:11:13 GMT
Server: ECAcc (sec/9704)
Strict-Transport-Security: max-age=31536000
X-CDN-Rewrite: Root path in dist
Content-Length: 357

<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
        <head>
                <title>504 - Gateway Timeout</title>
        </head>
        <body>
                <h1>504 - Gateway Timeout</h1>
        </body>
</html>

**Comment by skofman1** [comment]
Due to an incident in Azure NuGet services are degraded. 
1. api.nuget.org is unavailable;
2. nuget.org web site is read-only mode - package publishing and account management are unavailable. Manual download of packages is also unavailable.

You can check the status on our status page: https://status.nuget.org/  We’ll post updates there.

**Comment by skofman1** [comment]
The outage was resolved. All NuGet services are now operational.
