### ISSUE TITLE
Package statistics for FakeXrmEasy.9 package not updating

### ISSUE THREAD

**Issue by jordimontana82** [NuGet/NuGetGallery#4997]
Hi,

Package statistics don't seem to be updating for package FakeXrmEasy.9.

Could you please take a look?

Thanks a mill

**Comment by scottbommarito** [comment]
Hey @jordimontana82,

I'll be fixing this soon and it will roll out with the next deployment.

Just a note: the reason stats don't update every time you create a new package is because we have a bug with statistics for packages that end with a `.` plus a number. The statistics pipeline can't distinguish between `FakeXrmEasy.9 version 1.0.0` and `FakeXrmEasy version 9.1.0.0` so it assumes that the downloads are for the latter. If you were to change the naming scheme of your packages, for example by uploading `FakeXrmEasy9 version 1.0.0` instead, you would not have this problem. Unfortunately this is a very hard bug to fix and although we've wanted to fix it for a while, it will likely be a long time until we do.

In the future, I would suggest naming new packages under a different scheme that doesn't have this issue so that there's no need for us to intervene. If you would like to keep this naming scheme, please let us know when you upload new packages as quickly as possible so you don't have any issues with losing download counts. To speed up the process even further, you could make the change yourself (see https://github.com/NuGet/NuGet.Jobs/blob/master/src/Stats.ImportAzureCdnStatistics/packagetranslations.json) and we'll review it.

**Comment by jordimontana82** [comment]
Hi Scott!

Thanks a mill! Ok, will update the naming convention as you suggested from now on...

Cheers!

**Comment by scottbommarito** [comment]
Verified that it's working as expected now!

Let us know if you encounter any other issues.
