### ISSUE TITLE
NuGet.Server v3 Support

### ISSUE THREAD

**Issue by danielwertheim** [NuGet/NuGetGallery#5038]
Is the NuGet.Server going to get support for NuGet v3 API and will it be ported to support multiple targets and thereby also .NET Core?

**Comment by skofman1** [comment]
@danielwertheim , can you provide more details regarding your scenario? 
Adding V3 support to NuGet.Server is currently not on our backlog.

**Comment by danielwertheim** [comment]
@skofman1 honestly I guess it's more of an "will you keep this alive"...? But if V2 is to be supported for a long period it's not an issue. What's more interesting would be .NET Core support so that one easily could spin up "lighter" Docker containers with a custom host using NuGet.Server

**Comment by skofman1** [comment]
@danielwertheim , V2 support is not going anywhere, not on nuget client side nor on nuget.org side.
Regarding rewriting NuGet.Server for .NET core, we have an issue to track it here: https://github.com/NuGet/NuGetGallery/issues/3390
And I see that @tomzo already started the work: https://github.com/ai-traders/liget

Closing this issue as duplicate.

**Comment by valeriob** [comment]
What are the differences and the reason between v2 and v3 ?

**Comment by skofman1** [comment]
V3 protocol is scalable, stable and performant.
The interaction between client and server is done by using JSON blobs that can be generated statically. Meaning, in order to perform a package restore operation there is no need to access any cloud service and server compute resources are no required. All the data the client needs is exposed in static JSON blobs, and download is made faster using CDN. 
Unlike V3, V2 protocol uses nuget,.org website APIs to get information about packages and their download links. 
We have recently documented V3 and added detailed instructions (with examples!) on how to consume it: https://docs.microsoft.com/en-us/nuget/api/overview

**Comment by guanjinke** [comment]
Any update about the issue? I'd like to know if the latest version has supported the V3 API?

**Comment by loic-sharma** [comment]
NuGet.Server does not support V3 yet. If you're looking for servers that support V3, I'd recommend [BaGet](https://github.com/loic-sharma/BaGet) or [Sleet](https://github.com/emgarten/Sleet).

**Comment by qJake** [comment]
We're trying to migrate our private `Nuget.Server` on-premise to Azure Artifacts, and apparently the package retrieval script only supports the V3 API.

https://docs.microsoft.com/en-us/azure/devops/artifacts/tutorials/migrate-packages?view=azure-devops

This is really unfortunate because now there isn't a path from a private on-premise NuGet feed into Azure Artifacts.

V3 support would be really nice, or (wishful thinking) a re-imagining of the NuGet.Server package as an ASP.NET Core package/middleware instead.

**Comment by loic-sharma** [comment]
Hi @qJake, that's great feedback! Have you reached out to Azure DevOps about this suggestion?

Also, BaGet has a trick that lets you import packages from NuGet.Server. You should be able to use that to migrate to Azure Artifacts: https://loic-sharma.github.io/BaGet/tools/migrate/#steps
