### ISSUE TITLE
Package upload UI - click on "submit" takes a long time

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#5049]
After the package was uploaded, submitting it should be instantaneous, however it takes multiple seconds.

**Comment by chenriksson** [comment]
For server-side, I'm seeing:
- 46.4% inclusive due to WebMatrixPackageCurator.CurateAsync (ShouldCurate returns false)
- 16% inclusive from the actual DB commit

Need to investigate more, but looks like we shouldn't need to select the feed and populate its packages if we know the `galleryPackage` shouldn' be curated due to feed-agnostic criteria.

![image](https://user-images.githubusercontent.com/15364949/37749163-ed2c81e6-2d43-11e8-8193-05894b034d73.png)

@skofman1 @xavierdecoster  Did we decide whether or not to kill the WebMatrix curated feed? Trying to determine if the fix is to remove the feed entirely, or optimize this path.

**Comment by xavierdecoster** [comment]
> @skofman1 @xavierdecoster Did we decide whether or not to kill the WebMatrix curated feed? Trying to determine if the fix is to remove the feed entirely, or optimize this path.

Removing obsolete curated feeds imho is a good thing :)
Discussion on removing WebMatrix-specific one is tracked by issue https://github.com/NuGet/NuGetGallery/issues/3696

**Comment by chenriksson** [comment]
Verified on INT0 vs custom baseline (local against INT0 / master 5f3d18a)

Scenario: verify-upload (package that isn't curated)
 - Baseline: 4.38s, 3.38s, 3.34s => 3.7s
 - Latest: 2.17s, .75s, .42s => 1.11s (-70%)

Won't verify PROD, because scenario requires authentication and can't be tested on secondary or staging.
