### ISSUE TITLE
NuGet Server creates temp files in C:\Windows\Temp\NuGetScratch in server

### ISSUE THREAD

**Issue by NagarajMasub** [NuGet/NuGetGallery#5230]
Hi,

we have our own nuget feed in our server,we are using NuGet.Server . C:\Windows\Temp\NuGetScratch in this location there are more than 100 gb of nuget files are stored, due to this my server gets hanged, how can i resolve this.

We already faced this issue on one our servers, but in our new server, we have used latest NuGet Server assemblies, the cache created in NuGetScratch folder instead of nuget. (https://github.com/NuGet/Home/issues/3635)

And the growing speed is worst. the folder size takes 90 GB within 10mins

I cant delete the files, it will grow continuously, since this is our customer feed, the size increase while a customer using.

1. Is it possible to change this temp location to another drive instead of C drive?
2. I checked your source, I thought you are getting the temp path using the gettempPath action, so changing the Temp environment variable in my server will take the new path which I ll give?
3. Changing this temp variable will affect the NuGet feed?
4. Deleting these files will affect customer while installing the nuget?

Please update this ASAP.

Thanks in advance.

**Comment by joelverhagen** [comment]
Thanks for reporting this issue. Could you answer my questions below?

## Your questions

> Is it possible to change this temp location to another drive instead of C drive?

No, not without changing the user-wide temp location.

> I checked your source, I thought you are getting the temp path using the gettempPath action, so changing the Temp environment variable in my server will take the new path which I ll give?

`Path.GetTempPath` looks at first `TMP` then `TEMP` second ([docs](https://msdn.microsoft.com/en-us/library/system.io.path.gettemppath.aspx)). As a workaround, You can try changing the value of `TMP`. I always change `TEMP` at the same time so that different applications behave consistently.

> Changing this temp variable will affect the NuGet feed?

No, it should not. NuGet.Server serves packages downloads from the configured package directory (from the `packagesPath` setting in the web.config).

> Deleting these files will affect customer while installing the nuget?

No, they are regenerated if they don't exist and are needed.

## My questions

To better help you, could you provide the following information?

1. What NuGet.Server version are you using?
1. What is the size of your configured packages directory (`packagesPath` setting in the web.config)?
1. How many directories are directly under the `NuGetScratch` directory? If there are less than 10, could you provide the names of these directories? If it is more than 10, is it almost all a bunch of GUID-named directories?
1. Have you ever observed the `NuGetScratch` directory getting cleared?
1. Try going to the clear-cache endpoint in your browser, e.g. `http://my-server/nuget/clear-cache`. Does this reduce the size of the `NuGetScratch` directory at all?

I would like to work on this fix but NuGet.Server takes a lower priority compared to other NuGet server-side work. I will schedule this for next sprint (some time after January 15th).

## Additional Context

I believe the reason this `NuGetScratch` location is being used when determine the supported frameworks of a package. This method is currently implemented by inspecting the directory structure of the extracted .zip file ([source](https://github.com/NuGet/NuGet2/blob/c3d1027a51b31fd0c41e9abbe90810cf1c924c9f/src/Core/Packages/OptimizedZipPackage.cs#L188)). Each time the web process restarts, a new sub-directory is creating (with `Guid.NewGuid()`) under `NuGetScratch`.

Possible fixes (and this is more for my team -- you don't have to care about this part):

1. Call `OptimizedZipPackage.PurgeCache()` more frequently. This is not a great solution since we need to be careful not to purge at the wrong time. And this only purges files created by the current process.
1. Use `ZipPackage` instead of `OptimizedZipPackage`. This reads the file list without extracting the file. The `OptimizedZipPackage` has caching. `ZipPackage` does not, so it may be slower.
1. Provide a short live, package-isolated, in-memory cache to be used by this constructor: `OptimizedZipPackage(IFileSystem fileSystem, string packagePath, IFileSystem expandedFileSystem)`.

I would like to get to this fix, but

**Comment by NagarajMasub** [comment]
Hi @joelverhagen 

Thanks for your update.

I have switched the TEMP path to another drive now cache moved to that drive.

find the details you have asked.
1. What NuGet.Server version are you using?
 Version - 3.0.2
2. What is the size of your configured packages directory (packagesPath setting in the web.config)?
 Size - 130 GB
3. How many directories are directly under the NuGetScratch directory? If there are less than 10, could you provide the names of these directories? If it is more than 10, is it almost all a bunch of GUID-named directories?
   Yes, it is more than 10. and those are GUID by Name, find some samples below
0b1ddf45-e0f2-4dee-8117-fc5627b46d40
0e7ff63d-a955-4721-bf62-1fbcd809de67

4. Have you ever observed the NuGetScratch directory getting cleared?
   I think no.
5. Try going to the clear-cache endpoint in your browser, e.g. http://my-server/nuget/clear-cache. Does this reduce the size of the NuGetScratch directory at all?
   Getting this error: "Clear cache is only supported for local requests."

**Comment by joelverhagen** [comment]
> Size - 130 GB

Yup, that would do it. This shouldn't be an issue -- as mentioned above I hope to fix this problem soon.

> Yes, it is more than 10. and those are GUID by Name, find some samples below
> 0b1ddf45-e0f2-4dee-8117-fc5627b46d40
> 0e7ff63d-a955-4721-bf62-1fbcd809de67

As I suspected, I think the server is restarting frequently. Each time the server restarts, it will create a new "GUID" directory. This is kind of nasty...

> Getting this error: "Clear cache is only supported for local requests."

Oh right, my bad. You have to hit the clear-cache endpoint while you're logged into the host server.

**Comment by NagarajMasub** [comment]
@joelverhagen 

One more issue we are facing in recent times after updated the latest NuGet server,

The hosted application's CPU usage went high even though less number of users only accessing the site.

We have 20 Nuget server feeds hosted as sub-applications. We didn't face these kinds of CPU usage issue in the previous version. but now we are facing this issues regularly, it gets down multiple times per day.

Is this will happen due to creating those bulk cache issues? or any reason for this?

can you please check with High priority?

**Comment by joelverhagen** [comment]
@NagarajMasub, thanks for the additional details. Which version of NuGet.Server did not exhibit these high CPU issues?

**Comment by NagarajMasub** [comment]
@joelverhagen 

find the attached image
![image](https://user-images.githubusercontent.com/18211481/34835129-f1c8ccce-f719-11e7-84b7-412339bf6b8b.png)

**Comment by NagarajMasub** [comment]
@joelverhagen 
ANy update on this issue?

**Comment by joelverhagen** [comment]
This work is planned for next sprint, so I have not yet had a chance to investigate or work on a fix. When I or someone on my team gets to it, I think we will be focusing on the disk space problem. It's not clear to me as of yet whether the CPU issue is a side effect of the disk space issue or a separate issue entirely. Let's see what your CPU usages patterns are like after we get a bug fix for the disk space issue in your hands.

**Comment by NagarajMasub** [comment]
@joelverhagen 
Thanks for the update, waiting for your fix..... :)

**Comment by joelverhagen** [comment]
Hey @NagarajMasub, could you try updating to the following prerelease build to see if it fixed your issue? Install NuGet.Server version **3.0.3-jver-big-tmp-21027** from the following package source:
https://dotnet.myget.org/F/nuget-build/api/v3/index.json

(this is a MyGet package source is where CI builds of NuGet.Server go before we published them to NuGet.org)

The PR that produced this build is here, if you are curious:
https://github.com/NuGet/NuGet.Server/pull/48

**Comment by joelverhagen** [comment]
Hey @NagarajMasub, I've shipped the fix in 3.1.0, which is published to nuget.org:
https://www.nuget.org/packages/NuGet.Server/3.1.0

Let me know if you run into any other issues or if it resolves the problem for you 😄

**Comment by NagarajMasub** [comment]
Hi @joelverhagen ,

Thanks for your update, 

after upgraded the below packages, the cache issue has been resolved.
https://dotnet.myget.org/F/nuget-build/api/v3/index.json

But now we are facing Performance issue on the server. the CPU usage always takes 99% even single user only accessing the feed.

One of our engineers created an issue related to this, can you please check and update?
https://github.com/NuGet/NuGetGallery/issues/5536

The New packages, creating folder structure while discovering the packages 1st time but not deleting the packages in the outside folder. is this known issue?

**Comment by joelverhagen** [comment]
> But now we are facing Performance issue on the server. the CPU usage always takes 99% even single user only accessing the feed.

Yes, this seems like the CPU issue you mentioned before. We'll follow-up on that other GitHub issue.

> The New packages, creating folder structure while discovering the packages 1st time but not deleting the packages in the outside folder. is this known issue?

Could you explain this in more detail? I'm not sure what you mean.
