### ISSUE TITLE
[BugBash] Account shows 2 AAD entries after first log in

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#5452]
Scenario 9, per @joelverhagen (issue 2)

there are two AAD entries in my account after first log in...

**Comment by scottbommarito** [comment]
Site admins are allowed to have multiple accounts linked (to preserve the login flow, because admins must authenticate with AAD) but if this is a visual bug showing multiple entries for one auth method then it should be fixed.

**Comment by shishirx34** [comment]
Yes site admins can have multiple accounts linked since it uses AAD provider as opposed to AADv2. Once https://github.com/NuGet/NuGetGallery/issues/5478 is done this issue shouldn't happen. I think it is safe to ignore this for now since it will be applicable to only admins, and we are not planning to transform these accounts as of now.
