### ISSUE TITLE
[BugBash] Linking MSA can enable 2 users with same email and weirdness

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#5462]
Scenario 20, per @loic-sharma (issue 1)

I have two accounts: the first...

**Comment by shishirx34** [comment]
I don't think this is an issue but by design, the problem being that the user did not link their AAD login to the account using the AAD email address.

@anangaur - can you take a look at this issue and determine if this is something we should care about? 
The problem is that the one account is using @nuget.org password login and another one with the AAD login, using the same email address.

**Comment by shishirx34** [comment]
discussed with @anangaur - This is expected.
