### ISSUE TITLE
Question concerning installation

### ISSUE THREAD

**Issue by Stephanevg** [NuGet/NuGetGallery#5621]
Hi,

I have a short question. The locations where I want to deploy a NuGet Gallery, don't always have a visual studio xxxx installed on that server.
What would be the best / recommend way to install the NuGetGallery on a server where I don't have Visual studio installed? 

Isn't possible to have access to a 'simple' msi (or other type of installer) to install the NuGet gallery? That would really simplify a lot of things for a lot of ITpros.

It there any plan to add this for example on this github page (or in the powershell gallery for example) as a downloadable package? That would be really great! (Or probably it exists, and I simply missed it?)

**Comment by skofman1** [comment]
Hi @Stephanevg , unfortunately we don't have an MSI package, or other method to simply install the Gallery on a VM with no Visual Studio. 
Many users choose to use NuGet.Server instead, which is much simpler to configure: https://docs.microsoft.com/en-us/nuget/hosting-packages/nuget-server
But this depends on your requirements.

If you still would like to deploy NuGetGallery, my recommendation will be to start with deploying the Gallery on a machine with VS installed, according to the instructions in our [Readme](https://github.com/NuGet/NuGetGallery). After you are done with setting up the web.config to match your requirements, in order to move the Gallery to a different machine, install on that machine .NET Framework 4.6, a SQL DB and IIS/IIS express. Copy the NuGetGallery folder as is, and set IIS to use it.

**Comment by Stephanevg** [comment]
Hi @skofman1  
Thanks for answer! 
Could it be possible that you guys make that available (via a Feature request) ? 
It is really a struggle for non developpers to implement a NugGet Server.
Having a MSI would really simplify the complete installation process, and be of a big help for the entiere community.

**Comment by loic-sharma** [comment]
Hey there @Stephanevg! Can you explain why you would like to setup your own instance of the NuGet Gallery? The Gallery is

**Comment by loic-sharma** [comment]
Sorry for the noise - I closed this issue by accident 😅 

An MSI would certainly simplify the Gallery's installation! Out of curiosity, why are you trying to setup your own instance of the NuGet Gallery? Like @skofman1 mentioned, many users run [NuGet.Server](https://github.com/NuGet/NuGet.Server/) instead as it is easier to install.

**Comment by Stephanevg** [comment]
no worries @loic-sharma :)
My primary need is to setup a nuget.server it to be able to deploy a package using PowerShell (Install-Package). The possibility to 'easily' host a package is a component that is missing- Today, for that reason, and this https://github.com/OneGet/oneget/issues/6 most sysadmins tend to go towards competitors product (such as Chocolatey).

**Comment by skofman1** [comment]
@Stephanevg , the purposes of NuGet and Chocolatey are different. NuGet hosts packages to be used by .NET developers while Chocolatey hosts software. Both use similar protocols to install packages.
The simplest way to host packages without the need to install anything is by using a folder on a local/network folder.  Checkout the instructions here: https://docs.microsoft.com/en-us/nuget/hosting-packages/local-feeds

**Comment by skofman1** [comment]
There's a similar issue already tracked here: https://github.com/NuGet/NuGetGallery/issues/2397

Closing as duplicate.
