### ISSUE TITLE
Securing a gallery so that authentication is required to access packages

### ISSUE THREAD

**Issue by Texernie** [NuGet/NuGetGallery#5800]
I have searched the issues and the web for this and I am not finding any good answers. I would like to secure my NuGetGallery such that authentication is always required. One of my sources has done this by providing us with a special URL to access their nuget feed.

https://nuget.{vendor}.com/{API Key?}/api

I have about decided that they are running a custom build of the server. What would be the best way to implement something like this, or where would the easiest place be to implement this?

I would like my nuget server to behave like below:

https://nuget.{my company}.com/{API Key?}/api -> pulls packages like normal
https://nuget.{my company}.com/api -> 401 Unauthorized or 404 Not Found
https://nuget.{my company}.com/{API Key?} -> homepage like normal
https://nuget.{my company}.com/ -> login page then to homepage

Edit:
It is possible that I can have another piece of software extract the API key from the url and put it into a request header if having the auth key in the header is easier to do.

Thanks in advance for any guidance you can provide.
Regards,
Texernie

**Comment by joelverhagen** [comment]
Hey @Texernie.

Great question. Today, NuGetGallery does not support this feature. It has a lot of assumptions around a single set of packages and a single set of users which, once logged in, can push to that set of packages.

I see two possible options for this feature, both would require a decent amount of custom code.

1. The simplest is to use NuGet.Server instead of NuGetGallery. NuGet.Server is a much simpler server implementation with no SQL or blob storage dependencies. Packages and package metadata is stored on the disk. There is a [sample](https://github.com/NuGet/NuGet.Server/blob/master/samples/NuGet.Server.V2.Samples.OwinHost/Program.cs) in the NuGet.Server repository showing what it looks like to have multiple feeds running in a single process and having custom authentication. One caveat is that NuGet.Server has no package browser UI. It's just a V2 feed endpoint.

1. If you require a UI (like one that gallery has), you could try overhauling the "curated feed' concept in NuGetGallery. This has a notion of segregating packages into separate feeds. For example, take a look at the [curated feed OData controller](https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Controllers/CuratedPackagesController.cs) (which powers a curated feed specific V2 endpoint). You could perhaps mix in some custom auth code tying an API key to a specific curated feed. There is also [CuratedFeedsController](https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Controllers/CuratedFeedsController.cs) which allows browsing packages in a specific curated feed.

I hope this helps.

**Comment by joelverhagen** [comment]
BTW, @NickCraver has worked on an version of NuGet.Server that uses SQL Server for all storage instead of disk if that is more appropriate for your use-case: https://github.com/NuGet/NuGetGallery/issues/5430.

**Comment by Texernie** [comment]
For those also searching for this, I have tested a concept that would do what I originally asked. 

**USE AT YOUR OWN RISK!**
**USE AT YOUR OWN RISK!**
**USE AT YOUR OWN RISK!**

There were not many changes needed to the NuGetGallery code.

File 1, AppController.cs. Add [ApiAuthorize] attribute to the AppController class. This will make every call to a controller require the X-NuGet-ApiKey header in the request.

File 2: ApiKeyAuthenticator.cs. Add below code to the AttachToOwinApp method.

    app.Map("", api =>
    {
        api.UseApiKeyAuthentication(new ApiKeyAuthenticationOptions
        {
            ApiKeyHeaderName = Config.HeaderName,
            ApiKeyClaim = Config.Claim
        });
    });

Now for the hard part. There are many solutions for load balancing, url rewrite, etc. If you are using HAProxy, the below lines are a starting place for what will have to go into the backend.

    acl url_backend_apikey path_beg -i /[\w]*/
    acl url_content path_beg -i /content/
    acl url_scripts path_beg -i /scripts/
    acl url_stats path_beg -i /stats/
    acl h_huget_apikey_exists req.hdr(X-NuGet-ApiKey) -m found
    http-request set-var(req.apikey) path,regsub(^/[\w]*[/]?,/) if url_backend_apikey
    http-request add-header X-NuGet-ApiKey %[var(req.apikey)] unless h_nuget_apikey_exists or !url_backed_apikey
    reqirep ^([^\ ]*\ /)[\w]*[/]?(.*)     \1\2 if !url_content !url_scripts !url_stats


**There are some known issues with this solution.** 

- If you deploy the entire solution, there will be **no way** to register your user to generate the initial apikey! 
- There could very well be more than the 3 path prefixes that will have to be "escaped" and exempted from the url rewrite scheme. 
- There could very well be other issues that you will run into that would prove this to be a less than desirable solution.

**USE AT YOUR OWN RISK!**
**USE AT YOUR OWN RISK!**
**USE AT YOUR OWN RISK!**

In the end, we have decided to go a different route that does not require any of this solution.
