### ISSUE TITLE
More thorough investigation/fix for delayed download stats

### ISSUE THREAD

**Issue by tmenier** [NuGet/NuGetGallery#5812]
Based on many personal experiences (including [today](https://www.nuget.org/packages/Flurl.Http/)), as well as GitHub issues, tweets, etc, the issue of delayed download stats seems like a chronic problem that's been going on for at least a year now. Even under "normal" circumstances (when it's not 19 hours behind like today) it seems like I have to wait quite a long time for those counts to update. Even at a huge scale of a billion packages, maintaining a reasonably current and stable counter associated with each of them doesn't seem like it would be that hard of a problem to solve.

I want to be as polite as possible here, and I don't think download stats are mission critical for anyone so I'm not suggesting this is red-hot, but isn't it possible there's a deeper architectural flaw or bottleneck, rather than some isolated incidents that are closed as soon as they appear to go away for the time being? In other words, would you consider investigating this from an architectural perspective rather than an operational one?

Thank you.

**Comment by skofman1** [comment]
@tmenier , thanks for raising this issue. Our statistics pipeline was [designed and built a few years ago](https://blog.nuget.org/20150924/Revised-Download-Counts-and-Package-Statistics.html). Over the years we invested in maintenance and bug fixes, since with the increased popularity of nuget.org and hence exponentially rising download counts, it often needs perf improvements. 
Rebuilding the statistics pipeline is on our backlog. As part of the effort we will not only improve performance and reliability but will also introduce feature improvements the community has been asking for a while. However, as you mentioned, this is not our top priority. You can take a look at our upcoming work here: https://blog.nuget.org/20180301/NuGet-Spring-2018-Roadmap.html

**Comment by tmenier** [comment]
Completely understood and thanks for the info!
