### ISSUE TITLE
Enable HTTP compression for nuget API

### ISSUE THREAD

**Issue by rianjs** [NuGet/NuGetGallery#5837]
The gallery supports gzip compression, but the API endpoints do not.

Request headers:

```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Cache-Control: max-age=0
Connection: keep-alive
Cookie: _ga=GA1.2.814392553.1516204099
Host: api.nuget.org
Referer: https://github.com/
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
```

Response headers:

```
HTTP/2.0 200 OK
access-control-allow-origin: *
access-control-expose-headers: x-ms-request-id,Server,x-ms-version,Content-Type,Cache-Control,Last-Modified,ETag,Content-MD5,x-ms-lease-status,x-ms-blob-type,Content-Length,Date,Transfer-Encoding
cache-control: no-store
content-length: 717482
content-md5: udXkOLdHneZZssXqa/wvwg==
content-type: application/json
date: Sun, 22 Apr 2018 20:19:19 GMT
etag: 0x8D5A884A4FB459E
last-modified: Sun, 22 Apr 2018 19:09:59 GMT
server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
strict-transport-security: max-age=31536000
x-cdn-rewrite: Root path in dist
X-Firefox-Spdy: h2
x-ms-blob-type: BlockBlob
x-ms-lease-status: unlocked
x-ms-request-id: b16fa188-b01e-0018-8077-da1dc0000000
x-ms-version: 2009-09-19
```

I hit this page, but it doesn't really matter what request you make; none of the responses are compressed:
https://api.nuget.org/v3/catalog0/index.json

Sizes and cursory testing:
* 700KB uncompressed
* ~134KB with "normal", non-aggressive gzip compression (7zip "normal")
* ~129KB with aggressive gzip (7zip "maximum")
* ~128KB with very aggressive compression (7zip "ultra")

**Comment by skofman1** [comment]
@rianjs , unlike the Gallery which is a service, the content in V3 APIs is served by CDN and is static files hosted on Azure blob storage.  
We use g-zip for V3 APIs only where it's crucial for official client (nuget.exe, dotnet.exe, Visual Studio) performance, which is only registration files: https://api.nuget.org/v3/registration3-gz/newtonsoft.json/index.json

Since clients don't use catalog as part of the protocol, we never g-zipped the catalog.
