### ISSUE TITLE
Crud.Entity 1.1.1 is missing from V3

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#5856]
Unlisted, but exists:
https://www.nuget.org/packages/Crud.Entity/1.1.1

Seems to be missing from packages container, which would result in it never making it into the catalog.

Not in flat container:
https://api.nuget.org/v3-flatcontainer/crud.entity/index.json

Full discrepancies:
https://explorepackages.azurewebsites.net/Home/Explore/Crud.Entity/1.1.1

**Comment by skofman1** [comment]
This is from 2 months ago. We should be able to investigate why the package upload failed.

**Comment by joelverhagen** [comment]
Perhaps it is still in the `validation` container.

**Comment by scottbommarito** [comment]
@agr and I looked into this. It's a result of https://github.com/NuGet/NuGetGallery/issues/5625, which we have since fixed. Basically, saving the ReadMe committed the package, but then the actual commit of the package failed, leaving the package in a corrupted state--in the database but not in any containers.

**Comment by scottbommarito** [comment]
Will contact package owners and delete the package.
