### ISSUE TITLE
Autocomplete query for Microsoft.CodeA doesn't return any results

### ISSUE THREAD

**Issue by svick** [NuGet/NuGetGallery#5858]
It seems that when I make an autocomplete query to the API, I sometimes don't get any results, even when a package with the given prefix exists.

Specifically:

* https://api-v2v3search-0.nuget.org/autocomplete?q=Microsoft.Code works fine
* https://api-v2v3search-0.nuget.org/autocomplete?q=Microsoft.CodeA doesn't return anything
* https://api-v2v3search-0.nuget.org/autocomplete?q=Microsoft.CodeAna doesn't return anything
* https://api-v2v3search-0.nuget.org/autocomplete?q=Microsoft.CodeAnal works fine

**Comment by ryuyu** [comment]
This is due to the way that we currently store and match the ids for "autocompletion".
Without going into too much detail, it appears that there is a bug when there are partial tokens within tokens shorter than 8 characters (ie Microsoft.Code -> Microsoft, Code; Microsoft.CodeA -> Microsoft, CodeA, Code, A). You can notice this same issue with Microsoft.AspNet vs Microsoft.AspN

I have experimented with a quick fix to this by not splitting on camelcasing.
This results in the following: 
http://localhost:24862/autocomplete?q=Microsoft.CodeA
{
"@context": {
"@vocab": "http://schema.nuget.org/schema#"
},
"totalHits": 8,
"lastReopen": "2018-05-02T20:22:54.8334269Z",
"index": "C:\\Users\\ryuyu\\Desktop\\newindex1",
"data": [
"Microsoft.CodeAnalysis.CSharp",
"Microsoft.CodeAnalysis.Common",
"Microsoft.CodeAnalysis",
"Microsoft.CodeAnalysis.Analyzers",
"Microsoft.CodeAnalysis.VisualBasic",
"Microsoft.CodeAnalysis.Workspaces.Common",
"Microsoft.CodeAnalysis.CSharp.Workspaces",
"Microsoft.CodeAnalysis.VisualBasic.Workspaces"
]
}

However, fixing it in this manner requires nontrivial amount of work on our side.
I'm also unsure of what other effects this might have on the service as I modified one of the analyzers.

How critical is this scenario being correct for you? @svick

**Comment by svick** [comment]
> How critical is this scenario being correct for you?

I'm not sure. On one hand, I think `dotnet add package` command line autocompletion (which is the reason this API matters to me) should be predictable and in general work well. On the other hand, I'm not sure how many people are using that, since it currently requires [manual installation](https://github.com/dotnet/cli/blob/master/Documentation/general/tab-completion.md#how-to-enable-it).

**Comment by joelverhagen** [comment]
This is resolved since Azure Search shipped.
https://azuresearch-usnc.nuget.org/autocomplete?q=Microsoft.CodeA
https://azuresearch-usnc.nuget.org/autocomplete?q=Microsoft.CodeAna

In your code, please use the service index to discover search URLs. The documentation for the service index is here:
https://docs.microsoft.com/en-us/nuget/api/service-index
