### ISSUE TITLE
Nuget server 3.1.2 issue with lastupdated and updated date

### ISSUE THREAD

**Issue by bamayer1** [NuGet/NuGetGallery#5880]
I am using the latest nuget server 3.1.2. The server is up an running. I notice, that every hour the dates of all packages are changing, even if no package has been pushed to the nuget server. What process could cause this? I recycled and stopped/started the application pool of the nuget server, this didnt cause the changes. Also, if I read the dates lastupdated and updated of the published packages with a powershell script, I get inconsistent results. E.g. the date retrieved with powershell is not the date of the package seen in the file explorer.
Best regards

**Comment by skofman1** [comment]
@bamayer1 , sorry for the late response. We totally misses the issue. Did you ever find out what caused the timestamps to change?

**Comment by dac11** [comment]
We had this issue  with Nuget Server 3.3.0. The lastupdated date was renewed regularly.
After we changed the application pool to domainuser with proper permissions on the Packagegfolder the problem was fixed.

We did migrate the old nugetpakages by filecopy into the new server. The Server processed each package and copied into subdirectory. The originial file could not be deleted, so the process was repeated again and again which caused the update on lastupdated
