### ISSUE TITLE
HTTP 500 error when verifying a new account

### ISSUE THREAD

**Issue by kbaley** [NuGet/NuGetGallery#5889]
We're converting our company username/password account into an organization. Here's what happened leading up to the HTTP 500 error

- In Chrome, I logged into our company nuget account (with a username/password)
- In Firefox, I created a new account for myself using my Microsoft account
- I received the email asking me to verify my account
- I clicked the verify link which launched Chrome (where I was already logged in but to a different account)

At this point, I received the error:

![image](https://user-images.githubusercontent.com/130546/39647691-9673a94a-4fa5-11e8-8fb4-9e16fda7169f.png)

**Comment by scottbommarito** [comment]
Thanks for reporting this issue.

The verify link is intended to be opened while logged in as the account you are verifying. In other words, in your situation, we expected you to open the link from Firefox and not Chrome.  If you try opening the link while logged in as your new account it should work.

Regardless, the server should not have returned 500, and should have instead told you that the verify link you clicked was not for your company's NuGet account.

I tried looking at our exception logs and didn't see your request at a glance.
Could you tell me what your NuGet account usernames are (both your company account and your new account) so I can find the logs more easily?
If you don't want to post this information publicly, feel free to send an email to support@nuget.org mentioning this issue along with the usernames.

**Comment by scottbommarito** [comment]
I was able to find the logs and determine the bug in the code. No need to send your usernames.

**Comment by skofman1** [comment]
Investigation: 
Repro steps:
1. Create account A 
2. Create account B
3. Log in with account A
4. Click on account confirmation link for account B. 

Result: 500 page (NullReferenceException)
Expected: a nice message

The issue is here: https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Controllers/AccountsController.cs#L130

GetAccount returns null when there's a mismatch, while [here](https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Controllers/AccountsController.cs#L136) we try to get the username from the null ref
