### ISSUE TITLE
IsLatestVersion Metadata flag is always false with query param semVerLevel=2.0.0

### ISSUE THREAD

**Issue by zhili1208** [NuGet/NuGetGallery#5904]
@morad3741 commented on [Sun May 06 2018](https://github.com/NuGet/Home/issues/6911)

Hi,
Ive encountered some inconsistency with the Search and FindPackagesById endpoints, i would like to get your opinion on that:

1. When reaching:
https://www.nuget.org/api/v2/FindPackagesById()?id=%27sleet%27
Ive noticed the next metadata: 
> <d:IsLatestVersion m:type="Edm.Boolean">true</d:IsLatestVersion>

on entry with version: 1.0.1,
but when reaching the same endpoint with semVerLevel param:
https://www.nuget.org/api/v2/FindPackagesById()?id=%27sleet%27&semVerLevel=2.0.0
there is no entry with IsLatestVersion flag set to true,
why is that?

2. When using nuget list command the client reaching to:
https://www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=Id&searchTerm=%27sleet%27&targetFramework=%27%27&includePrerelease=false&$skip=0&$top=30
you will notice 2 entries with IsLatestVersion flag set to true : 1.0.1 & 0.2.5 (Why there is two versions with that flag?),
but when doing the same query with semVerLevel=2.0.0 param:
https://www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=Id&searchTerm=%27sleet%27&targetFramework=%27%27&includePrerelease=false&$skip=0&$top=30&semVerLevel=2.0.0
there is no entry with IsLatestVersion flag set to true,
why is that?

thank you for your help.

**Comment by morad3741** [comment]
Hi, any progress with the issue?

**Comment by chenriksson** [comment]
Re: `/api/v2/FindPackagesById()?id=%27sleet%27&semVerLevel=2.0.0`
This looks like a bug, as version "2.3.22+git.ed45aa9" is marked as the latest for semVerLevel2 in the DB.

Re: `https://www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=Id&searchTerm=%27sleet%27&targetFramework=%27%27&includePrerelease=false&$skip=0&$top=30`
This is expected. The searchTerm is matching two packages: `Sleet` (latest=1.0.1) and `Sleet.Azure` (latest=0.2.5)

Re: `https://www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=Id&searchTerm=%27sleet%27&targetFramework=%27%27&includePrerelease=false&$skip=0&$top=30&semVerLevel=2.0.0`
Version "2.3.22+git.ed45aa9" should be marked as latest for semVerLevel=2. This may be the same bug as the first, since `FindPackagesById` uses the search service.

@zhili1208 I need to investigate further to understand the issue, but will let you know.

**Comment by skofman1** [comment]
@morad3741 , can you share details about your scenario?
We recommend using our V3 APIs to search for packages. You can find the documentation here: https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource

The search results allow you to see the latest package version.

**Comment by chenriksson** [comment]
The Gallery bug is here:
https://github.com/NuGet/NuGetGallery/blob/9eb4bc49f7f34339b0fc4a6183f9265509961cdd/src/NuGetGallery/Infrastructure/Lucene/ExternalSearchService.cs#L138

Search correctly returns true for `IsLatest` and `IsLatestStable` when `semVerLevel=2.0.0` is passed. However, when the Gallery populates a package entity with the response, it should account for the `IsLatestSemVer2` and `IsLatestStableSemVer2` properties which aren't returned by search.

Working on a fix.

**Comment by chenriksson** [comment]
@morad3741 @zhili1208 - the issue should be fixed now.
