### ISSUE TITLE
Document how to stand up NuGet Gallery with MSA/AAD support

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#6079]
The README.md does not have details on how to enable MSA/AAD support for Gallery. We should list the steps required.

/cc: @skofman1

**Comment by shishirx34** [comment]
**Configuring MSA/AAD for your on-prem gallery instance**

1. Register an app for authenticating with your AAD: Sign in with your work/personal account on https://apps.dev.microsoft.com
2. Goto Application Registration Portal tab
3. Under "Converged Applications" click "Add an app"
4. Give a name.
5. Under platforms section, create a web platform if one doesn't exist
6. Check `Allow implicit flow` and `Restrict token issuing to this app`
7. Under target domain add: `<Your domain>` eg: `nuget.org`
8. Under Redirect URIs: `https://<Yourdomain>/users/account/authenticate/return` (NOTE: this is a must format otherwise it will give error, also note the 'https')
9. Note down ApplicationId and Application secret.
10. In your local nuget gallery instance, set the values copied in step 9 in `web.config` for Keys: `Auth.AzureActiveDirectoryV2.ClientId` and `Auth.AzureActiveDirectoryV2.ClientSecret` respectively. Also set the value for key `Auth.AzureActiveDirectoryV2.Enabled` to `true` so that you can see the login with microsoft account button on login page of gallery.
11. Note: This authenticates the gallery with the v2 common workflow, It means any AAD/personal
 MSA account will be able to create an account and publish packages to your on-prem gallery. If you want to authenticate with only specific AAD, for now, you will need to make a code change. 
	1. Update the [AzureActiveDirectoryV2AuthenticatorConfiguration](https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Authentication/Providers/AzureActiveDirectoryV2/AzureActiveDirectoryV2AuthenticatorConfiguration.cs#L53). Set the authority tenant ID to your AAD Tenant ID:
	```
	openIdOptions.Authority = String.Format(CultureInfo.InvariantCulture, AzureActiveDirectoryV2Authenticator.Authority, "<Your AAD Tenant ID>");	
	``` 
12. This should get your gallery up and running integrated with your specific AAD Account.

**Comment by skofman1** [comment]
@shishirx34 , Thanks for the write up! Can you create a wiki page here https://github.com/NuGet/NuGetGallery/wiki with those details.

**Comment by shishirx34** [comment]
Done: https://github.com/NuGet/NuGetGallery/wiki/Configuring-MSA-AAD-for-your-on-prem-gallery-instance

**Comment by anangaur** [comment]
Can you also reference the wiki from the README.md ?

**Comment by shishirx34** [comment]
https://github.com/NuGet/NuGetGallery/pull/6093
