### ISSUE TITLE
How do I access the rest API on a self hosted gallery?

### ISSUE THREAD

**Issue by matthewjones555** [NuGet/NuGetGallery#6121]
_Firstly, sorry if this is in the wrong place, is there a more appropriate forum for asking questions about self hosted nuget galleries?_

I'm running a self hosted nuget gallery, let's say the host name is **selfhosted.azurewebsites.net**.

I'm able to succesfully push packages and delete packages using the v2 api on the following url

https://selfhosted.azurewebsites.net/api/v2/package

but I'm unable to use the v3 rest api, I just keep getting 404 errors.

So far I've tried:

https://selfhosted.azurewebsites.net/api/v3
https://selfhosted.azurewebsites.net/api/v3/index.json
https://selfhosted.azurewebsites.net/v3/index.json
http://selfhosted.azurewebsites.net/api/v3
http://selfhosted.azurewebsites.net/api/v3/index.json
http://selfhosted.azurewebsites.net/v3/index.json

Everything I've tried results in a 404.  Is there any documentation about self hosting the rest api?  Is it in a separate project?

I've been searching for hours, and am either looking in the wrong place, or there's too much search noise, or it doesn't exist.

Thanks for any help you can offer.

**Comment by loic-sharma** [comment]
# nuget.org's v3 API

If you would like to run the same code as nuget.org, you will need to setup several jobs and services from the [NuGet.Services.Metadata](https://github.com/NuGet/NuGet.Services.Metadata) project:

1. [feed2catalog](https://github.com/NuGet/NuGet.Services.Metadata/blob/master/src/Ng/Scripts/Feed2CatalogV3.cmd) job
2. [catalog2registration](https://github.com/NuGet/NuGet.Services.Metadata/blob/master/src/Ng/Scripts/Catalog2RegistrationV3-Reg3.cmd) job
3. [catalog2dnx](https://github.com/NuGet/NuGet.Services.Metadata/blob/master/src/Ng/Scripts/Catalog2DnxV3.cmd) job
4. [catalog2lucene](https://github.com/NuGet/NuGet.Services.Metadata/blob/master/src/Ng/Scripts/Catalog2LuceneV3-Reg2.cmd) job
5. [Search service](https://github.com/NuGet/NuGet.Services.Metadata/tree/master/src/NuGet.Services.BasicSearch)

I wouldn't recommend this route unless you're expecting massive amounts of package downloads.

# BaGet

The [BaGet](https://github.com/loic-sharma/BaGet) project makes it way easier to host a NuGet v3 endpoint. It scales up pretty well, but it isn't as battle tested as nuget.org.

Let me know if you have any questions!

**Comment by loic-sharma** [comment]
Closing this issue for now. Feel free to open another issue if you have any additional questions @matthewjones555

**Comment by DoctaJonez** [comment]
@loic-sharma, is there any documentation detailing how to set these services up?

If not, are there any plans to create documentation?

**Comment by loic-sharma** [comment]
# BaGet

For [BaGet](https://github.com/loic-sharma/BaGet), you just `dotnet run` the project. That's it! I seriously recommend you go this route, otherwise you're in for a headache.

#  nuget.org's v3 services

Sadly, our documentation could be greatly improved in this area. You will need to (this is all off the top of my head, so please excuse any missing information):

1. Setup at least one machine
2. Setup an Azure Blob Storage account with the following containers:
  a. "index" - Hosts [the service index](https://docs.microsoft.com/en-us/nuget/api/service-index)
  b. "packages" - The Gallery's copy of NuGet packages, used by v3's ingestion pipeline
  c. "catalog" - This hosts the [catalog resource](https://docs.microsoft.com/en-us/nuget/api/catalog-resource)
  d. "registration" - This hosts the [metadata resource](https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource)
  e. "flat-container" - This hosts the [package content resource](https://docs.microsoft.com/en-us/nuget/api/package-base-address-resource)
  f. "auditing" - This stores package deletions from Gallery, used to populate the catalog
3. Run the [Gallery](https://github.com/NuGet/NuGetGallery)
  a. Configure `StorageType` to be `AzureStorage`  [here](https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Web.config#L27)
  b. Configure the Gallery to point to the "packages" container [here](https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Web.config#L33)
  c. Configure the Gallery to point to the "auditing" container [here](https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Web.config#L29)
4. Build [NuGet.Services.Metadata](https://github.com/NuGet/NuGet.Services.Metadata)
5. Deploy the built `ng.exe` and all of its DLLs to your machine
6. Run the `feed2catalog` job to populate the catalog resource:

```
Ng.exe feed2catalog ^
    -gallery https://yourgalleryurl.com/api/v2 ^
    -storageBaseAddress <https://azure.bob.storage.url.com>/catalog ^
    -storageType azure ^
    -storageAccountName <Blob Storage account name here> ^
    -storageKeyValue <Azure Blob Storage account key here> ^
    -storageContainer catalog ^
    -storageTypeAuditing azure ^
    -storageAccountNameAuditing <Blob Storage account name here> ^
    -storageKeyValueAuditing <Azure Blob Storage account key here> ^
    -storageContainerAuditing auditing ^
    -storagePathAuditing package
    -verbose true ^
    -interval 30
```

7. Run the `catalog2registration` job to populate the metadata resource

```
Ng.exe catalog2registration ^
    -source <https://azure.bob.storage.url.com>/catalog/index.json ^
    -contentBaseAddress <https://azure.blob.storage.url.com>/flat-container/ ^
    -storageBaseAddress <https://azure.blob.storage.url.com>/registration/ ^
    -storageType azure ^
    -storageAccountName <Azure Blob Storage account name here> ^
    -storageKeyValue <Azure Blob Storage account key here> ^
    -storageContainer registration ^
    -useCompressedStorage false ^
    -verbose true ^
    -interval 30
```

8. Run the `catalog2dnx` job to populate the package content resource

```
Ng.exe catalog2dnx ^
    -source <https://azure.blob.storage.url.com>/catalog/index.json ^
    -contentBaseAddress <https://azure.blob.storage.url.com>/packages ^
    -storageBaseAddress <https://azure.blob.storage.url.com>/flat-container ^
    -storageType azure ^
    -storageAccountName <Azure Blob Storage account name here> ^
    -storageKeyValue <Azure Blob Storage account key here> ^
    -storageContainer flat-container ^
    -verbose true ^
    -interval 30 ^
    -httpClientTimeoutInSeconds 900
```

I've updated this issue track the documentation work: https://github.com/NuGet/NuGetGallery/issues/6142. Let me know if you have any questions.
