### ISSUE TITLE
Automatically reserve username package prefix

### ISSUE THREAD

**Issue by nkolev92** [NuGet/NuGetGallery#6138]
_From @dasMulli on July 3, 2018 17:45_

The bar to register a prefix on nuget.org is "quite high" at the moment and requires manual steps, which is good for arbitrary prefixes.

I suggest automatically reserving the prefix matching the username of nuget.org users.

E.g. my username is "dasMulli", so I should be the only one allowed to upload new packages starting with "DasMulli."

_Copied from original issue: NuGet/Home#7088_

**Comment by skofman1** [comment]
@diverdan92 ?

**Comment by diverdan92** [comment]
I think this goes against the purpose of ID prefix reservations. Since the reservation indicates authenticity between the owner and the author they are identifying, some form of manual approval will be necessary (to confirm the legitimacy of the request). If we were to consider reserving user name prefixes, then we would need to manually approve all NuGet.org user names so that nobody claims a name that doesn't belong to them. 

Marking this closed as I don't think we should do this, but please let me know if you disagree.
