### ISSUE TITLE
Investigate: package that had existed now returns 404

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#6201]
@chenriksson commented on [Mon Jul 23 2018](https://github.com/NuGet/Engineering/issues/1561)

https://twitter.com/karann9/status/1021295981424328704

![image](https://user-images.githubusercontent.com/15364949/43095983-65ea52e6-8e6c-11e8-8ae0-5517f3bcdc7a.png)

/cc @anangaur

**Comment by chenriksson** [comment]
Example package from customer:
https://www.nuget.org/packages/Tangari.XrmToolBoxExtensions.BulkRecordAssigner

**Comment by chenriksson** [comment]
VS 2017 install of package fails due to "Unable to resolve dependency 'XrmToolBox'"... it appears the dependent package doesn't exist on nuget.org. I can get around this by with the "ignore dependencies" [install option](https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui#install-and-update-options), and can also download the package directly from nuget.org to get the DLLs.

Need to determine if this is what the customer is seeing.

**Comment by anangaur** [comment]
I guess the claim is that it used to exist so wanted to understand if that was the case.

**Comment by chenriksson** [comment]
The dependency (below) doesn't exist, and I don't see any history of it:
https://www.nuget.org/packages/XrmToolBox/1.2017.1.11

There is a similar package:
https://www.nuget.org/packages/XrmToolBoxPackage/1.2017.1.11

My guess is that install used to work because it was either getting the dependency from a different feed, or because client tooling originally ignored dependencies. I need more details from the customer to understand their scenario... will leave this open for a few days to wait for a response.

**Comment by chenriksson** [comment]
Closing due to no response... feel free to reopen if you hear back.

/cc @anangaur @skofman1
