### ISSUE TITLE
Download count is incorrect

### ISSUE THREAD

**Issue by RajRele** [NuGet/NuGetGallery#6206]
Hi Team, I am pretty sure that DocuSign has more count than what is currently shown on the recent release... I don't see Download count getting updated. Any help? https://www.nuget.org/packages/DocuSign.eSign.dll/3.0.0-rc
Thanks,

**Comment by rianjs** [comment]
Stats have been broken for about a week. It’s an ongoing problem.

**Comment by loic-sharma** [comment]
Hello. Thank you for letting us know, we are investigating.

**Comment by chenriksson** [comment]
Our job to collect CDN logs for Global/US region was down since 7/19. Looks like specific CDN log(s) may have had parsing errors which caused the job to fail.

Unfortunately, we're lacking monitoring on the log collection. We have issues tracking this, which should be prioritized asap:
- Stats - Monitor activity of W3C log collector (https://github.com/NuGet/NuGetGallery/issues/3248)
- Statistics: monitor CollectAzureCdnLogs (https://github.com/NuGet/NuGetGallery/issues/6082)

Current status - I'm looking into skipping over the failed logs to restore the job, then we'll be playing catch up for at least a few days.

**Comment by ttutisani** [comment]
I have the same issue. Looking forward to updates!

**Comment by chenriksson** [comment]
I've skipped a few problematic logs, and we seem to be catching up nicely. We had around 650 logs to process 10 hours ago, and about 285 now. Once we're caught up, I'll look into the problematic logs and see that we get them processed.

**Comment by chenriksson** [comment]
@agr Reassigning to you to finish the work.

Per hand-off discussion, there are a few dead lettered logs to retry as well as the logs that I skipped (https://github.com/NuGet/Engineering/issues/1576). You may also want to verify that the collect job is caught up now... I think it is.

**Comment by agr** [comment]
Reprocessing of the logs is done, there were few corrupted log files I had to discard, they accounted for under 5% of total amount of logs that had to be re-processed. Download counts on nuget.org should update in few hours.

**Comment by joelverhagen** [comment]
@RajRele, @rianjs, @ttutisani, if you have seen any other statistics issues please let us know by opening a new GitHub issue. This particular outage incident has been resolved.

**Comment by RajRele** [comment]
Thanks everyone working this!
