### ISSUE TITLE
Package upload page should show which user the package is uploaded for

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#6286]
Repro:
1. Login as an admin/collaborator of an org 
2. Upload a package where the namespace is reserved to an org

**Current behavior:** the organization the package is uploaded for is automatically recognized and the "choose owner for upload" drop down is not shown.

**Suggestion:** show the owner the package will be uploaded for. It can be a disabled drop down or simply text.

@anangaur

**Comment by lyndaidaii** [comment]
@skofman1 I am trying to reproduce this problem, I found out current behavior is it shows owner of package when I upload a package with reserved namespace as you suggested. 
Please see attachment below: 
![owner_6286](https://user-images.githubusercontent.com/64443925/84445032-f130cb00-abf7-11ea-8d17-e6843f15a73c.PNG)
Let me know if there is any problem, otherwise I will go ahead close this issue.

**Comment by skofman1** [comment]
@lyndaidaii , are you a collaborator on an organization?

**Comment by lyndaidaii** [comment]
> @lyndaidaii , are you a collaborator on an organization?

Yes, I am Administrator of an organization

**Comment by skofman1** [comment]
great! closing!
