### ISSUE TITLE
[Bug]Email hint might be wrong in some cases

### ISSUE THREAD

**Issue by ryuyu** [NuGet/NuGetGallery#6336]
User saw this prompt
![image](https://user-images.githubusercontent.com/11051729/44435464-f5907d80-a564-11e8-9829-841d2f0e3fab.png)

However, examination showed that he had a Microsoft account tied to his account.
The Microsoft account email was different from the one listed here.

**Comment by shishirx34** [comment]
The listed email address is not the "Microsoft login", its the email account associated with the account(previously used for password authentication). It is the email address we use for communication. Once this associated communication email address is correctly entered, we send the details of the associated "Microsoft account"(which could be a different email) to this linked email address. 

This is by design. @anangaur - do you think we can elaborate this with a better message here?

**Comment by shishirx34** [comment]
Talked offline with @ryuyu - this is by design.
