### ISSUE TITLE
View  twitter shares doesnt work properly

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#638]
[anurse]
Right now we include the scheme in the URL we give Twitter. This causes this problem and also means there is a difference between http://nuget.org/packages/jQuery and httpS://nuget.org/packages/jQuery, which is bad.

====
1. Post twitter messages for a package from preview.nuget.Org.
2. The "no of tweets" button on packages page gets updated after a long time.
Guess, its not in our control and that's how the tweeter plugin behaves.

3. Once it updates the number say to  "2" , clicking on that takes me to twitter search result for "https://preview.nuget.org/package/packagename" and the search always returns 0 results.
This also looks like some issue on twitter side, but it is a really required info.
As an end user, I would be interested in seeing what people have shared about this page.

**Comment by robertmuehsig** [comment]
I guess this is obsolete, because Twitter itself removed the "twitter shares-count" stuff from their API (at least it is not so easy anymore https://twittercommunity.com/t/clarification-about-share-counts-for-the-new-tweet-button/52868/35) and due to my PR https://github.com/NuGet/NuGetGallery/pull/2975 the "sharing" buttons are now just simple links.
No counting - no issue :sunglasses:
