### ISSUE TITLE
Visual Issue: Organization forms are smaller then other forms

### ISSUE THREAD

**Issue by robertmuehsig** [NuGet/NuGetGallery#6725]
I noticed that this form has much more spacing:

![image](https://user-images.githubusercontent.com/756703/49545977-7c345500-f8df-11e8-9e87-fee1b7ccdb0d.png)

... then other forms, e.g.:

![image](https://user-images.githubusercontent.com/756703/49546025-95d59c80-f8df-11e8-835a-717bb365c119.png)

This leads to some "jumping" in the navigation:

![gif](https://user-images.githubusercontent.com/756703/49546172-ea791780-f8df-11e8-8615-cc1cd83d7761.gif)

Also the org management page has some margins around the actual site, which is not present on the other pages:

![image](https://user-images.githubusercontent.com/756703/49546274-1f856a00-f8e0-11e8-9d89-70281c38b4b8.png)

Is this "by design" or a good candidate for "up for grabs"?

**Comment by scottbommarito** [comment]
I remember we initially had all of these forms only 10 columns instead of 12, but then we changed some of them to 12 but not all of them.

Culprit is https://github.com/NuGet/NuGetGallery/commit/5749f9c10a40fc803ad1fe9a595e15f0a12b67fd
(notice the removal of `ViewBag.MdPageColumns = Constants.ColumnsFormMd;` in several files)

@joelverhagen - Do you remember why this was changed? Is it ok to go ahead with aligning these organization pages.

@anangaur - Do you like 10 or 12 columns for these pages better? I prefer 12, but it's up to you.

**Comment by anangaur** [comment]
The jump does look bad. We should be consistent. 12 looks better.

**Comment by robertmuehsig** [comment]
If the NuGet Team is not to keen on fixing this in the next 12 hours I could send you a PR.

**Comment by scottbommarito** [comment]
@robertmuehsig - go ahead!

**Comment by robertmuehsig** [comment]
Ok - instead of removing this setting I just set it to 12 and re applied it to the missing pages. 

![image](https://user-images.githubusercontent.com/756703/49615901-3e9efd00-f9af-11e8-983e-1ee6fe64a996.png)

The sm-12 md-??? calculation stuff seems to be used on all (? at least it seems very often) pages and with this setting you still could change it later globally. 

Hope this helps
