### ISSUE TITLE
Error 400 (Bad request) when pushing a valid semver 2.0 versioned package.

### ISSUE THREAD

**Issue by olivier-spinelli** [NuGet/NuGetGallery#6819]
7.1.1--0058-develop is a valid semver 2.0 syntax, however when trying to push it to nuget.org, it fails with the following (hopefully explicit) error.

> Response status code does not indicate success: 400 (The NuGet package contains an invalid .nuspec file. The error encountered was: 'The package manifest contains an invalid Version: '7.1.1--0058-develop''. 

I'm aware that, currently, the actual target feed to push is https://www.nuget.org/api/v2/package/. Is the v2 here the culprit? 
Did I miss a configuration?

**Comment by skofman1** [comment]
@olivier-spinelli , some old nuget client versions (2.x) had a bug parsing certain version strings. This bug was fixed a long time ago, however nuget.org still blocks uploading packages with such versions since it will break old clients (see code here for [reference](https://github.com/NuGet/NuGetGallery/blob/619bede5c0580cd553d4b5332f35454a12ebebbf/src/NuGetGallery.Core/Packaging/ManifestValidator.cs#L182)).

This website will allow you to test which version formats will work: http://nugettoolsdev.azurewebsites.net/2.8.3/parse-version?version=7.1.1--0058-develop

For example, a version like `7.1.1-a0058-develop` will work (no -- and prerelease label starts with a letter).
