### ISSUE TITLE
Unable to upload package

### ISSUE THREAD

**Issue by mediumTaj** [NuGet/NuGetGallery#6824]
I'm unable to upload my NuGet package.

```
This package ID has been reserved. Please request access to upload to this reserved namespace from the owner of the reserved prefix, or re-upload the package with a different ID.
```

I have no idea who may own the package ID. I'm guessing it's not listed.
```
IBM.WatsonDeveloperCloud.CompareComply.v1
```

**Comment by shishirx34** [comment]
Hi @mediumTaj - you were blocked due to namespace reservation and not due to existing package.

We have implemented namespace reservation for some popular corporations in advance to protect our customers and community at large from misleading package Ids _appearing to be_ from the official sources. As such IBM* namespace has been reserved.

From your profile I see that you work for IBM? If that is the case we encourage you to take the ownership of this namespace. Check out our namespace reservation feature [here](https://docs.microsoft.com/en-us/nuget/reference/id-prefix-reservation). If you meet the criteria for the prefix reservation you'll be given access to the namespace after which you should be able to push the specified package + enjoy all the benefits you gain from prefix reservation :)

**Comment by mediumTaj** [comment]
Ok perfect I will look into reserving. Thank you!
