### ISSUE TITLE
Statistic page shows repeated week "12/31/2018 - 1/7/2019"

### ISSUE THREAD

**Issue by zhhyu** [NuGet/NuGetGallery#6836]
The statistic page in gallery shows repeated week "12/31/2018 - 1/7/2019", which is wrong. The graph of downloaded packages per week is not correct too.

![image](https://user-images.githubusercontent.com/41028779/51630112-299a1100-1efe-11e9-90f0-071220c1c381.png)

**Comment by agr** [comment]
This happens, because last day of the 2018 was Monday and it was 53rd week of the year. The [sproc](https://github.com/NuGet/NuGet.Jobs/blob/master/src/Stats.Warehouse/Programmability/Stored%20Procedures/dbo.DownloadReportLast6Weeks.sql) that produces the data for this report works like this:
1.	It figures out which day was 42 days ago;
2.	Checks which week was containing that day (so for 1/17/2019 it finds out that 42 days ago it was 49th week of 2018).
3.	It takes 6 weeks of data starting from that week (so, again, for 1/17/2019, it will grab data for weeks 49, 50, 51, 52, 53 and 1 (of 2019), regardless of the fact that 53 of 2018 and 1 of 2019 is the same week) and returns it.
