### ISSUE TITLE
List packages in Hosted NuGetGallery - The V2 feed at '...' returned an unexpected status code '404 Not Found'.

### ISSUE THREAD

**Issue by satano** [NuGet/NuGetGallery#7012]
I have [created a NuGetGallery](https://github.com/NuGet/NuGetGallery#build-and-run-the-gallery-in-arbitrary-number-easy-steps) web application and [deployed it to Azure](https://github.com/NuGet/NuGetGallery/blob/master/docs/Deploying/README.md).

The NuGetGallery is correctly running (say on `https://xxx.azurewebsites.net`). I was able to register a new user and generated API key.

A was also able to push package there:

`nuget push DemoPackage.1.0.0.nupkg apikey -Source https://xxx.azurewebsites.net`

The package is there - I can see it using web interface.

But listing and installing packages from this NuGetGallery is not working.

When I try to list packages (`nuget list -Source https://xxx.azurewebsites.net`), I got error:

> The V2 feed at 'https://xxx.azurewebsites.net/Search()?$filter=IsLatestVersion&$orderby=Id&searchTerm=''&targetFramework=''&includePrerelease=false&$skip=0&$top=30&semVerLevel=2.0.0' returned an unexpected status code '404 Not Found'.

When I try to install package (`nuget install DemoPackage -Source https://xxx.azurewebsites.net`), I got similar error:

> Installing package 'DemoPackage' to '...path...'.
  GET https://xxx.azurewebsites.net/FindPackagesById()?id='DemoPackage'&semVerLevel=2.0.0
  NotFound https://xxx.azurewebsites.net/FindPackagesById()?id='DemoPackage'&semVerLevel=2.0.0 99ms
An error occurred while retrieving package metadata for 'DemoPackage' from source 'KrosNuGet'.
  Failed to fetch results from V2 feed at 'https://xxx.azurewebsites.net/FindPackagesById()?id='DemoPackage'&semVerLevel=2.0.0' with following message : Response status code does not indicate success: 404 (Not Found).
  Response status code does not indicate success: 404 (Not Found).

I also looked an issues #5370 and #6578 but there is no resolution.

So my question is. What should I do to make NuGetGallery work?

**Comment by joelverhagen** [comment]
Hey @satano, glad to hear you're using NuGetGallery! On Azure none the less 🥇.

Could you try using the source URL `https://xxx.azurewebsites.net/api/v2`, i.e. add `/api/v2` to the end?

For an analogy, nuget.org's `Packages()` and `FindPackagesById()` endpoints are also under `/api/v2`:
https://www.nuget.org/api/v2/Packages(Id='Newtonsoft.Json',Version='9.0.1')
https://www.nuget.org/api/v2/FindPackagesById()?id=%27Newtonsoft.Json%27

**Comment by satano** [comment]
Thanks a lot @joelverhagen. This works. ❤️ 

Just a question. What is the difference between v2 and v3 api? It seems https://www.nuget.org/ uses v3 - so why not NuGetGallery?.

**Comment by loic-sharma** [comment]
V2 APIs are quite flexible and require a database, which makes it difficult to scale out to nuget.org's size. You can think of the V3 APIs as a bunch of static JSON files, which is easier to scale out.

Some helpful links:
* V3 API documentation: https://docs.microsoft.com/en-us/nuget/api/overview
* nuget.org's V3 implementation: https://github.com/nuget/nuget.services.metadata
* Guide on how to setup nuget.org's V3 services: https://github.com/NuGet/NuGetGallery/wiki/Hosting-nuget.org's-v3-services

**Comment by joelverhagen** [comment]
Thanks for the links, @loic-sharma.

For nuget.org, the main difference between V2 and V3 is how they are implemented. V2 API is built on top of SQL Server and the V3 API is built on top of Azure blob storage and Lucene for search.

A bit of history. As nuget.org's traffic increased exponentially, it became harder and harder to meet the traffic demands with a SQL database. As you may know, Azure SQL gets very expensive as it scales up and has a maximum size it can reach. Therefore, V3 was implemented on technologies that a small team (us 😄) could reasonably manage as traffic increased. We don't have to manage a million compute resources as traffic scales. All of the V3 endpoints used for `nuget.exe restore` are implemented on top of blob storage, which has great availability, is quite cheap, and can be further improved with a CDN in front. I am glossing over details a bit but that's the key difference when V3 split off in the way it did.

V2 is a much more flexible API since it is built on top of OData and therefore supports arbitrary queries beyond the ones nuget.exe perform. For example, you can sort by and package field, do skip/take operations, etc. At nuget.org's current traffic volumes, this is very hard to scale on SQL since the query patterns are nearly infinite. In other words, OData can let you do queries that are not possible on V3.

It's true that V2 is the "old" API and V3 is the "new" API, but V2 has some benefits for small deployments of NuGetGallery (or [NuGet.Server](https://github.com/NuGet/NuGet.Server)). It has fewer moving parts so maintenance is easier. Our implementation of V3 has at least 4 background jobs running to keep the blobs up to date. For NuGetGallery + V2, you just need an app service and a SQL database. Much easier. NuGet.Server is even simpler with just an app service (no SQL required).

Right now, there are few differences in the V2 and V3 API surface area (i.e. what the APIs can do) so client experience is very similar. As time goes on though, it's possible there will be greater divergence and we'll need to revisit how to make these features available for people that just use NuGetGallery on its own.

We _do_ recommend our users to connect to nuget.org over the V3 source URL (https://api.nuget.org/v3/index.json) instead of the V2 source URL (https://www.nuget.org/api/v2) since the availability of V3 is better and should be faster too.

I hope this clears things up. Let me know if you have more questions.

**Comment by scottbommarito** [comment]
@satano - Also, regarding hosting a NuGet server, if you don't need the full feature set of NuGetGallery, you could also consider running a more lightweight implementation. They are easier to set up and maintain, but have a lot less functionality--however, you likely won't need this functionality unless you're working with a large team.

[NuGet.Server (V2 implementation)](https://github.com/NuGet/NuGet.Server)
[BaGet (V3 implementation)](https://github.com/loic-sharma/BaGet)

**Comment by satano** [comment]
Thank you guys a lot. 👍
