### ISSUE TITLE
Symbol packages are incorrect

### ISSUE THREAD

**Issue by jozefizso** [NuGet/NuGetGallery#7321]
NuGet will hapilly pack PDB files into the new SNUPKG files. Project was compiled with VS 2017 v15.9.13 and there were no errors or warnings creating the nuget packages and symbols.

Yet, NuGet Gallery cannot process symbols because of the "The uploaded symbols package contains one or more pdbs that are not portable" error.

As those files were successfuly created by nuget, I expect the Gallery can use them.

Otherwise, NuGet 5.0.2 contains a bug which prevents it from creating correct symbol files as it does not warning the user in any way that such packages will be useles.

PS: This whole new experience arround symbol packages is just terrible. I don't understand why did you shut down the previous symbols package server and we cannot use existing symbols for our packages.

PS1: Process for new symbol packages is terribly documented. Parameters to create the new SNUPKG files are not documented at all.

**Comment by skofman1** [comment]
@jozefizso , thanks for the feedback!

> Otherwise, NuGet 5.0.2 contains a bug which prevents it from creating correct symbol files as it does not warning the user in any way that such packages will be useles.

This is by design. `nuget.exe` will pack any pdb format you will throw at it, since it doesn't know the server you will be uploading those to and the capabilities of that server. At present, nuget.org accepts only portable pdbs, but this might change in the future. Other nuget server implementations (like AzureDevOps, MyGet, GitHub) might chose to accept all pdb types. 

>  I don't understand why did you shut down the previous symbols package server and we cannot use existing symbols for our packages.

The previous symbols server (`https://nuget.smbsrc.net`) is still up and running. You can find documentation [here](https://docs.microsoft.com/en-gb/nuget/create-packages/symbol-packages). 

> Process for new symbol packages is terribly documented. Parameters to create the new SNUPKG files are not documented at all.

Are you referring to the documentation [here](https://docs.microsoft.com/en-gb/nuget/create-packages/symbol-packages-snupkg)? We are in the process of improving our docs and would love to hear specific feedback on what can be improved.
