### ISSUE TITLE
PFX Certificates not accepted

### ISSUE THREAD

**Issue by MSBassSinger** [NuGet/NuGetGallery#7342]
### Describe the bug
I have a DigiCert signing certificate, which is a PFX.  I exported it to a .cer so I would have both.  When I build a package in Visual Studio 2019, I must provide a PFX file to sign it.  That works fine.  However, I can only upload a .cer to NuGet as my certificate.  NuGet does not match the PFX-signed package to the .cer file.  

### Expected behavior
I would expect NuGet to accept my .cer or my .pfx certificates.

**Comment by joelverhagen** [comment]
The certificate that you upload to nuget.org must be the public key certificate. The Account Settings page on nuget.org (https://www.nuget.org/account) expects a DER-encoded binary X.509 certificate. This usually has a ".cer" file extension. Note that there is an alternate encoding for public keys which is base-64 instead of binary. This won't work even though the file extension is sometimes also ".cer". You can use `mmc.exe` with the Certificates snap-in in Windows to export the DER-encoded public key certificate from a certificate installed on your machine.

If you have a .cer file that is not working, you can open it in Notepad and look at the first several characters. If it looks like this:

```
-----BEGIN CERTIFICATE-----
```

... then it is base-64 encoded and needs to be converted to DER encoding. Please do not post the content of any certificates on this GitHub issue. I want to ensure your secrets stay secret 👍.

You can convert a base-64 .cer file by double-clicking it .cer in Windows, installing it to your certificate store, then exporting it again in the DER format. The screen during export where you choose "DER" looks something like this:

![image](https://user-images.githubusercontent.com/94054/61383848-4fc4bc00-a864-11e9-935a-ff3fb798c601.png)

As a side note, a PFX typically contains both the public certificate and the private key which is more than what nuget.org needs. The PFX file should be kept secret and should only used for by you. For example, you would use it on your computer to execute the `nuget.exe sign` command when it is installed to your Windows certificate storage but must never upload it to nuget.org.

**Comment by joelverhagen** [comment]
If you have further questions about your particular certificates or are still blocked, please reach out to support@nuget.org and we'll work with you to understand the problem more deeply in a less public context.

**Comment by joelverhagen** [comment]
Please feel free to re-open if you have more questions.

**Comment by MSBassSinger** [comment]
Thank you. I did send a question late yesterday on command line format for this issue, but have not yet received a response.
The response to my question would really help.
Thanks,
Jeff Jones
    	
    	

    	Jeff JonesMSBassSinger@comcast.netAlpharetta, GA
    
  




On Tue, Jul 23, 2019 at 11:50 AM -0400, "Joel Verhagen" <notifications@github.com> wrote:












Please feel free to re-open if you have more questions.
