### ISSUE TITLE
TempData messages are no longer working

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#7461]
For example, as an admin, when you reflow a package you don't see the grey bar message on the subsequent page that tells you the reflow is starting.

This is a regression and likely affects customer scenarios.

**Comment by scottbommarito** [comment]
Explanation of the issue, for posterity:

This was caused by @joelverhagen re-registering a controller in DI. Controllers are usually wired up into DI by MVC automatically, but he wanted to modify the wiring so he replaced the default registration. This controller was then, for an unknown reason, repeatedly given the same instance of a `CookieTempDataProvider`. Because it was never reconstructed for each request, this `CookieTempDataProvider` was never given the current requests' `HttpContext`, so any attempts to access `TempData` failed.
