### ISSUE TITLE
Duplicates when paging through search results since new search went live

### ISSUE THREAD

**Issue by Jericho** [NuGet/NuGetGallery#7494]
### Describe the bug
I have a console application that uses the NuGet.Protocol.Core.v3 version 4.3.0-beta1-2418 nuget package to search nuget for packages with a certain keyword. My app retrieves 10 results at a time and loops through pages until no result are returned. This has always worked very well until a few days ago. What I am seeing since the new search went live is that intermittently a package will be included on a certain page and again on the following page.

### To Reproduce
Here is an excerpt of my C# code that can be copied and pasted into a console app to reproduce the behavior:
```
var take = 10;
var skip = 0;
var searchTerm = "Cake";
var filters = new SearchFilter(true)
{
    IncludeDelisted = false
};
var discoveredPackages = new List<IPackageSearchMetadata>(take);
var nugetSearchClient = nugetRepository.GetResource<PackageSearchResource>();

while (true)
{
    var searchResult = await nugetSearchClient.SearchAsync(searchTerm, filters, skip, take, NullLogger.Instance, CancellationToken.None).ConfigureAwait(false);
    skip += take;

    if (!searchResult.Any()) break;

    // I added the following code to help me investigate this problem
    // An exception will be thrown if a package is returned in the search
    // result and has been discovered previously
    var duplicates = searchResult.Select(r => r.Identity).Intersect(discoveredPackages.Select(p => p.Identity));
    if (duplicates.Any())
    {
        var dupes = string.Join(", ", duplicates.Select(i => i.ToString()));
        throw new Exception($"The following package were already returned by the search API: {dupes}");
    }

    discoveredPackages.AddRange(searchResult);
}
```

### Expected behavior
I expect packages to be returned only once and not to be duplicated on multiple pages of the search result.

### Side note
Is there a way when I search programatically to specified my desired sorting and completely avoid the new "relevance" sorting? For example, in my case a simple alphabetical sort would be perfectly fine.

**Comment by joelverhagen** [comment]
Thanks for the additional details. I'll take it I'll look into what's going on. just to be sure can you provide how you initialize the NugetRepository property?

**Comment by Jericho** [comment]
```
var providers = new List<Lazy<INuGetResourceProvider>>();
providers.AddRange(NuGet.Protocol.Core.Types.Repository.Provider.GetCoreV3());  // Add v3 API support
var packageSource = new PackageSource("https://api.nuget.org/v3/index.json");
var nugetRepository = new SourceRepository(packageSource, providers);
```

**Comment by joelverhagen** [comment]
> Is there a way when I search programatically to specified my desired sorting and completely avoid the new "relevance" sorting? For example, in my case a simple alphabetical sort would be perfectly fine.

The V3 search endpoint only supports ordering by relevance. Ideally this order is quite stable over time and only changes when a new package is introduced or if download counts change dramatically. 

In general, sorting of search results in arbitrary was is tracked here: https://github.com/NuGet/NuGetGallery/issues/2636. Please provide your motivation for arbitrary sorting there and that will help us prioritize and understand customer expectations.

> I expect packages to be returned only once and not to be duplicated on multiple pages of the search result.

I have reproduced the issue and have filed a ticket with the Azure Search team. I have determined that both the relative order and the "score" vary from query to query. Additionally, the download count and document metadata is constant from query to query.

**Comment by Jericho** [comment]
@joelverhagen I continue to investigate and have two new observations:

1. when a duplicate package is returned it takes the place of another package which means that some packages are missing from the result
2. increasing the number of records per page seems to have the side effect of reducing the number of duplicates.

**Comment by joelverhagen** [comment]
> when a duplicate package is returned it takes the place of another package which means that some packages are missing from the result

Yes, when order is unstable while paging, this is two sides of the same coin. Duplicate packages _and_ missing packages. Thanks for the confirmation on your end.

> increasing the number of records per page seems to have the side effect of reducing the number of duplicates.

Yeah, this is a reasonable mitigation especially considering your scenario. Our maximum "take" value is 1,000 which should give you quite a bit of runway.

**Comment by Jericho** [comment]
> Our maximum "take" value is 1,000 which should give you quite a bit of runway.
My current query returns 480 packages so 1,000 is fine for now. This is the workaround I'm implementing right now.

**Comment by joelverhagen** [comment]
Hey @Jericho, I've gotten a response back from the Azure Search team. In short, this sort of behavior is expected.

Based on the way they shard documents out inside Azure Search, a document might get a slightly different score from query to query. The TF-IDF statistics are not exactly the same across all of the shards so depending on which shard a query goes to that document might be considered slightly more or less relevant for a given query. This same "jitter" is happening to many documents and if a couple of the documents have close scores, they can come back in different orders.

We have brainstormed some mitigations on our side:

- Add a cache between our service and Azure Search so that subsequent skip/take requests for the same search query would likely come from a cached result of say, the top 1000 documents.
- Fiddle with the scoring profile to make these similar document scores spread out more
- Change the scale configuration we have. Perhaps if we have a different balance of replicas or partitions this behavior will be less?
- Over-fetch a bunch of results and page through the results in the client.
  - This is essentially the approach you took. You increased the "take" value so that you would not observe more than one relative order.

These are all rather expensive approaches and each has their own drawbacks so we will hold off on making any changes for now. As we become more comfortable with our service and learn about other pain points we'll consider the priority of this issue.

Again, in the short term the approach you took seems perfect. When the time comes that you need to fetch more than 1,000, please feel free to get back to us and we'll talk about more approaches.

Thanks again for calling this out. I've learned a lot in the process of the investigation and this information will help us in the future.

**Comment by Jericho** [comment]
Thanks for the explanation. Specifying `1000` as the number of records per page works perfectly fine in my scenario so I was able to put this issue behind me.

I fully understand that from Azure Search's perspective this is the expected behavior but from my perspective as a developer consuming data from nuget's API, this is most certainly not expected. I don't think it's reasonable to expect duplicate packages and/or missing packages from the nuget API so I would encourage you to raise the priority of this issue and not wait until someone needs more than 1,000 documents to think about addressing it.

In addition to the ideas you have already brainstormed, I would like to propose that you allow developers to specify their desired sorting and therefore completely bypass Azure Search "relevance". I believe this would resolve this issue even in scenarios where more than 1,000 documents match the search criteria. This idea, as you previously pointed out to me, was proposed 4 years ago in #2636.

**Comment by MangelMaxime** [comment]
I am still seeing this problem today.

The scope of my search is for around 350 packages. I am making request with 50 elements per page in order to show a progress bar to the user.

However, doing so results in duplicated packages.

If I search for 1000 packages at once then the problem doesn't occur.

For now, I am going to go with 1000 packages pages however this will not be working once we reach that point.
