### ISSUE TITLE
The gallery search ordering is broken when searching for an existing package name

### ISSUE THREAD

**Issue by assyadh** [NuGet/NuGetGallery#7518]
### Describe the bug
When searching for [Amazon.AspNetCore.Identity.Cognito](https://www.nuget.org/packages?page=3&q=Amazon.AspNetCore.Identity.Cognito), it only shows up on the 3rd page.

### To Reproduce
1. Navigate to https://www.nuget.org/
2. Search for Amazon.AspNetCore.Identity.Cognito
3. Click next page twice, to see the package in the 3rd page

### Expected behavior
When supplying a valid package name, the search should put this package in top position.

### Screenshots
n/a

### Additional context
n/a

**Comment by loic-sharma** [comment]
Hello! Thank you for opening this bug. We're considering several fixes for this issue:

1. Add a special UI that displays a search's exact match at the top. This is tracked by: https://github.com/NuGet/NuGetGallery/issues/7463
2. Tweaking the scoring algorithm to give more relevant results. We have a few improvements in the pipeline that should help your specific query: https://github.com/nuget/nugetgallery/issues/7381 and https://github.com/nuget/nugetgallery/issues/7391

I'll go ahead and close this issue off since it should be covered by the other issues I've linked. Please let us know if you have any feedback!

**Comment by joelverhagen** [comment]
Hey @assyadh, this should be mitigated on nuget.org. For more details, see https://github.com/NuGet/NuGetGallery/issues/7463#issuecomment-531898791.
