### ISSUE TITLE
Support packageTypes property in catalog

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#7574]
### Describe the bug
The [`packageTypes` nuspec property](https://docs.microsoft.com/en-us/nuget/reference/nuspec#packagetypes) is used to distinguish between regular dependency packages, .NET CLI tools, and .NET CLI templates. Today, this property is always `""` on catalog leafs.

### To Reproduce

See the `packageTypes` property on the following catalog leafs:

* .NET CLI tool: https://api.nuget.org/v3/catalog0/data/2018.10.17.01.01.10/dotnet-xunit.2.4.0-beta.1.build3958.json
* .NET CLI template: https://api.nuget.org/v3/catalog0/data/2018.11.30.06.14.50/giraffe-template.0.1.0-alpha007.json

### Expected behavior
The catalog leaf should be a JSON array of all the package type names in the nuspec. For example:

```
"packageTypes": [
    "DotnetCliTool"
]
```

### Additional context
This is necessary to properly support package type filtering (see https://github.com/NuGet/NuGetGallery/issues/5762). Today, the job mutating the search index must guess the package type from the catalog leafs' `packageEntries` property. This approach isn't ideal as the search index must be rebuilt when a new package type is introduced.

**Comment by joelverhagen** [comment]
Agreed that current behavior is useless. Same story exists for `<repository>` (/cc @donnie-msft for https://github.com/NuGet/Home/issues/8584) or any other type that is a complex element (not just a single text node). Attributes are also ignored!

When we implement search by package type (coming relatively soon IIRC...) we will need this as you mentioned. It's funny because @ryuyu did all of this work ages ago but we never merged it 😢. I forget the blocker. https://github.com/NuGet/NuGet.Services.Metadata/pull/87

> Today, the job mutating the search index must guess the package type from the catalog leafs' packageEntries property. This approach isn't ideal as the search index must be rebuilt when a new package type is introduced.

What job are you referring to?

> The catalog leaf should be a JSON array of all the package type names in the nuspec. 

Concerning the shape, an array of strings is not sufficient. The package type model includes a version which would need to be included as well.

.nuspec XSD: https://github.com/NuGet/NuGet.Client/blob/502505da868f79b1c4fc1704dae6642138adb30c/src/NuGet.Core/NuGet.Packaging/compiler/resources/nuspec.xsd#L100-L104

Package Type specification: https://github.com/NuGet/Home/wiki/Package-Type-%5BPacking%5D

We need to choose whether to explicitly state the default version in the response JSON. My vote is **no**. Catalog leaves should match the intent of the package author. Explicitly stating `version="0.0"` vs. leaving out the `version` is equivalent to consumers but I think matching the author intent is safest. People reading the .nuspec need to already know the default so forcing this on catalog readers seems fine. So something like:

```json
{
  "packageTypes": [
    { "name": "DotnetCliTool" },
    { "name": "CustomType", "version": "2.0" },
  ]
}

**Comment by loic-sharma** [comment]
> > Today, the job mutating the search index must guess the package type from the catalog leafs' packageEntries property. This approach isn't ideal as the search index must be rebuilt when a new package type is introduced.
> 
> What job are you referring to?

I imagine this would be `catalog2azuresearch`.

> > The catalog leaf should be a JSON array of all the package type names in the nuspec.
> 
> Concerning the shape, an array of strings is not sufficient. The package type model includes a version which would need to be included as well.
> 
> .nuspec XSD: https://github.com/NuGet/NuGet.Client/blob/502505da868f79b1c4fc1704dae6642138adb30c/src/NuGet.Core/NuGet.Packaging/compiler/resources/nuspec.xsd#L100-L104
> 
> Package Type specification: https://github.com/NuGet/Home/wiki/Package-Type-%5BPacking%5D

Good point 👍 

> We need to choose whether to explicitly state the default version in the response JSON. My vote is **no**. Catalog leaves should match the intent of the package author. Explicitly stating `version="0.0"` vs. leaving out the `version` is equivalent to consumers but I think matching the author intent is safest. People reading the .nuspec need to already know the default so forcing this on catalog readers seems fine. So something like:
> 
> ```json
> {
>   "packageTypes": [
>     { "name": "DotnetCliTool" },
>     { "name": "CustomType", "version": "2.0" },
>   ]
> }
> ```

Looks great!

> When we implement search by package type (coming relatively soon IIRC...) we will need this as you mentioned. It's funny because @ryuyu did all of this work ages ago but we never merged it 😢. I forget the blocker. [NuGet/NuGet.Services.Metadata#87](https://github.com/NuGet/NuGet.Services.Metadata/pull/87)

Ah interesting! Maybe we can reuse this when we do this work for Azure Search too.
