### ISSUE TITLE
Packages with high download counts overwhelm packages that match all terms

### ISSUE THREAD

**Issue by KarthickR5** [NuGet/NuGetGallery#7620]
Hi,
 When i search using this keyword **asp.net core datagrid** this means patform name(**asp.net core**) and control name(**Datagrid**).

How this package **Microsoft.AspNetCore.Http** shows in top. this package does not contains search keyword in package name and tags. also download count was lesser than second package.

![Sample Screenshot](https://user-images.githubusercontent.com/56252418/66626422-cf6ce780-ec15-11e9-93e6-f76b0f5eacaa.png)

Can you please explain, in which basis this package(Microsoft.AspNetCore.Http) shows in top? and how this keyword match with that package?

**Comment by joelverhagen** [comment]
My guess is that Microsoft.AspNetCore.Http shows above the second result because there are fewer total tokens in that package ID meaning it's more relevant in total (see TF/IDF, one of the underlying concepts of Azure Search/Lucene).

Both documents have many, many downloads (are very popular) and have the "asp" "net" and "core" tokens. True, they do not have the "datagrid" token but in this case our currently algorithm makes the massive download count outweigh the fact that all terms are matched.

**Comment by joelverhagen** [comment]
Since this question, we have made all non-field scoped query terms required. This means the problem is less severe. The search query provided looks a lot more useful:
https://www.nuget.org/packages?q=asp.net+core+datagrid

Please feel free to open a new issue if you're still having a problem!
