### ISSUE TITLE
I Can't delete a new create package

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/NuGetGallery#7748]
@LuGuangguang commented on [Tue Nov 26 2019](https://github.com/NuGet/Home/issues/8859)

I learn to how to create a package.When I had public a package,I want to delete this. But I can't by the URL "https://docs.microsoft.com/zh-cn/nuget/quickstart/create-and-publish-a-package-using-visual-studio-net-framework".This is no the delete button.
 
this doc
![PHZE(IIAT (%RF51${(RNDR](https://user-images.githubusercontent.com/34500722/69702479-47da2a00-112a-11ea-916c-46b7e5464878.jpg)

this my project
![L9%FP{ AT56MX)A80PD@3EV](https://user-images.githubusercontent.com/34500722/69702619-98ea1e00-112a-11ea-910e-246141aae206.png)

Thank you!

**Comment by yishaigalatzer** [comment]
This is intentional, you need to file a support ticket. There are a few reasons for this, but the most famous one can be found in this article:  https://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/

**Comment by skofman1** [comment]
@LuGuangguang , as @yishaigalatzer explained, nuget.org doesn't allow deleting packages. However, we allow "unlisting" a package, which hides it from search results (but you can still see it in your list of packages).
If it's critical for you to delete a package completely (for example because it contains private code), please contact support https://www.nuget.org/policies/Contact
