### ISSUE TITLE
Is there a way to modify the licenseInfo link after a nuget package is published

### ISSUE THREAD

**Issue by ramsubbaraoc** [NuGet/NuGetGallery#7775]
Is there a way to modify the licenseInfo link after the nuget package is published?

I had an invalid URL in the licenseInfo link. Now i want to modify it. I had sent a mail to nuget.org support but haven't received any response from them yet. Is there a way i can do it myself.

Thanks

**Comment by joelverhagen** [comment]
Hey @ramsubbaraoc, by design packages on nuget.org are immutable. The only way to modify the license URL is to publish a new version. Consider unlisting the old version that has the problematic license URL.

If you haven't heard about it yet, consider packing the license information into the package instead of using an external license URL. This will help your consumers be more confident that the license information will be available forever and that it won't change over time:
https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-a-license-expression-or-a-license-file
