### ISSUE TITLE
Improved link functionality for nuget.org

### ISSUE THREAD

**Issue by taori** [NuGet/NuGetGallery#7835]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
Nuget.org page

It would be great if there were a page link for nuget.org to access the latest version of a packet matching a given version suffix name.

e.g nuget.org/packages/mypage/latest/alpha or nuget.org/packages/mypage/latest

**Comment by joelverhagen** [comment]
Hey @taori, I moved this issue to NuGet/NuGetGallery which is the repository we use for nuget.org specific issues.

Regarding this request, we have a very basic version of this behavior already:

- Latest stable: package details URL without any version
  - Example: [/packages/Serilog](https://www.nuget.org/packages/Serilog) links to 2.9.0 even though 2.9.1-dev-01154 is the latest.
- Latest including prerelease: package details URL with `/absoluteLatest` at the end
  - Example [/packages/Serilog/absoluteLatest](https://www.nuget.org/packages/Serilog/absoluteLatest) points to 2.9.1-dev-01154

How would you expect `latest/alpha` to work on a set of versions like this?
- 1.0.0-alpha
- 1.0.0-alpha.1
- 1.0.0-alpha.2
- 1.0.0-beta

Would `1.0.0-alpha` be picked since it matches exactly? Would `1.0.0-alpha.2` be picked since it's the highest version starting with an `alpha` prerelease? Or would `1.0.0-beta` be picked since it's a version higher than `alpha`, i.e. "the latest after alpha"?

Another option in the short term would be to use one of our APIs and write script to calculate the answer. For example, you could look up the current listed versions for an ID using the [search API](https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource) or the [package metadata API](https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource). You could use the `NuGetVersion` type from [NuGet.Versioning](https://www.nuget.org/packages/NuGet.Versioning) package to parse the versions and [NuGet.Protocol](https://www.nuget.org/packages/NuGet.Protocol) to interact with the APIs.

**Comment by taori** [comment]
ohhh great. i was unaware of /absoluteLatest (i only  instinctively tried /latest). Thanks for that!

Without knowing the api itself i would semantically expect a latest feature work like the following:
- `/latest` returns the absolute latest package by upload time (since no suffix path already returns the latest non prerelease, otherwise that should have the latest slot)
- `/latest/prerelease` would be a reserved suffix keyword returning the latest upload of a package with prelease (so either x.x.x-beta300.nupkg, x.x.x-alpha300.nupkg or x.x.x-beta.nupkg)
- `/latest/prerelease/beta` would return the latest prelease (so either x.x.x-beta300.nupkg or x.x.x-beta.nupkg or x.x.x-beta-internal.nupkg or x.x.x-beta.internal.nupkg)
- `/latest/prerelease/beta.internal` would return the latest (so either x.x.x-beta.internal300.nupkg or x.x.x-beta.internal.nupkg)

That way badges with references to nuget can link to multiple different channels instead of just linking to the latest prerelease version (which solves my problem. but more granularity would make everyone happy i suppose :))




> Would `1.0.0-alpha` be picked since it matches exactly? Would `1.0.0-alpha.2` be picked since it's the highest version starting with an `alpha` prerelease? Or would `1.0.0-beta` be picked since it's a version higher than `alpha`, i.e. "the latest after alpha"?

if prerelease subfilters were to be implemented the way i suggested i suppose that would be rendered irrelevant, since the phrases of a prerelease are usually the same and the numbers are mostly ordered the same as their build number. 

With additional prerelease word filters you would be directed to the channel quality of your choice (if alpha/beta is used in a semantically useful way)

**Comment by skofman1** [comment]
@taori , if you would like to contribute to nuget.org and implement your suggestions, we will support you by reviewing your PR and shipping the change. 🚢

**Comment by taori** [comment]
okay. rather busy these days but i'll consider it, since it would be rather neat. thanks

**Comment by joelverhagen** [comment]
This change is deployed to nuget.org.
