### ISSUE TITLE
On nuget.org the versions of Microsoft.ChakraCore are incorrect when read from the APIs

### ISSUE THREAD

**Issue by bbossola** [NuGet/NuGetGallery#7863]
On nuget.org, the versions reported by the API differs from the versions reported by the web interface for Microsoft.ChakraCore

### To Reproduce
Using a browser, visit https://www.nuget.org/packages/Microsoft.ChakraCore/
You can see the latest version is 1.11.16 (confirmed)

Using curl, access the information about the library:
https://api.nuget.org/v3/registration3/microsoft.chakracore/index.json
You can see the latest version is 1.11.15

### Expected behavior
The versions reported from the web interface and the versions reported from the API are consistent.

### Screenshots
**WEB:**  
![image](https://user-images.githubusercontent.com/186370/76203510-ac5b5980-61ee-11ea-8f31-46a98e23c270.png)

**API:**  
![image](https://user-images.githubusercontent.com/186370/76203565-c72dce00-61ee-11ea-966a-571b9fc6272e.png)

**Comment by joelverhagen** [comment]
The issue here is that you are using an outdated package metadata base URL. 

The URL "https://api.nuget.org/v3/registration3/" was replaced in the service index several months ago. The NuGet.org service index is the authoritative source for these URLs. Read more about it here:
https://docs.microsoft.com/en-us/nuget/api/overview#service-index

The corresponding new URL is:
https://api.nuget.org/v3/registration4/

However I would recommend all new readers to use the base URL that also includes SemVer 2.0.0 packages:
https://api.nuget.org/v3/registration4-gz-semver2/

You can read more about the different base URLs here:
https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource

Also if you're reading these APIs from a .NET app you can consider using the client APIs:
https://docs.microsoft.com/en-us/nuget/reference/nuget-client-sdk

**Comment by bbossola** [comment]
You are absolutely right, thanks for the very complete information.
