### ISSUE TITLE
Latest version is not present using the NuGet API

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/NuGetGallery#7866]
@darmalovan commented on [Thu Mar 12 2020](https://github.com/NuGet/Home/issues/9291)

## Details about Problem
 I'm seeing a discrepancy in getting the latest version of a package between the NuGet website and the NuGet API.

## Detailed repro steps so we can see the same problem

1. Going to the NuGet web site for the `EntityFrameworkCore.Relational` package https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Relational/
the latest version is `3.1.2`. 

2. Using the API https://api.nuget.org/v3/registration3/microsoft.entityframeworkcore.relational/index.json I am getting `3.1.1` as the latest version.

I tried also to use the api.nuget.org/v3/registration3-gz-semver2 endpoint without any luck.

The search web site says `3.1.2` is the latest version:
![image](https://user-images.githubusercontent.com/5316748/76555697-d50a7a00-64a0-11ea-8c79-01e7b5c367dc.png)

Would love for any advice here :)

---

@donnie-msft commented on [Thu Mar 12 2020](https://github.com/NuGet/Home/issues/9291#issuecomment-598385470)

Hi! I'm sending this over to the Server team to take a look.

**Comment by joelverhagen** [comment]
The issue here is that you are using an outdated package metadata base URL. 

The URL "https://api.nuget.org/v3/registration3/" was replaced in the service index several months ago. The NuGet.org service index is the authoritative source for these URLs. Read more about it here:
https://docs.microsoft.com/en-us/nuget/api/overview#service-index

The corresponding new URL is:
https://api.nuget.org/v3/registration4/

However I would recommend all new readers to use the base URL that also includes SemVer 2.0.0 packages:
https://api.nuget.org/v3/registration4-gz-semver2/

You can read more about the different base URLs here:
https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource

Also if you're reading these APIs from a .NET app you can consider using the client APIs:
https://docs.microsoft.com/en-us/nuget/reference/nuget-client-sdk

**Comment by darmalovan** [comment]
Thanks for the response, makes sense!
 is the `/registration4-gz-semver2/` documented? I could only find /registration3-* endpoints.

**Comment by joelverhagen** [comment]
The package metadata base URL (the registrion4/registration3 thing) should _always_ be discovered via the service index. Per NuGet protocol, we are free to change the URL from time to time as long as the new one appears in the service index with an expected `@type` value (`RegistrationsBaseUrl/3.6.0` in this case).

I agree that the samples having registration3 are confusing.

**Comment by bkaid** [comment]
I'm also seeing this issue with other packages.  For example, I use dependabot to keep dependencies up to date automatically.  One it's not able to update is MassTransit.RabbitMq.

Dependabot logs:
```
updater | INFO <job_26331871> Checking if MassTransit.RabbitMQ 6.2.0 needs updating
  proxy | 2020/03/15 04:13:11 GET https://api-v2v3search-0.nuget.org:443/query?q=masstransit.rabbitmq&prerelease=true
  proxy | 2020/03/15 04:13:11 200 https://api-v2v3search-0.nuget.org:443/query?q=masstransit.rabbitmq&prerelease=true
updater | INFO <job_26331871> Latest version is 5.2.1
updater | INFO <job_26331871> No update needed for MassTransit.RabbitMQ 6.2.0
```

https://www.nuget.org/packages/MassTransit.RabbitMQ/  shows latest is 6.2.2.  5.2.1 is over a year old. Even using the equivalent discovered API endpoint https://azuresearch-usnc.nuget.org/query?q=masstransit.rabbitmq gives the same outdated result of 5.2.1.
