### ISSUE TITLE
[Usabilla] Search feedback

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#7913]
Search query: https://www.nuget.org/packages?q=boost_python36-vc142 
Comment:   Results that do not contain the keywords I'm searching for

**Comment by loic-sharma** [comment]
Using spaces instead of underscores and dashes yields better results: https://www.nuget.org/packages?q=boost+python+vc142

The "banana split" improvement doesn't help here because the desired results don't match all the tokens `boost`, `python`, `36`, `vc`, and `142`. We should compare the tokens generated by the Azure Search analyzer for the `boost_python36-vc142` and `boost python36 vc142` queries.

**Comment by joelverhagen** [comment]
This is fixed with the camel-split enhancement (https://github.com/NuGet/NuGet.Jobs/pull/925).

**Comment by joelverhagen** [comment]
Well
