### ISSUE TITLE
ASP.net C# pg 11.6 and npgsql 4.0.10

### ISSUE THREAD

**Issue by shan03** [NuGet/NuGetGallery#7924]
ASP.net C#(.net 4.5) pg 11.6(AWS) and npgsql 4.0.10 is not working. when i try to connect my pg db through ado.net im getting {"The operation has timed out."} this error suggest me ASAP.

**Comment by loic-sharma** [comment]
Hello, thanks for creating this issue. These GitHub issues are to track problems with the nuget.org website, we do not support individual NuGet packages. You can try contacting package owners directly using the "Contact Owners" link on the package details page, or, you can ask your question on https://stackoverflow.com. Be sure to add the tag `nuget` so that your question can be found and answered.
