### ISSUE TITLE
Unable to add Nuget.org in visual studio 2019 for mac

### ISSUE THREAD

**Issue by mahaveerprasadpichaimani** [NuGet/NuGetGallery#7952]
Hi Team,

I am trying to add Nuget packages for ios application development but unable to add any nuget packages from Nuget.org due to the below error message. I have attached the screen shots here for your reference.

Could you please check and let me know the issue here?

ios version: macOS Mojave 10.14.6
Visual studio version: visual studio community (preview) for mac
Nuget Version: 5.0.2.5988

![Nuget Org_Issue](https://user-images.githubusercontent.com/63851947/79563443-1d731400-80ad-11ea-8ef0-03b3f2c122e3.JPG)
![PackageConsoleErrorMessage](https://user-images.githubusercontent.com/63851947/79563447-1f3cd780-80ad-11ea-94d3-fe527182ef79.JPG)
![CompileErrorMessage](https://user-images.githubusercontent.com/63851947/79563449-1fd56e00-80ad-11ea-8ff8-cdbdf5cadaaf.JPG)
![NugetVersion](https://user-images.githubusercontent.com/63851947/79563451-1fd56e00-80ad-11ea-8f4f-51eef22cc0fc.JPG)

**Comment by mahaveerprasadpichaimani** [comment]
Thanks Joel and nkolev. I have sent the attached results based on joel's input to support@nuget.org.

Could you please check and let me know the solution for the same. Thanks in advance.

**Comment by joelverhagen** [comment]
I've responded to your email. In short, it looks like a connectivity issue specific to Visual Studio for Mac because the ping and trace route results indicate a successful connection. As @nkolev92 mentioned, I'd recommend reaching out to Visual Studio for Mac:
https://docs.microsoft.com/en-us/visualstudio/mac/report-a-problem?view=vsmac-2019
