### ISSUE TITLE
Installing EntityFramework to asp.net core

### ISSUE THREAD

**Issue by ThatoLesetla** [NuGet/NuGetGallery#8025]
Hi All,

I'm currently struggling to install Microsoft.EntityFrameworkCore to my project. When I run dotnet restore. The is a list of packages that aren't found

**This is my .csproj**
`<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.3"/>
  </ItemGroup>
</Project>`
**This is what I get when I run dotnet restore**
PS C:\Users\DELL\Desktop\New_folder\backend> dotnet restore
  Determining projects to restore...
C:\Users\DELL\Desktop\New_folder\backend\backend.csproj : error NU1101: Unable to find package Microsoft.EntityFrameworkCore.Abstractions. No packages exist with this id in source(s): LocalSource, Microsoft Visual Studio Offline Packages
C:\Users\DELL\Desktop\New_folder\backend\backend.csproj : error NU1101: Unable to find package Microsoft.EntityFrameworkCore.Analyzers. No packages exist with this id in source(s): LocalSource, Microsoft Visual Studio Offline Packages
C:\Users\DELL\Desktop\New_folder\backend\backend.csproj : error NU1101: Unable to find package Microsoft.Bcl.AsyncInterfaces. No packages exist with this id in source(s): LocalSource, Microsoft Visual Studio Offline Packages
C:\Users\DELL\Desktop\New_folder\backend\backend.csproj : error NU1101: Unable to find package Microsoft.Bcl.HashCode. No packages exist with this id in source(s): LocalSource, Microsoft Visual Studio Offline Packages
C:\Users\DELL\Desktop\New_folder\backend\backend.csproj : error NU1101: Unable to find package Microsoft.Extensions.Caching.Memory. No packages exist with this id in source(s): LocalSource, Microsoft Visual Studio Offline Packages
C:\Users\DELL\Desktop\New_folder\backend\backend.csproj : error NU1101: Unable to find package Microsoft.Extensions.DependencyInjection. No packages exist with this id in source(s): LocalSource, Microsoft Visual Studio Offline Packages
C:\Users\DELL\Desktop\New_folder\backend\backend.csproj : error NU1101: Unable to find package Microsoft.Extensions.Logging. No packages exist with this id in source(s): LocalSource, Microsoft Visual Studio Offline Packages
C:\Users\DELL\Desktop\New_folder\backend\backend.csproj : error NU1102: Unable to find package System.Collections.Immutable with version (>= 1.7.0)
C:\Users\DELL\Desktop\New_folder\backend\backend.csproj : error NU1102:   - Found 2 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 1.2.0 ]
C:\Users\DELL\Desktop\New_folder\backend\backend.csproj : error NU1102:   - Found 0 version(s) in LocalSource
C:\Users\DELL\Desktop\New_folder\backend\backend.csproj : error NU1102: Unable to find package System.ComponentModel.Annotations with version (>= 4.7.0)
C:\Users\DELL\Desktop\New_folder\backend\backend.csproj : error NU1102:   - Found 2 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 4.1.0 ]
C:\Users\DELL\Desktop\New_folder\backend\backend.csproj : error NU1102:   - Found 0 version(s) in LocalSource
C:\Users\DELL\Desktop\New_folder\backend\backend.csproj : error NU1102: Unable to find package System.Diagnostics.DiagnosticSource with version (>= 4.7.0)
C:\Users\DELL\Desktop\New_folder\backend\backend.csproj : error NU1102:   - Found 1 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 4.0.0 ]

**Comment by loic-sharma** [comment]
Hello,

Unfortunately, we do not provide individual support for NuGet client but you can find several options to help resolve your issue below.

The official NuGet documentation covering both nuget.exe and Visual Studio is available at https://docs.microsoft.com/en-us/nuget/ 

Help on specific warning and error codes is available at https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings

If you are unable to find help in the docs you can ask your question on https://stackoverflow.com/  Be sure to add the tag: nuget so that it can be found and answered. 

StackOverflow should be used first for all questions, support requests, or if you are unclear on what the expected client behavior is.

Bugs can be filed for NuGet in Visual Studio using these instructions: https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-report-a-problem-with-visual-studio.md

Additional information on NuGet client bugs and known issues can be found here: https://github.com/nuget/home/issues

That said, it looks like you're missing the "nuget.org" package source. You can try the following options:

1. Create a [`nuget.config` file](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file) and explicitly list the NuGet package sources needed to build your project. Or, ...
2. Explicitly add the NuGet package source to the dotnet restore command: `dotnet resource --source https://api.nuget.org/v3/index.json`
