### ISSUE TITLE
Autocomplete APIs dont show .NET 5.0 prerelease packages

### ISSUE THREAD

**Issue by omajid** [NuGet/NuGetGallery#8094]
### Describe the bug
I am seeing inconsistent results via the web interface and the autocomplete API. Am I doing something wrong?

The web interface shows me pre-release versions of .NET 5 packages: https://www.nuget.org/packages/runtime.linux-x64.Microsoft.NETCore.DotNetAppHost/5.0.0-preview.6.20305.6

The autocomplete API doesn't. I tried:
- https://api-v2v3search-0.nuget.org/autocomplete?id=runtime.linux-x64.Microsoft.NETCore.DotNetAppHost&prerelease=true
- https://azuresearch-usnc.nuget.org/autocomplete?id=runtime.linux-x64.Microsoft.NETCore.DotNetAppHost&prerelease=true

Neither does the search API:

- https://azuresearch-usnc.nuget.org/query?q=runtime.linux-x64.Microsoft.NETCore.DotNetAppHost&prerelease=true

### To Reproduce
1. Point your browser to
- https://www.nuget.org/packages/runtime.linux-x64.Microsoft.NETCore.DotNetAppHost/5.0.0-preview.6.20305.6
- https://api-v2v3search-0.nuget.org/autocomplete?id=runtime.linux-x64.Microsoft.NETCore.DotNetAppHost&prerelease=true

### Expected behavior
The website and search API show consistent view of packages. Right now, the webiste shows the pre-release versions. I dont seem them via the nuget APIs

**Comment by loic-sharma** [comment]
Hello, thanks for reaching out! Just curious, could you explain your scenario a little more? Why are you interacting with the search APIs directly?

To answer your question, the version `5.0.0-preview.6.20305.6` uses [semantic versioning 2.0.0](https://semver.org/spec/v2.0.0.html) due to the periods in the prerelease label. Older NuGet clients do not support semver 2, so, by default we filter out semver results. For the search API, you will need to include the `semVerLevel=2.0.0` query string argument. For example: https://azuresearch-usnc.nuget.org/autocomplete?id=runtime.linux-x64.Microsoft.NETCore.DotNetAppHost&prerelease=true&semVerLevel=2.0.0

For more information, please refer to this documentation: https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource#request-parameters
