### ISSUE TITLE
Nuget installed 

### ISSUE THREAD

**Issue by srika1ki** [NuGet/NuGetGallery#8170]
Nuget is installed, just not for me... 😣

ugh, i know... so instead of trying to cunstruct an application (that's how i got into this mess) i'm receptive to asking for help. there's quite a few `F ups but right now i need to remotely access my laptop in order to fix. Please, be kind to my mess. It's mine and i own that mess. i need help cleaning up the mess i have made out of my life.

G

**Comment by srika1ki** [comment]
https://github.com/owner/project/issues/123

**Comment by loic-sharma** [comment]
Hi could you clarify the kind of help you need?

I'd recommend looking at NuGet's documentation: https://docs.nuget.org/

You can also try stackoverflow.com. Be sure to add the `nuget` tag so that your question can be found and answered.

If you found a NuGet bug in Visual Studio, please use these instructions to report it: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019#:~:text=In%20Visual%20Studio%2C%20select%20the,Send%20Feedback%20%3E%20Report%20a%20Problem.
