### ISSUE TITLE
Poor/unrelated search results when not using the exact package name

### ISSUE THREAD

**Issue by Sergio0694** [NuGet/NuGetGallery#8201]
### Describe the bug
Searching for the [`Microsoft.Toolkit.HighPerformance` package](https://www.nuget.org/packages/Microsoft.Toolkit.HighPerformance/) displays unrelated search results. This happens both on nuget.org and when searching through Visual Studio. It's almost impossible to find that package unless you actually know the exact name.

Not exactly the same, but possibly related to https://github.com/NuGet/NuGetGallery/issues/8130?

### To Reproduce
Here's some search results I tried:

⛔ "microsoft high performance" ([screen](https://user-images.githubusercontent.com/10199417/92381423-1eafe680-f10b-11ea-9c3d-6e11c3a8ce57.png)), the package is nowhere to be found
⛔ "microsoft highperformance" ([screen](https://user-images.githubusercontent.com/10199417/92381483-3a1af180-f10b-11ea-8c25-4a05e83bd5bb.png)), same as above
⛔ "Microsoft HighPerformance" ([screen](https://user-images.githubusercontent.com/10199417/92381513-4acb6780-f10b-11ea-9a3a-7192e410befe.png)), same
⛔ "microsoft toolkit high performance" ([screen](https://user-images.githubusercontent.com/10199417/92381544-5a4ab080-f10b-11ea-8a11-24d6600a4e38.png)), same
⛔ "microsoft toolkit highperformance" ([screen](https://user-images.githubusercontent.com/10199417/92381566-68003600-f10b-11ea-8a7d-f5ec4d5dc4bd.png)), same

✅ "microsoft.toolkit.highperformance" ([screen](https://user-images.githubusercontent.com/10199417/92381616-7e0df680-f10b-11ea-8e86-b99fc8fb4a61.png)), works
✅ "Microsoft.Toolkit.HighPerformance" ([screen](https://user-images.githubusercontent.com/10199417/92381692-9a119800-f10b-11ea-820b-113cde208b39.png)), works too

### Expected behavior
The `Microsoft.Toolkit.HighPerformance` should be the first result for all these various search queries.

### Screenshots
Attached a screen next to each tested query above.

### Additional context
In case it helps, right now we have the following tags in the package:

> UWP Toolkit Windows core standard unsafe span memory string array stream buffer extensions helpers parallel performance

Though I'd expect the search results to display that package as first result even just based on the package name, as all those sample queries are an exact match for the package name, once tokenized with the `.` and converted to lowercase.
I wouldn't expect users to search for the package by the exact name (which is also more verbose to type), especially if they just are not aware the package exists at all, so the way the search results are returned right now doesn't help with discoverability.

Thanks! 😊

**Comment by loic-sharma** [comment]
Thanks for opening this issue! Today, our search rankings heavily prefer packages with many total downloads. This works well for the majority of searches as folks often want heavily downloaded packages like Newtonsoft.Json. However, favoring packages with high total downloads puts new package like `Microsoft.Toolkit.HighPerformance` at a massive disadvantage, as the term [`microsoft`](https://www.nuget.org/packages?q=microsoft) includes other Microsoft packages with large amounts of downloads.

Furthermore, the term [`microsoft`](https://www.nuget.org/packages?q=microsoft) includes "noisy" results like [System.Numerics.Vectors](https://www.nuget.org/packages/System.Numerics.Vectors/). These "noisy" results aren't actually commonly installed by customers, instead, these are transitive dependencies of other popular packages.

We're considering a few improvements to the rankings algorithm that should help this case:

1. https://github.com/NuGet/NuGetGallery/issues/7406 - Use recent downloads instead of total downloads for rankings 
1. https://github.com/NuGet/NuGetGallery/issues/7186 - Prefer direct dependencies over transitive dependencies

**Comment by joelverhagen** [comment]
@Sergio0694, we've rolled out some improvements in this area. Could you try out your queries? from what I can tell:

`microsoft high performance` - rank 9
`microsoft highperformance` - rank 1
`Microsoft HighPerformance` - rank 7 
`microsoft toolkit high performance` - rank 1
`microsoft toolkit highperformance` - rank 1
`microsoft.toolkit.highperformance` - rank 1
`Microsoft.Toolkit.HighPerformance` - rank 1

Seems better to me, overall, but I was wondering what you think!

**Comment by Sergio0694** [comment]
Hi @joelverhagen - I just tried those queries and I got the same results you mentioned, this looks absolutely great!
Thank you so much for looking into this, this is definitely so much better than before! 😊
