### ISSUE TITLE
VSFeedback - The trust relationship could not be established for the SSL/TLS secure channel.

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/NuGetGallery#8237]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1204423/nuget无法联网.html)._

---
NuGet is not connected to the Internet.
The nuget.org index of the source https://api.nuget.org/v3/index.json could not be loaded.
  There was an error sending the request.
  The underlying connection is closed: The trust relationship could not be established for the SSL/TLS secure channel.
  According to the authentication process, the remote certificate is invalid.

---
#### Feedback Bot on 9/30/2020, 01:45 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by joelverhagen** [comment]
Hello, thanks for taking the time to report this. We've moved this issue to GitHub, which is where we track issues for nuget.org. 

First, could you tell me if you are still facing this problem? Currently, there are no know outages on nuget.org.

Second, as an initial guess, could you try some of the mitigations available on this blog post?
https://devblogs.microsoft.com/nuget/deprecating-tls-1-0-and-1-1-on-nuget-org/
Several of our users have run into TLS issues when connecting to nuget.org because we have disabled TLS 1.0 and 1.1. Let's eliminate that possibility first.

Thanks.

**Comment by joelverhagen** [comment]
Please feel free to contact support@nuget.org if you run into further problems regarding connecting to nuget.org.
