### ISSUE TITLE
Package icons show up in search results at certain browser window widths in narrow layouts

### ISSUE THREAD

**Issue by agr** [NuGet/NuGetGallery#8264]
### Describe the bug
At certain browser width (between "smartphone" and "tablet" layouts) package icons get displayed on search results page while they are not displayed in other narrow layouts.

### To Reproduce
1. On this URL https://www.nuget.org/packages
2. Make your browser window narrower until it switches to "smartphone" (the narrowest) layout.
3. Increase the window width slowly.
4. At certain window width (I think it is one specific pixel width) right when it is about to switch to tablet layout there would a point where package icons would appear while general layout is still "smartphone".

I had it reproed on 4k monitor with 150% scale set in display settings and 100% scale in the browser itself (Chromium Edge).

### Expected behavior
Since icons don't generally appear in both smartphone and tablet layouts, there shouldn't be a point between those where icons are displayed.

### Screenshots
![image](https://user-images.githubusercontent.com/102933/95923156-c2735e80-0d69-11eb-9a14-d531c96aab17.png)

### Additional info
That horizontal scrollbar at the bottom is probably undesired, too.

**Comment by rocklan** [comment]
Uh, this one is kind of insane. It's arguably a bug in bootstrap or chrome ... or even in CSS itself.  If you set the width of the browser to 767px you can see the icon is displayed, but not when wider or thinner. If you change the bootstrap.css file on line 5736 to be 767.9px instead of 767px it fixes the issue:

```css
@media (max-width: 767.9px) {
  .hidden-xs {
    display: none !important;
  }
}
```

But is 767.9 enough? What about 767.99? :) What about all of the other bootstrap widths? 

According to w3c, a (pixel value can have a decimal point)[https://www.w3.org/TR/2011/REC-CSS2-20110607/syndata.html#length-units], so it's completely valid. 

Now apparently max-width is always inclusive, and there's no way to make it exclusive, so there's no way to say "just make this apply for everything below 768px". Arguably that's a "bug" in CSS.. or perhaps if we were being generous we could call it a limitation.

So I propose it's just set to 767.9px.
