### ISSUE TITLE
Delete private packages and packages with 0 downloads

### ISSUE THREAD

**Issue by IdkGoodName** [NuGet/NuGetGallery#8314]
### Is your feature request related to a problem? Please describe.
I can't delete a package which is private and I don't need it anymore. I used it for testing before and now I can't delete it.

### Describe the solution you'd like
You should be able to delete private packages and packages with 0 downloads. If package is private or has 0 downloads, there will be no project which depends on it, so it would be safe to delete it.

**Comment by loic-sharma** [comment]
Thanks for reaching out. You should be able to delete the package by following these steps:

1. Click on “Contact support” on the package's page on nuget.org
1. Select a reason (do not select "Other" as the reason)
1. Select "Delete this package" for how you would like to proceed
1. Select "I understand that this action cannot be undone..."

This will delete the package. You will not be able to upload the same package ID and version again. I'll close off this issue, but please feel free to comment if you have any additional questions!

**Comment by PureKrome** [comment]
> but please feel free to comment if you have any additional questions!

🤚🏻 I do - you didn't answer the poster's question :( You did suggest a work-around (which is fine, etc).

Given the question "allow us to delete private packages -or- packages with 0 downloads" can someone please answer
- ❌ Nope -> we're not going to allow this because of <insert reasons, here>
- ✔️ Yep -> we will allow this. Watch this space
- 🤷🏻 Not sure -> we need to think about this, still. Maybe, maybe not.

Cheers! 🍰

**Comment by loic-sharma** [comment]
We don't allow NuGet package deletions as it would break every project that depend on it. For example, see the ["left-pad incident"](https://blog.npmjs.org/post/141577284765/kik-left-pad-and-npm).
 
NuGet.org does however support unlisting a package, which can be done from the Manage Package page. Unlisted packages don't appear on NuGet.org or in the Visual Studio UI, and do not appear in search results.

If you'd like to learn more, check out our docs: https://docs.microsoft.com/en-us/nuget/nuget-org/policies/deleting-packages

Please let me know if you have any addition questions.

**Comment by PureKrome** [comment]
Thanks heaps @loic-sharma for helping answer some of our questions, about this. Really appreciate it!

> as it may break every project that depend on it. 

Yep - this is the very well established story .. for PUBLIC packages. If we have _and own_ a private feed, then isn't it fair to say we control all who use it AND all who would use it? so then we could make the call on the impact? But I don't think the NuGet gallery support private feeds (which is such a missed opportunity :(  Gosh this would just make this product totally awesome).

> As per my previous comment, we do have an exception for newly uploaded packages with minimal downloads

But even though there is a work around for this, it's extremely slow and manual and i feel like most people would just shrug, cry and move on. So the question would be: why do you want to delete a package with 0 downloads if you can just unlist it (which is another often used suggestion, for this). It comes to numbering, which is (most of the time) an emotional thing, IMO.

If i have version 1.0.0 of a package, I would really love to keep the numbering in order, say 2.0.0 or 1.1.0 etc... and when I start unlisting packages because I just published a package but noticed something wrong with the package asap, I would unlist then quickly fix and then quickly publish again ... but the numbers are out.

It's a silly emotional feeling that can be shot down by many smarter people than I, in any debate. I totally accept that. (sorta like getting emotional with VM's where as VM's [should be treated like cattle and not pets](https://devops.stackexchange.com/questions/653/what-is-the-definition-of-cattle-not-pets)"). But these numbering-feelings still exist.

And it shouldn't be impacting anyone cause it's zero downloads.

Anyways, that my (our?) human, emotional angle on things.

**Comment by loic-sharma** [comment]
> But I don't think the NuGet gallery support private feeds (which is such a missed opportunity :( Gosh this would just make this product totally awesome).

We support lots of private server implementations! You can find a list here: https://docs.microsoft.com/en-us/nuget/hosting-packages/overview

> If we have and own a private feed, ...

Private feeds can choose how they interpret the [`nuget delete`](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-delete) or [`dotnet nuget delete`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-delete) commmands. Some private feed implementations do support package deletions. For example, BaGet lets you enable package deletions (see [this](https://loic-sharma.github.io/BaGet/configuration/#enable-package-hard-deletions)).

**Comment by PureKrome** [comment]
> NuGet has many private server implementations! 

Ah - I miscommunicated.

I wish the NuGet -gallery- would support private feeds because it's currently such a great product! That would just be the "bee's knees" having that extra item.

Other products like your awesome 🥖 (i love that name) mean we need to manage them, which is not something many of us wish to do. I suppose this means that if we wish to have private feeds, we need to pay for it. Which might be OK for most scenarios?

Cheers again! keep up the awesome work!

**Comment by loic-sharma** [comment]
Ah that's an interesting idea! Feel free to create a new issue for your feature request, this helps us prioritize as people upvote issues :)
