### ISSUE TITLE
Nuget Package Version History sorting is incorrect for prerelease suffixes

### ISSUE THREAD

**Issue by jzabroski** [NuGet/NuGetGallery#8325]
### Describe the bug
NuGet Package Version History sorting is incorrect.  It sorted lexicographically rather than understanding the package versioning schema for beta releases.

As an example, RazorLight2.0.0-beta9 comes above RazorLight2.0.0-beta10.

### To Reproduce
1. Open web browser (mine is Chrome)
2. Go to https://www.nuget.org/packages/RazorLight
3. Expand "Version History" accordion control
4. Observe that it sorts packages by major version number, but when you use prerelease suffixes, the sorting breaks.

### Expected behavior
Why not just sort it by last updated date?

### Screenshots
![image](https://user-images.githubusercontent.com/447485/99278405-fde7c980-27fc-11eb-9f09-a391ea63c2b2.png)

### Additional context
https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages#semantic-versioning implies that `-alpha`, `-beta`, and `-rc` are well known pre-release tags, so it seems natural to expect these pre-release tags to also include version numbers and that these suffix version numbers to sort correctly.

Also, note that for packages like [Newtonsoft.Json](https://www.nuget.org/packages/Newtonsoft.Json/), where the major versions cross from 9 to 10, the major.minor.patch convention sorts correctly, so it seems like the issue is confined to just pre-release tags.  I realize pre-release tags can be any value, but the nuget docs literally suggest sticking with `-alpha`, `-beta`, and `-rc`

**Comment by jzabroski** [comment]
BTW, my workaround, which is stupid, is to drop `-beta` and move to `-rc` labeling convention.

**Comment by joelverhagen** [comment]
Hey @jzabroski, thanks for taking the time to report this.

NuGet follows the SemVer specification. The behavior you're describing is confusing, as you say, but by design. The prerelease label of a SemVer version is sorted in lex order. However, in SemVer 2.0.0 there is a way to split the prerelease label into pieces with `.` (dot) delimiters and each section will be sorted either by lex or by numeric value depending on the shape.

Compare this:

SemVer 1.0.0 - lex order:
https://nugettoolsdev.azurewebsites.net/5.8.0/sort-versions?versions=2.0.0%0D%0A2.0.0-beta1%0D%0A2.0.0-beta9%0D%0A2.0.0-beta10

SemVer 2.0.0 - numeric order:
https://nugettoolsdev.azurewebsites.net/5.8.0/sort-versions?versions=2.0.0%0D%0A2.0.0-beta.1%0D%0A2.0.0-beta.9%0D%0A2.0.0-beta.10

For more information, consider reading our documentation about NuGet versioning:
https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#pre-release-versions

Or the SemVer spec:
https://semver.org/spec/v2.0.0.html

Note that there are some small differences between NuGet's implementation of SemVer and the official spec. For example, NuGet treats versions as case-insensitive strings and allows an optional 4th digit in the version number (to support `System.Version`).

**Comment by jzabroski** [comment]
So, in short, you are saying the problem exists between the keyboard and the chair :-)

So, in summary, I should create 2.0.0-rc.1 not 2.0.0-rc1 for my next release and I will have it correct.

This all makes total sense and I apologize for thinking it should work this way without double checking the spec prior to filing my issue.

**Comment by jzabroski** [comment]
@joelverhagen I think I know why I adopted rc1 instead of rc.1. Check out https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack

Will submit PR to fix.  Not sure if you have authority to help flag and push along.
