### ISSUE TITLE
Having an issue uploading to Nuget.org

### ISSUE THREAD

**Issue by osaghaso** [NuGet/NuGetGallery#8346]
Hi,
i'm trying to upload package using "Upload" button at https://www.nuget.org/packages/upload, but i'm receiving " This package ID has been reserved. Please request access to upload to this reserved namespace from the owner of the reserved prefix, or re-upload the package with a different ID". 
Can you help me with this?.

**Comment by loic-sharma** [comment]
Hello, this happens when the package you upload has a reserved package ID prefix. For example, the package ID `Microsoft.` is reserved to the Microsoft account, you cannot upload a package named `Microsoft.Foo`. You will need to rename your package. For more information, please refer to this documentation: You will need to rename your package.  

Please let us know if you have any additional questions or feedback!
