### ISSUE TITLE
Inline code block in documentation is HTML-entity-encoded twice

### ISSUE THREAD

**Issue by carlreinke** [NuGet/NuGetGallery#8372]
Input:
```
Usage: `SlnSort [options] <sln>`
```
Output:
![image](https://user-images.githubusercontent.com/11667451/104103122-9890e180-525d-11eb-8031-2102ade45a09.png)

Previously reported in #4946, which was apparently closed without being fixed.

**Comment by skofman1** [comment]
@lyndaidaii , can you please take a look?

**Comment by lyndaidaii** [comment]
@carlreinke, thank you for your bug report. This will be fixed with [PR](https://github.com/NuGet/NuGetGallery/pull/8292/files).
I will let you know once go live on nuget.org. 
We are currently switching markfown paser from commonmark to markdig. We added addtional functional like emjo, table, tasklist, autolink. 
Feel free to provide more feedback once this change is deployed.

**Comment by lyndaidaii** [comment]
@carlreinke  We deployed changes to nuget.org. it should be fixed now. Close this ticket for now. Let us know if you have more questions.
