### ISSUE TITLE
Stats: Community Packages shows non-Community Packages #2

### ISSUE THREAD

**Issue by 304NotModified** [NuGet/NuGetGallery#8456]
### Describe the bug

The Community Packages shows non-Community Packages, see screenshot

url: https://www.nuget.org/stats/packages

### To Reproduce
1. go to https://www.nuget.org/stats/packages

### Expected behavior
Not showing Microsoft packages when "Show all packages" isn't checked. Currently 3 microsoft.* packages are shown

### Screenshots

![image](https://user-images.githubusercontent.com/5808377/111561543-e9a8de80-8794-11eb-9d5c-0a7e3b9e43b6.png)

related: https://github.com/NuGet/NuGetGallery/issues/7314

**Comment by shishirx34** [comment]
@304NotModified - Thank you for reporting this issue. We need to update our non-community package filter list. I see some more packages in that list which should also be filtered out. I will fix it.

**Comment by shishirx34** [comment]
The list has been updated. There were 3 non-community packages that have been filtered out now.

**Comment by 304NotModified** [comment]
Thanks!

Good to know, I can't send a PR in the future for this?

Also, the filtering doesn't support wildcards? (e.g. `Microsoft.*`')

**Comment by shishirx34** [comment]
Unfortunately not. Currently this is a database operation so needs some privileged action. We do not want to include wildcards because there are some old third party(community packages with that namespace, some owned by dotnetfoundation) packages which we do not want to blanket block from that list. 

Good news is there is some ongoing work to improve statistics pipeline which could potentially automate this process and not need any intervention in future.
