### ISSUE TITLE
[Speculative bug] Package.DownloadCount is going to eventually overflow

### ISSUE THREAD

**Issue by pranavkm** [NuGet/NuGetGallery#8476]
### Describe the bug
We were admiring Json.NET's almost 1 billion download count today. I was curious about the data type used to store this value in the gallery. It looks like [Package.DownloadCount](https://github.com/NuGet/NuGetGallery/blob/be38792c3d3d327765113a32d82cd5b9b68cd1b0/src/NuGet.Services.Entities/Package.cs#L60) is a int32 value and will eventually overflow to negative values. Might be prudent to update that property and everything that touches it to use a 64-bit integer.

**Comment by JamesNK** [comment]
Newtonsoft.Json is getting 74 million downloads every 6 weeks. If it stays constant, in about 80 weeks it will break Int32.MaxValue (2.1 billion)

**Comment by loic-sharma** [comment]
Thanks for reporting this! It looks like a few areas are affected:

https://github.com/NuGet/NuGetGallery/blob/be38792c3d3d327765113a32d82cd5b9b68cd1b0/src/NuGet.Services.Entities/Package.cs#L60

https://github.com/NuGet/NuGetGallery/blob/be38792c3d3d327765113a32d82cd5b9b68cd1b0/src/NuGet.Services.Entities/PackageRegistration.cs#L26

https://github.com/NuGet/NuGet.Jobs/blob/376ac06e6e07d4ee8d1e28f6b2346e3891487496/src/Stats.Warehouse/Tables/dbo.Fact_Download.sql#L12

**Comment by JamesNK** [comment]
I think it is important to test what happens to clients. There will likely be some older clients out there that are no longer updated. What happens when they get int32.maxvalue+1?

**Comment by joelverhagen** [comment]
Thanks @pranavkm and @JamesNK for bringing this to our attention.

We've been loosely following the numbers and have fixed some problems in this area already. For example it's possible that our front page total download count stopped updating one time suspiciously close to `int.MaxValue` several years back 🙄. But a full analysis should be done since this will be the first time a _single_ package exceeds `int.MaxValue`.

I think overflowing to negative is a better case than, you know, VS UI crashing 😨. We need to dig through server and client side.

Thanks @loic-sharma for the initial analysis!

**Comment by ymwymw** [comment]
Just a suggestion, maybe manually move the download count down as it's moving up until you know everything is fixed. or have it as a backup plan on D-Day.

**Comment by dsteinweg** [comment]
Not sure if this is the right place to report a VS UI bug, but the display label for download counts seems to follow the file size convention (K for kilobyte, M for megabyte, G for gigabyte) instead of the normal English convention (K for thousand, M for million, B for billion).

See here, I'd expect it to say "1.1B downloads" for Newtsonsoft.Json instead of "1.1G downloads":

![image](https://user-images.githubusercontent.com/112942/122967664-51e8fc80-d350-11eb-8ca1-2dd687184ca2.png)

This was from VS2019 Enterprise 16.10.2, though it seems to be present in VS2022 Preview 1 as well (17.0.0 Preview 1.0).

**Comment by JamesNK** [comment]
G is correct https://en.wikipedia.org/wiki/1,000,000,000

**Comment by canton7** [comment]
The "G" is a [metric prefix](https://en.wikipedia.org/wiki/Metric_prefix):

> A metric prefix is a unit prefix that precedes a basic unit of measure to indicate a multiple or submultiple of the unit.

Strictly speaking, prefixes are added to basic units of measure. While some parts of the world seem to use them standalone, I wouldn't consider this universal by any means: I've *never* seen "2 billion" written as "2G", only ever as "2B". Likewise I've never seen "$2G", etc.

**Comment by joelverhagen** [comment]
[Microsoft.Extensions.Primitives](https://www.nuget.org/packages/Microsoft.Extensions.Primitives/7.0.0-preview.6.22324.4) was the first package to exceed `Int32.MaxValue` and things are working well.
![image](https://user-images.githubusercontent.com/94054/180278537-621807d5-4f0a-442c-8dbe-61769b8e816c.png)
([source](https://www.nuget.org/packages?packagetype=&sortby=totalDownloads-desc&q=owner%3Ajamesnk+owner%3Amicrosoft&prerel=True))

Kudos to @ryuyu for rolling out the necessary changes. NuGet should be totally compatible with download counts exceeding `Int32.MaxValue` (2,147,483,647) at this point.

If you run into any problems, please open an issue on [NuGet/NuGetGallery](https://github.com/NuGet/NuGetGallery/issues/new/choose) if it is a NuGet.org problem or [NuGet/Home](https://github.com/NuGet/Home/issues/new/choose) if it is a NuGet client tooling (VS, nuget.exe, .NET CLI) problem. IIRC some very old versions of NuGet client may have issues, so please reproduce any issue found on recent tooling versions.

**Comment by prime167** [comment]
It only took 71 weeks 😃 

![image](https://user-images.githubusercontent.com/3722845/184095391-60d420b1-c422-41d8-934d-d7df3255b728.png)

**Comment by DaleMckeown** [comment]
The download count has been stuck on 2161665532 for an hour now, though I do not know how often it updates.

![image](https://user-images.githubusercontent.com/1249673/184891360-7e0be587-92d6-46a9-aa4a-92cce4dfd87e.png)

Curiously, while this is not int32 MaxValue, it's suspiciously identical to the value of a bug I have just reported With Azure DevOps where artifact feeds are failing to consume upstream feeds (in this case NuGet).

`{"$id":"1","innerException":null,"message":"Failed to retrieve data from the upstream package source 'https://api.nuget.org/v3/index.json': JSON integer 2161665532 is too large or small for an Int32. Path 'data[0].totalDownloads', line 1, position 827.","typeName":"Microsoft.VisualStudio.Services.Packaging.ServiceShared.Upstream.PublicUpstreamFailureException, Microsoft.VisualStudio.Services.Packaging.ServiceShared","typeKey":"PublicUpstreamFailureException","errorCode":0,"eventId":3000}`
 
 https://developercommunity.visualstudio.com/t/Azure-Artefacts-feeds-no-longer-working/10121986?space=21&entry=problem&sort=newest
