### ISSUE TITLE
Mismatch between UI and API for version information

### ISSUE THREAD

**Issue by coke** [NuGet/NuGetGallery#8523]
### Describe the bug
Version visible on UI reports 404 when using the API to get detailed information

### To Reproduce

1. Open https://www.nuget.org/packages/microsoft.identity.client/
2. See versions available (including those hidden under 'Show more'), includes 4.26.0
3. Open https://api.nuget.org/v3/registration3/microsoft.identity.client/4.26.0.json - get 404

Other versions, e.g. https://api.nuget.org/v3/registration3/microsoft.identity.client/2.6.2.json, return expected information

### Expected behavior
Every version in the UI should have detailed information available at the registration3 endpoint.

**Comment by joelverhagen** [comment]
Hello, apologies for the inconvenience here. This is actually by design. The base URL you have there ( `https://api.nuget.org/v3/registration3/`) was deprecated long ago and we have since moved to a new base URL. The new base URL that corresponds to this old one is: `https://api.nuget.org/v3/registration5-semver1/`.

I should also note that this `registration3` base URL and the new `registration5-semver1` only contain SemVer 1.0.0 packages. Over 95% of users and clients today support SemVer 2.0.0 so I would recommend using the base URL that contains SemVer 2.0.0 packages as well: `https://api.nuget.org/v3/registration5-gz-semver2/`.

If you are encountering this problem it is likely because you hardcoded the base URL into your script or code. This is not advisable because we change these base URLs from time to time (perhaps due to new metadata backfills or other administrative actions). To dynamically discover the current base URL, you should go to the service index (https://api.nuget.org/v3/index.json) and look up the base URL with a type `RegistrationsBaseUrl/3.6.0`.

It might help clear things up if you want to read through our API docs:
https://docs.microsoft.com/en-us/nuget/api/overview

The registration (package metadata) resource is documented specifically here:
https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource

If you are writing your code in .NET, you can consider using the NuGet client SDK. Here's an example on how to enumerate versions and metadata using the .NET SDK:
https://docs.microsoft.com/en-us/nuget/reference/nuget-client-sdk#list-package-versions

This handles the service (base URL) discovery that I mentioned above and can save you a lot of trouble of writing it yourself.

**Comment by joelverhagen** [comment]
I should also note that hard-coding against the "registration leaf" URL is a bit risky since it's only by implementation detail that the URL is formatted: `{base URL}/{lower ID}/{lower, normalized version}.json`. The official NuGet client does not use this pattern and it is not documented to be exactly like this all of the time.
https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource#registration-leaf

> On nuget.org, the URL for the registration leaf document coincidentally contains the package version. However, this assumption should never be made by a client since server implementations are free to change the shape of the URL as long as the parent document has a valid link.

That being said, if your code only uses NuGet.org's V3 API and no other package source, you are free to take the risk and depend on this NuGet.org implementation detail. It's possible we'll change it in the future but currently we have no plans to do so.

**Comment by coke** [comment]
Thank you for the quick and helpful reply! I had found the registration3 URL via a google search, and didn't realize I was working with a deprecated endpoint.

The particular item I'm writing currently is not in .NET. I'll make an immediate switch to use the new URL you note, and eventually switch over to avoid the risk on the implementation detail. Thanks
