### ISSUE TITLE
What's the correct way to list dependencies of NuGet packages?

### ISSUE THREAD

**Issue by chucklu** [NuGet/NuGetGallery#8659]
AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1573 and dotnet/SqlClient#1137.
Currently based on my experience, we should list all top level dependences on NuNet package page, such as https://www.nuget.org/packages/Microsoft.Data.SqlClient/3.0.0. However this package only list Azure.Identity as required dependency. I suppose the Azure.Core also be listed as a required dependency, as the Microsoft.Data.SqlClient reference it directly.

    .NETFramework 4.6.1

    Azure.Identity (>= 1.3.0) 

I just wonder what's the correct way to list the dependencies.
Imagine that we have a libA which references packageB and packageC. And packageB require PackageC.
I think the libA should list both packageB and packageC as dependencies, but from the above mentioned Microsoft.Data.SqlClient package, it only list packageB. Which one is the correct one?

**Comment by chucklu** [comment]
Maybe you have a rule book about this? I have tried to Google it, but no lucky.

**Comment by joelverhagen** [comment]
Hello @chucklu, judging based on the other issue, it seems like you may have come to the conclusion already. But just in case, I'll try to clarify here.

The dependency information shown on nuget.org is direct _package dependencies_. This is not necessary the same as assembly references for several reasons:

1) When you depend on a package, it can pull in many transitive package dependencies which themselves may bring other assemblies. At build time, you can reference any of those assemblies brought in packages either directly or indirectly. For the Azure.Core example, this is a transitive dependency of Microsoft.Data.SqlClient because Azure.Identity (a direct dependency) itself depends on Azure.Core. This means that any assembly in the Azure.Core package can actually be an _assembly reference_ of the SqlClient DLL or even your own project that uses the Microsoft.Data.SqlClient package.

2) Not all packages actually bring assemblies. This means you might see a name pop up in the nuget.org UI of a package that has not matching assembly name. Some packages are so-called "meta-packages" that do not contain assemblies but instead contain only dependencies on other packages.

3) Sometimes the package ID does not match the assembly name. This can further confuse the situation that you were investigating in the other issue.

I hope this clears things up. In short, this is expected due to how transitive package dependencies work in NuGet.

**Comment by chucklu** [comment]
@joelverhagen  Thanks for your explanation.
