### ISSUE TITLE
[Redesign display package page] Add preview banner & URL 

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#8672]
Allow users to opt-in to the new design by appending a `preview=1` query string to the URL. Also, add a golden banner to the top of the page to let customers opt in to the new design and give feedback.

**Comment by jcjiang** [comment]
Est. time: ~ one week (Mon to Mon), may extend based on customer response

**Mon:**

- share tweet with query link to preview page
- update original spec thread
- ask for thoughts in GitHub Discussions or tweet replies
- start with small group of users who can point out any bugs in our preview set-up
- make banner live on preview package details page "what do you think? [survey]"
   - collect contact info of users who want to talk to us more about 1) current design 2) future iterations
   
![image](https://user-images.githubusercontent.com/23298667/127037605-5315a69f-cee2-460c-93da-40b634442a6c.png)

The survey is found [here](https://www.surveymonkey.com/r/Preview/?sm=EaOChzwS1fLo1zib8RkkyqDhZzyO6wehWIpQ8vXBW5Kvye_2BTN0zhTOpLCR0fCfkS). 

**Tues:**

- make banner live on current package details page 

![image](https://user-images.githubusercontent.com/23298667/127037566-9d9a0ca3-23fa-4728-98a9-42453a045134.png)

**Wed-Fri:**

- schedule interviews/chats with users, as needed

**next Mon:**

- remove banner from current package details page

**Comment by zhhyu** [comment]
Some of my thoughts:
1. For step 1 on Monday, I feel that one day may not provide us enough time to collect feedback data;
2. Is that possible for customers to change back to the old version after they opt-in? My understanding is that the approach is not session-based. So if the customer refreshes the page, it will go back to the old version?
3. I think that most of packages don't have readmes yet, will this be an important factor that affects a customer's opinion if the default tab is readme.

**Comment by jcjiang** [comment]
@zhhyu 

1. That's a really good point! I will change the plan to allow for at least 2 days of Twitter-only feedback. We can be flexible about when we turn on the banner for all package details pages and adjust based on how much interest we get.
2. The page will not go back to the old version when the customer refreshes since we are implementing the preview using a query string in the URL - as long as the same URL is being navigated to, the customer will still get the preview page.
3. Thanks for bringing that up. I definitely say it's a concern and comes down to the balance between "showing so people use it" and "not showing because people haven't used it yet." Right now we're still showing readme as the default tab, but happy to adjust if we see that it's an issue in survey responses.

**Comment by loic-sharma** [comment]
@dannyjdev You can verify this by going on the package details page. It should have a golden banner asking you to use the preview. If you click the preview link, you should see the preview plus a golden banner asking you to fill out the survey.
