### ISSUE TITLE
[Feature]: API endpoint for package README.md file

### ISSUE THREAD

**Issue by CyberAndrii** [NuGet/NuGetGallery#8732]
### Related Problem

Hi. On our site, we list packages made by other people for our framework. We use the gallery API to find them by tags. But it's hard for users who don't know what NuGet or GitHub is to find docs so we would like to show readme files. The issue is that there is no way to retrieve them.

### The Elevator Pitch

The best option would be having a REST API for getting the contents of README.md file.

### Additional Context and Details

[There already is a similar endpoint](https://github.com/NuGet/NuGetGallery/blob/77c5f6e57e0e53e8ef52b3e433571b2469681e25/src/NuGetGallery/Controllers/PackagesController.cs#L2954..L2981) but it is only for package owners, even if it is read-only, why?

Would you like me to PR this feature?

**Comment by joelverhagen** [comment]
There is an **unofficial** extension to the [package content API](https://docs.microsoft.com/en-us/nuget/api/package-base-address-resource) which surfaces the README.md, for example:
https://api.nuget.org/v3-flatcontainer/knapcode.torsharp/2.8.1/readme

By unofficial, I mean that our team has put README and icon files next to the documented .nupkg and .nuspec download URLs. At this point, this is not guaranteed to work forever (it's not specified in the protocol) but you could consider taking the risk of depending on it as a workaround.

An alternative would be to build your own index of README files by scanning the catalog, e.g. using: [How-to: Query for all packages published to nuget.org](https://docs.microsoft.com/en-us/nuget/guides/api/query-for-all-published-packages).

For this scenario, we would want to avoid putting the read-only path in NuGetGallery code since this requires compute (Azure web apps compute time) vs. putting it on api.nuget.org which is CDN-based and highly scalable.

**Comment by loic-sharma** [comment]
@joelverhagen Are there any blockers to officially adding the README path to the V3 protocol? We could introduce a new package content resource version to declare support for READMEs. (We could also consider doing this for icons and embedded licenses too)

**Comment by joelverhagen** [comment]
> Are there any blockers to officially adding the README path to the V3 protocol

No blockers that I know of.

> We could introduce a new package content resource version to declare support for READMEs. (We could also consider doing this for icons and embedded licenses too)

I think we'd want to do them all at the same time, to have fewer granular versions. Love the idea.

**Comment by chgill-MSFT** [comment]
@loic-sharma 

> > We could introduce a new package content resource version to declare support for READMEs. (We could also consider doing this for icons and embedded licenses too)

>I think we'd want to do them all at the same time, to have fewer granular versions. Love the idea.

Should we make a new issue to add READMEs, embedded licenses, and icons to the V3 protocol?

**Comment by loic-sharma** [comment]
@chgill-MSFT Sure, I created this issue: https://github.com/NuGet/NuGetGallery/issues/8835

@CyberAndrii I'll close this off for now as we have a broader work item that also includes icons and licenses. Please subscribe to the other issue for updates.
