### ISSUE TITLE
[NuGet.org Bug]: Unable to upload a Certificate greater than 10 000 bytes

### ISSUE THREAD

**Issue by zosrothko** [NuGet/NuGetGallery#8755]
### Impact

I'm unable to use NuGet.org

### Describe the bug

I am uploading a Certificate but Nuget.org rejects it saying it is greater that 10000 bytes. In effet, the certificate metrixware.cer is 16K long

![image](https://user-images.githubusercontent.com/7262593/130573353-f0a17c0d-b94b-426e-847b-45d15f37df41.png)

### Repro Steps

Upload the joined certificate metrixware.cer below

[metrixware.cer.zip](https://github.com/NuGet/NuGetGallery/files/7037258/metrixware.cer.zip)

### Expected Behavior

The certificate beeing uploaded

### Screenshots

![image](https://user-images.githubusercontent.com/7262593/130573586-841f6cdd-e13f-403e-a542-369e805248b3.png)

### Additional Context and logs

![image](https://user-images.githubusercontent.com/7262593/130574129-c7251ac6-0653-419a-8ad8-7ba49b8aeba0.png)

**Comment by joelverhagen** [comment]
Could you provide a package that is signed with this certificate (prior to upload to NuGet.org of course)? The archive that you uploaded doesn't seem to be opening on my end.

**Comment by zosrothko** [comment]
Here the package

[Metrixware.MI.MaaS.Model.1.0.5.nupkg.zip](https://github.com/NuGet/NuGetGallery/files/7040990/Metrixware.MI.MaaS.Model.1.0.5.nupkg.zip)

**Comment by loic-sharma** [comment]
Somehow Windows is unable to extract the ZIP archives you are sharing. I'm getting the following errors:

![image](https://user-images.githubusercontent.com/737941/130665780-72403591-a4ee-4fbe-b46f-96183e9633e2.png)

Would you be able to share the raw .nupkg file?

**Comment by zosrothko** [comment]
I cannot upload the raw nuget package as github does not allow this nupkg suffix. So how could I send you this package. By the way, the issue is NOT about pushing the package at nuget.org but just adding the metrixware.cer into my list of certificates, thus I do not quite understand why you need the package. But anyway, I will send it to you.

**Comment by loic-sharma** [comment]
Ah, the NuGet package you shared is unsigned. We were hoping to get a NuGet package signed using your certificate so that we could extract your code signing certificate. Would you be able to share a .nupkg that is signed using your code signing certificate, or, your certificate in a ZIP archive that Windows can extract?

**Comment by zosrothko** [comment]
The NuGet package `Metrixware.MI.MaaS.Model.1.0.5.nupkg` from the zip file of the above comment is signed. Why do you need this package???. The issue is about the Metriware.cer certificate at nuget.org

**Comment by loic-sharma** [comment]
> The NuGet package `Metrixware.MI.MaaS.Model.1.0.5.nupkg` from the zip file of the above comment is signed.

The package you provided is not signed. If you open the package in [NuGet Package Explorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer) you will see:

![image](https://user-images.githubusercontent.com/737941/130685581-fbdbba78-d147-4832-8afc-8851407f76c9.png)

Here's what a signed package looks like in NuGet Package Explorer:

![image](https://user-images.githubusercontent.com/737941/130685724-12e6416b-7da1-41da-b9ba-3b29c744b6e1.png)

That `Json.NET (.NET Foundation)` link is the subject name of the code signing certificate. Clicking on this link lets you examine the certificate.

> Why do you need this package???. The issue is about the Metriware.cer certificate at nuget.org

We want to see the certificate you are trying to upload to nuget.org. There's multiple ways to share this certificate, such as:

1. Share the certificate file directly in a ZIP archive, or ...
2. ... Share a package that was signed using your certificate, so that we can extract the certificate from this package

**Comment by joelverhagen** [comment]
Certificate files can have many different kinds of encoding. There are many "standards" and encodings which could lead to a different file size. Personally, I've made mistakes in this area giving folks a Base64 DER or PEM encoded certificate when they needed DER, binary encoded certificates.

If you provide us a signed package, it will allow us to extract the certificate with the exact same encoding that NuGet.org expects to side step any encoding issue that you may be accidentally running in to.

Another thing you can try is to double check that the certificate is exported with "DER" encoding. This can be done by opening `mmc.exe` on Windows, adding the certificate snap-in, and exporting the public part of the certificate (do not include private key!):
![image](https://user-images.githubusercontent.com/94054/130690884-4895cc5d-83ad-4070-a80a-6e837ee8779d.png)

Just in case, here's the documentation about exporting and registering the certificate so you can double check your steps:
https://docs.microsoft.com/en-us/nuget/create-packages/sign-a-package#export-the-certificate-file

Also, increasing the file limit sounds quite reasonable, I just want to be sure that we understand the whole situation and can reproduce the problem in our test environment before making any fix. Thanks for your help!

**Comment by zosrothko** [comment]
Ok,I regenerate the certificate `metrixware.cer` using the `mmc `service and it can be uploaded. In fact, the initial `metrixware.cer` was in clear ascii text which is why its length was greater than 10 000 bytes. With the new one which is in binary form, everything is fine.

Thus I let you decide to close or not this issue.

Thanks for your help and attention.
Rgds
