### ISSUE TITLE
[NuGet.org Bug]: Inconsistent download statistics

### ISSUE THREAD

**Issue by FantasticFiasco** [NuGet/NuGetGallery#8770]
### Impact

It bothers me. A fix would be nice

### Describe the bug

The download statistics are inconsistent between viewing a package in the search results and in the view of the particular package. This also seems to affect [shields.io](https://shields.io/) badges where the number of downloads displayed are incorrect.

As to my specific problem:

- https://www.nuget.org/packages?q=AwsSignatureVersion4 shows 294,585 total downloads
- https://www.nuget.org/packages/AwsSignatureVersion4 shows 433,432 total downloads

### Repro Steps

https://www.nuget.org/packages?q=AwsSignatureVersion4 and https://www.nuget.org/packages/AwsSignatureVersion4 shows different download statistics.

### Expected Behavior

The number of downloads should be the same, indifferent of how I view the package.

### Screenshots

![image](https://user-images.githubusercontent.com/8513095/131253438-8e595d6f-733c-46db-a71d-71c5a2e0a16c.png)
![image](https://user-images.githubusercontent.com/8513095/131253449-1baf64b2-3214-4e83-a657-6570bf982161.png)

**Comment by joelverhagen** [comment]
Looks like this was an intermittent issue where the download count was measured in the middle of the value being updated. This value was cached and captured in memory on www.nuget.org and is prevented from decreasing due to this code:
https://github.com/NuGet/NuGetGallery/blob/dd64d52d5c1984a414869b1d411dcffd3afef425/src/NuGetGallery/Services/CloudDownloadCountService.cs#L203-L210

A subsequent deployment or node restart should fix this.

@dannyjdev, who is on-call, could we get a gallery deployment this week and then some eyes on this situation to make sure it resolves?

@agr + @ryuyu, any idea if this problem will be mitigated with the new stats pipeline?

**Comment by tonyqus** [comment]
@joelverhagen  It's nice to meet you here. 

I did notice that nuget is frequently changing the download number for some reasons. First time I see it, I guess I may not sleep very well and it's an illusion. :D But after several times, it looks there are some jobs running behind nuget.org to adjust the download number. 

According to what you explained, is it just cache issue? Because I even notice some big decrease for current version download data on NPOI nuget.

**Comment by joelverhagen** [comment]
Hi @tonyqus 👋! Yes, it's just a cache issue. We're very close to shipping a newer version of our stats pipeline that should avoid this problem. Keep an eye out for this problem in about a month or so. If it's still happening, we'll revisit this issue with fresh eyes. Apologies on the illusions 😄.

**Comment by joelverhagen** [comment]
We have since moved to a new statistics pipeline. This problem should no longer occur. If you face it again, please feel free to open a new issue. Thanks!
