### ISSUE TITLE
[UI]: Add a dark mode/theme to nuget.org

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#8773]
### Related Problem

A top ask in the redesign survey was to add a dark mode.

![image](https://i.imgflip.com/5lb79q.jpg)

### The Elevator Pitch

![image](https://user-images.githubusercontent.com/737941/131384030-bcafb9a8-6c4d-45c7-b2e1-b77226222b09.png)

Kudos to [Dark Reader extension](https://github.com/darkreader/darkreader) and @jcjiang for the "mock up" 😄

**Comment by renemadsen** [comment]
Any update on this issue?

**Comment by joelverhagen** [comment]
@renemadsen, no update yet. It's on our backlog but currently below the cutline for the current semester due to priority and capacity issues.

If you or anyone else the community is interested in making a contribution to complete this, that would be amazing! NuGet.org team could guide someone along the way to get the change tested and verified. I think one of the questions is how to toggle the setting and make the setting "sticky".

Some resources to consider:
- StackOverflow's journey for dark mode: https://stackoverflow.blog/2020/03/31/building-dark-mode-on-stack-overflow/
- Accessibility (most notably color contrast guidelines) as detected by [Accessibility Insights FastPass](https://accessibilityinsights.io/docs/web/getstarted/fastpass/).

**Comment by shahabhijeet** [comment]
@joelverhagen just saying..... getting at least two pages dark themed without the sticky-ness would be huge for users.
For e.g. the home page and the search results page, even if these two pages get dark themed for the duration of the browser session that will be huge.
I don't mind switching it back to dark theme every time I visit nuget.org (and my previous setting did not stick)

**Comment by NiKiZe** [comment]
Just use https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme why even bother with the toggles?

**Comment by JonDouglas** [comment]
Shipped via 

https://devblogs.microsoft.com/nuget/dark-mode-now-available-on-nuget-org/

![image](https://github.com/NuGet/NuGetGallery/assets/1288848/e363c037-fb24-47f7-b696-9859a6bc9fcb)
