### ISSUE TITLE
[README]: Allow Azure Pipelines Badge Images in README.md

### ISSUE THREAD

**Issue by RehanSaeed** [NuGet/NuGetGallery#8877]
### Related Problem

I use badge images from Azure Pipelines like this:

[![Serilog.Enrichers.Span package in serilog-exceptions feed in Azure Artifacts](https://feeds.dev.azure.com/serilog-exceptions/_apis/public/Packaging/Feeds/8479813c-da6b-4677-b40d-78df8725dc9c/Packages/3f8a2a7e-8124-4987-9c44-916dba83b9d6/Badge)](https://dev.azure.com/serilog-exceptions/Serilog.Enrichers.Span/_packaging?_a=package&feed=8479813c-da6b-4677-b40d-78df8725dc9c&package=3f8a2a7e-8124-4987-9c44-916dba83b9d6&preferRelease=true)

They currently show like this on NuGet:

![image](https://user-images.githubusercontent.com/2270364/141500441-233dfdef-4ab9-4db8-b4e0-c957e7d207ac.png)

Here is a link to the package:

https://www.nuget.org/packages/Serilog.Enrichers.Span/

### The Elevator Pitch

Azure Pipelines badges needs proper support.

**Comment by lyndaidaii** [comment]
@RehanSaeed, thanks for suggestion. We actually do support azure pipelines `dev.azure.com`, please check allowlist here: https://docs.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org#allowed-domains-for-images-and-badges. 
In your readme, it renders other azure pipeline bages.  I think the reason why this typical azure pipeline badge is not rendered because of the link has some error. Here is error message I got when I click this link: https://dev.azure.com/serilog-exceptions/Serilog.Enrichers.Span/_packaging?_a=package&feed=8479813c-da6b-4677-b40d-78df8725dc9c&package=3f8a2a7e-8124-4987-9c44-916dba83b9d6&preferRelease=true
![Screenshot 2021-11-16 111311](https://user-images.githubusercontent.com/64443925/142050347-ef8f7db5-9a6a-41e2-8117-e031df390a10.png)

**Comment by RehanSaeed** [comment]
The page loads for me, perhaps because I am the project owner?

The badge also loads above in my original message but not on nuget.org.

**Comment by lyndaidaii** [comment]
@RehanSaeed, I think it might be this reason. When I open this link, it doesn't show anything, no feed found. It might be private feed?

**Comment by lyndaidaii** [comment]
closed issue since it's not active anymore.
