### ISSUE TITLE
[NuGet.org Bug]: Never remembers my account

### ISSUE THREAD

**Issue by WhiteBlackGoose** [NuGet/NuGetGallery#8907]
### Impact

It bothers me. A fix would be nice

### Describe the bug

The problematic device - Ipad on 14.4 IpadOS. On my Windows laptop it works fine.

1. I fill in my MSFT Account
2. It then sends me a verification email
3. I confirm and check "Never ask again on this device"
4. I check "Never log out on this device" (or something, it's unfortunately localised)

Now, within less than a day it completely forgets my account.

### Repro Steps

See Describe the bug

### Expected Behavior

Expected - it won't log out me at all.

**Comment by joelverhagen** [comment]
Hello, @WhiteBlackGoose. Per security requirements for our service, the authentication session to NuGet.org only lasts for 6 hours. Unfortunately, this is an area where we do not have much flexibility to change due to requirements on our team.

Regarding the Microsoft account forgetting your device, this flow is outside of NuGet.org's control. NuGet.org depends on Microsoft account authentication in this area. I recommend reaching out to Microsoft support about this problem. Perhaps they can diagnose the problem: https://support.microsoft.com/contactus. 

For reference, when I log into NuGet.org with my Microsoft account, I am prompted to select my Microsoft account from a list but I am not asked to do any additional verification (2FA or email verification) because I have done this a long time ago on my PC. It sounds almost like your Microsoft account is forgetting your device or is for some reason seeing your device a "new" more often than expected.

**Comment by WhiteBlackGoose** [comment]
I see, thanks
