### ISSUE TITLE
[NuGet.org Bug]: Some problems with README Markdown rendering

### ISSUE THREAD

**Issue by zspitz** [NuGet/NuGetGallery#8913]
### Impact

It bothers me. A fix would be nice

### Describe the bug

I've uploaded a README file together with my NuGet package (https://www.nuget.org/packages/PandocFilters/) and the rendered Markdown is a little less than ideal:
1. Language codes for code blocks are ignored; no syntax highlighting.
2. There is no whitespace between cells in the rendered table.
3. No support for superscript (`<sup>...</sup>`).

### Repro Steps

Upload a README file for a NuGet package containing misrendered Markdown.

### Expected Behavior

Syntax highlighting for code blocks should render properly.

There should be some whitespace between table cells.

A limited set of HTML elements should be supported, `sup` in my case.

**Comment by joelverhagen** [comment]
Hello @zspitz, thanks for taking the time to report this. We have some tracking issues already filed for the problems you are describing. https://github.com/NuGet/NuGetGallery/issues/8837

Specifically:
- table rendering: https://github.com/NuGet/NuGetGallery/issues/8503
- syntax highlighting: https://github.com/NuGet/NuGetGallery/issues/8632
- limited HTML: https://github.com/NuGet/NuGetGallery/issues/8644

Could you upvote these issues so that we can prioritize them accordingly?

Thanks!
