### ISSUE TITLE
[NuGet.org Bug]: Project website not correct for project

### ISSUE THREAD

**Issue by scarabdesign** [NuGet/NuGetGallery#8940]
### Impact

It's more difficult to complete my work

### Describe the bug

The link on this page for the project website clearly points to the wrong URL:
https://www.nuget.org/packages/Xamarin.Firebase.iOS.Core

The link:
https://go.microsoft.com/fwlink/?linkid=2007321

Forwards to:
https://github.com/xamarin/FacebookComponents/tree/main/Facebook.iOS/source/LoginKit

It should instead forward to:
https://github.com/xamarin/GoogleApisForiOSComponents/tree/main/source/Firebase/Core

### Repro Steps

Go to https://www.nuget.org/packages/Xamarin.Firebase.iOS.Core and click the link for the Project website

### Expected Behavior

It should point to the actual project website

**Comment by joelverhagen** [comment]
Hey @scarabdesign, this GitHub issue tracker is more for specific issues related to NuGet.org itself, rather than individual packages. My team (who manages this repo) is unable to fix this problem since we don't modify metadata of packages not owned by our team. Sorry for the confusion.

Please contact the package owner directly using the "Contact owners" link on the package details page.

Thanks!
