### ISSUE TITLE
.NET 6 not listed besides .NET Core 3.1 /5.0

### ISSUE THREAD

**Issue by devlead** [NuGet/NuGetGallery#9005]
### Impact

It bothers me. A fix would be nice

### Describe the bug

.NET 6 not listed for Tool and class library targeting .NET 6, but .NET 5 and .NET Core 3.1 is. 

Example tool 
![Screenshot_20220215-224750](https://user-images.githubusercontent.com/1647294/154156200-abb96ccd-62d5-4b98-9805-2c4c2516c524.jpg)

Example class library
![Screenshot_20220215-225722](https://user-images.githubusercontent.com/1647294/154156592-f4fde3d8-ae61-44a5-9d1f-76dbf7a57e89.jpg)

Both have .NET 6 listed under frameworks
![Screenshot_20220215-230030](https://user-images.githubusercontent.com/1647294/154156782-422dc4bb-9c71-4d38-b91e-e20bf89cb411.jpg)

### Repro Steps

Go to
https://www.nuget.org/packages/Cake.Tool
or
https://www.nuget.org/packages/Cake.Core

### Expected Behavior

.NET 6 to be listed

**Comment by dannyjdev** [comment]
Hi, thank you for creating an issue. The "Framework Badges" will only display the 4 major .NET products (.NET, .NET Core, .NET Standard, and .NET Framework), and we are only including the lowest frameworks that are part of the package assets from each one of those products. In this particular case net5.0 and net6.0 are part of the package assets, but since net5.0 is the lowest package asset framework, we are only showing that. On the Frameworks tab we show all the available package asset frameworks along with additional computed frameworks.

**Comment by devlead** [comment]
I see, that was unexpected, especially excluding LTS versions. 

As this is by design, I'll go ahead and close this issue.

**Comment by JonDouglas** [comment]
@devlead This still brings up a question. Is there a preferred display for these badges from your perspective? That would really help us understand more. Such as LTS versions, latest versions, etc.

**Comment by devlead** [comment]
> @devlead This still brings up a question. Is there a preferred display for these badges from your perspective? That would really help us understand more. Such as LTS versions, latest versions, etc.

I would've expected .NET 6 to not be excluded.
