### ISSUE TITLE
Why this package has not been indexed yet in 2 hours ago? 

### ISSUE THREAD

**Issue by CurryHan** [NuGet/NuGetGallery#9025]
### NuGet Product Used

NuGet.exe

### Product Version

other

### Repro Steps & Context

![image](https://user-images.githubusercontent.com/14214176/155704759-fe6e1831-9db5-4cc2-9cf9-1d276b2a693a.png)

**Comment by joelverhagen** [comment]
Hey folks, feel free to open put issues about NuGet.org in this repo (NuGet/NuGetGallery). The other repo (NuGet/Home) is about NuGet client issues.

Regarding this delay, we had a problem in our publishing pipeline which has since been resolved. See our status page history:
![image](https://user-images.githubusercontent.com/94054/156105172-2abd73e4-9e31-4051-8673-24491a17c4af.png)
