### ISSUE TITLE
[NuGet.org Bug]: Connection resets and invalid JSON returned from api.nuget.org

### ISSUE THREAD

**Issue by Maraudingas** [NuGet/NuGetGallery#9140]
### Impact

I'm unable to use NuGet.org

### Describe the bug

Can't restore packages from Nuget API V3, getting the following error message:
```
Failed to download package 'Microsoft.AspNetCore.Http.2.2.2' from 'https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.http/2.2.2/microsoft.aspnetcore.http.2.2.2.nupkg'.
  Unable to read data from the transport connection: Connection reset by peer.
    Connection reset by peer
```

```
Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/system.buffers/index.json'.
  Response status code does not indicate success: 502 (Bad Gateway).
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/system.buffers/index.json'.
  An error occurred while sending the request.
    Unable to read data from the transport connection: Connection reset by peer.
    Connection reset by peer
  Failed to download package 'System.Text.Json.4.6.0' from 'https://api.nuget.org/v3-flatcontainer/system.text.json/4.6.0/system.text.json.4.6.0.nupkg'.
  An error occurred while sending the request.
    Unable to read data from the transport connection: Connection reset by peer.
    Connection reset by peer
```

### Repro Steps

Restore Nuget packages from Nuget API V3

### Expected Behavior

Nuget packages restored.

**Comment by Maraudingas** [comment]
Good catch! I think it starting to work again. I've got a successful pipeline working and local build.

**Comment by marcoschneidertui** [comment]
Yes agree,
I see the connection is secure again
![grafik](https://user-images.githubusercontent.com/30691895/173532462-a105d5f6-0781-48f3-83df-f2eef9e02851.png)

**Comment by Maraudingas** [comment]
Agree, for a period of time it was working, but now failing again.

**Comment by joelverhagen** [comment]
Hello, thanks for all of the reports. We had an increased error rate for our V3 CDN endpoints in some geographies from 11:30 PM Pacific time to 4:15 AM. Since that time window, our monitoring indicates the issue has been mitigated. Please do let us know on this thread if you are still facing a problem -- apologies for the inconvenience. We will work with our infrastructure partners to understand more deeply why this service degradation occurred.

**Comment by baudday** [comment]
I am still experiencing this issue.

**Comment by joelverhagen** [comment]
We have performed a CDN failover to mitigate the problem. Please do let us know if you are continuing to see problems restoring packages or interacting with api.nuget.org. Thank you for your patience!

**Comment by ocbjsys** [comment]
Experiencing this now.

It works in the browser but is a 500 in GitHub 
https://api.nuget.org/v3-flatcontainer/system.text.encodings.web/index.json

Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/system.text.encodings.web/index.json'. Response status code does not indicate success: 500 (Internal Server Error).

**Comment by mmisztal1980** [comment]
We're experiencing this right now.

```
Source 'https://api.nuget.org/v3/index.json' exception: System.Exception: Could not retrieve data from '[https://nuget.org/api/v2/FindPackagesById()?semVerLevel=2.0.0&id='Microsoft.Build.Utilities.Core''](https://nuget.org/api/v2/FindPackagesById()?semVerLevel=2.0.0&id=%27Microsoft.Build.Utilities.Core%27%27)
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
```

**Comment by certara-rgottam** [comment]
experiencing an internal server error

/usr/share/dotnet/sdk/3.1.409/NuGet.targets(128,5): error : Response status code does not indicate success: 500 (Internal Server Error)

**Comment by joelverhagen** [comment]
@mmisztal1980 - the error message provided mentions a V2 URL. Is it possible you have the feed configured as V2 with `protocolVersion="2"` in your NuGet.config file? I also noticed there is no "www." in the V2 feed URL. I'm not certain the specifics of your client setup. Finally, our telemetry is not showing any availability issues on our V2 endpoint. Is the issue persisting?

@certara-rgottam - thank you for providing these details. We are currently engaged with our CDN provider who is investigating the root cause. Based on our telemetry, we see that the failure rate has dropped down to significantly lower levels than during 10:50 PM - 11:40 PM 2022-07-13 PDT time zone. Please do let us know if the issue persists and apologies for the inconvenience.

**Comment by joelverhagen** [comment]
Hello @spotvader, this issue is likely related to cipher suites enabled on your PC and on NuGet.org. Could you please reach out to our support team using https://www.nuget.org/policies/Contact (sign in first). We'll be able to more closely assist you. 

Generally speaking, NuGet.org has moved to a new multi-CDN infrastructure: https://github.com/NuGet/Announcements/issues/60. Some older TLS cipher suites are deprecated from the new CDN service. We did the analysis before, and only very old OS systems may be impacted by this change. So we suggest you to check cipher suites configured on your machine to ensure that any of cipher suites listed in the announcement have been enabled.

**Comment by drewgillies** [comment]
Note this status update on Twitter: https://twitter.com/nuget/status/1554953163576586241?s=20&t=S40LVQSEMItr0CJPTg7bVQ. It's brief but it's essentially our experience--we are dependent on external services for connectivity and we have been working with them to determine what mitigations we can put in place in addition to the increased load capacity that has already been achieved.

**Comment by zhhyu** [comment]
Hello, we will close this issue now. Please reopen it or reach out to us at support@nuget.org if you meet this problem again. Thanks!

**Comment by tomasbruckner** [comment]
Having the same issue right now, Everything was working fine yesterday (also pipeline in Gitlab CI using Docker image)

**Comment by joelverhagen** [comment]
Hey @tomasbruckner, we have this issue tracking today's availability problem: https://github.com/NuGet/NuGetGallery/issues/9218. On that issue, please let us know if you are still encountering a problem.

**Comment by rendhiagnosyifa** [comment]
I'm get the same issue again.. please help me... 
![image](https://user-images.githubusercontent.com/71139924/232184412-3e5f751b-40d0-413c-953e-a1c34ea46217.png)

**Comment by zhhyu** [comment]
Hi, @rendhiagnosyifa! My apologies for this inconvenience!

We suggest you use the latest versions of NuGet clients to enhance the resilience. Please follow this document: https://learn.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq#why-can-t-i-restore-packages-from-nuget-org and contact support. We may need to collect more diagnostic information and reach out to the CDN provider for the further investigation. Thanks!

**Comment by pharindoko** [comment]
I receive the same today on different OS (Linux, mac) when I try to do a restore in a docker image

```
Response status code does not indicate success: 502 (Bad Gateway).
```

This worked before as expected.
Anyone else having this issue ?

**Comment by marcoschneidertui** [comment]
Yes, we are experience such issues today as well. It seems that issue is "going on/going off" as some of our pipelines are able to complete

**Comment by hepptho** [comment]
I'm seeing the `502 (Bad Gateway)`  today as well, when running `dotnet publish` in a docker container.
It still seems to work occasionally but only about 1/10.

**Comment by Lejandary** [comment]
Seeing the same bad gateway 502 errors when running dotnet restore - every time though, not intermittent

**Comment by KUTlime** [comment]
> Hey @tomasbruckner, we have this issue tracking today's availability problem: #9218. On that issue, please let us know if you are still encountering a problem.

@joelverhagen are you sure that you mitigate this enough?

Same like #9775

**Comment by ZUOXIANGE** [comment]
We're seeing this problem right now.
![image](https://github.com/NuGet/NuGetGallery/assets/20124439/c073cf9d-c235-48b5-b511-023ccbc3ab2b)

**Comment by dongfo** [comment]
> We're seeing this problem right now.我们现在看到了这个问题。 ![image](https://private-user-images.githubusercontent.com/20124439/302575570-c073cf9d-c235-48b5-b511-023ccbc3ab2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MDg0MTYsIm5iZiI6MTcwOTYwODExNiwicGF0aCI6Ii8yMDEyNDQzOS8zMDI1NzU1NzAtYzA3M2NmOWQtYzIzNS00OGI1LWI1MTEtMDIzY2NiYzNhYjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDAzMDgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjODBiZGNkYWM4OWFkNWRiZWQ3NGJkYTkxNTUzOTUwZGJlYThmY2I3OTNiZjY3MTAzMjJkYTQ0NDFjNjQ3OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qtIPiKRKE7iQiONQAOehboi2Trj2OBJuqf_BXTcHEdQ)

same to you

**Comment by shaxiaozz** [comment]
same to me

**Comment by ZUOXIANGE** [comment]
same to me

**Comment by enjoycx** [comment]
same to me

**Comment by Amin2003713** [comment]
same with me
