### ISSUE TITLE
[NuGet.org Bug]: Cannot sign in using Microsoft account security key

### ISSUE THREAD

**Issue by carlreinke** [NuGet/NuGetGallery#9207]
### Impact

It bothers me. A fix would be nice

### Describe the bug

"AADSTS500201: We are unable to issue tokens from this API version for a Microsoft account. Please contact the application vendor as they need to use version 2.0 of the protocol to support this."

### Repro Steps

1. Add a security key to the Microsoft account you will use to log in
2. Navigate to nuget.org
3. Click "Sign in"
4. Click "Sign in with Microsoft"
5. Click "Sign-in options"
6. Click "Sign in with Windows Hello or a security key"
7. Tap security key, provide PIN, etc.
8. Click "Confirm" if requested to confirm the sign-in.
9. "Sorry, but we’re having trouble signing you in."

### Expected Behavior

Sign in succeeds.

**Comment by joelverhagen** [comment]
Hello @carlreinke, based on my understanding of the problem, it seems like this is outside of the scope of NuGet.org and is a problem you're encountering while you are authentication with your Microsoft account.

I am not familiar with that error message and it's not clear to me what the "application" is in that context.

I suggest trying several things:

1. Reaching out to Microsoft support about this problem. Perhaps this is a known issue related to the specific 2FA authentication method you have selected.
1. Does this problem exist when using your Microsoft account to sign into any other website? I acknowledge this might be hard to test because not all Microsoft account sign in flows have an explicit MFA/2FA requirement.
1. Could you try an alternate 2FA credential type, for example signing up with an OTP Authenticator app? Based on your description it seems like you're using a hardware key or Windows Hello.

**Comment by carlreinke** [comment]
I am assuming that NuGet Gallery is the application in this case.

Were you able to reproduce the issue with the steps I provided?  Either you will not be able to reproduce the issue or you will quickly become familiar with the error code.

I do not have trouble signing into microsoft.com or outlook.com using this security key to authenticate with my Microsoft account.

**Comment by joelverhagen** [comment]
> Were you able to reproduce the issue with the steps I provided? Either you will not be able to reproduce the issue or you will quickly become familiar with the error code.

I was not. I have a USB Yubikey associated with my personal Microsoft account that can use to sign into my Microsoft account. The flow worked as expected in an InPrivate Edge browser instance.

**Comment by carlreinke** [comment]
Hmm, maybe I need to provide better steps then.  😓

Your security key is configured to be used for "Account sign in" and not for "Account verification"?

![image](https://user-images.githubusercontent.com/11667451/186948503-d9a8c6e6-73bf-4e70-9ab5-df5879660189.png)

**Comment by joelverhagen** [comment]
"Account sign in" (to be honest I don't know the difference between those two options you stated but it looks like we match)
![image](https://user-images.githubusercontent.com/94054/186952118-1141b785-1b68-49cf-9670-0234e230e773.png)

**Comment by carlreinke** [comment]
Okay, I guess it's just my account then.  If somebody else hits the same error, maybe we can determine the common factor.
