### ISSUE TITLE
[NuGet.org Bug]: code signing certificates

### ISSUE THREAD

**Issue by jmecosta** [NuGet/NuGetGallery#9222]
### Impact

I'm unable to use NuGet.org

### Describe the bug

We have a bigger wider organization in nuget that we want everyone to use in the company.  However some of the groups don't have signing certificates and nuget.org prevents their packages from being uploaded because other users in the organization have uploaded their certificate that they want use when delivering their packages.

We don't want people in the company to user other organizations. 

How we handle different maturity of teams inside the same organization? 

Is the only option  to force them to buy a certificate even tough they really don't need it?

Thanks in advance

### Repro Steps

Not applicable

### Expected Behavior

Not applicable

**Comment by joelverhagen** [comment]
Hey @jmecosta, I like the direction of this question. It's something that hasn't been explored deeply for general NuGet.org users. The Microsoft organization on NuGet.org has some procedures in place but these aren't easily replicated for all organizations (for a variety of reason). Up until now, the features and documentation for NuGet.org has been mainly tailored to individual developers or small organizations where this sort of "certificate management" question is not a challenging thing to complete with the provided resources.

All of that is to say: let's talk through the current state and your requirements to find the best solution.

> However some of the groups don't have signing certificates and nuget.org prevents their packages from being uploaded because other users in the organization have uploaded their certificate that they want use when delivering their packages.

Is the final goal for various team at your wider organization to use a single signing certificate or multiple, in parallel?

If there is a single signing certificate, each team can upload the same public certificate to the organization page thus allowing packages signed with that certificate. There is no requirement that a public certificate can only be used by a single NuGet.org account (user or organization).

This is essentially the model that Microsoft uses for its various NuGet.org organizations (although there are some tools running behind the scenes to make certificate rotation easier). Packages pushed by [azure-sdk](https://www.nuget.org/profiles/azure-sdk) or by [aspnet](https://www.nuget.org/profiles/aspnet) (separate teams, from a package ownership perspective) are both signed with a code signing with hash `A6E18D21B507879FC7F9C392A5CE355936E3AD2C`. I won't go into details of how packages from two teams are signed with the same certificate but suffice it to say that there is a shared internal system allowing secure signing with a single code signing certificate. The signing of course is done outside of the scope of NuGet.org but they arrive to NuGet.org with the same author signature signer.

> How we handle different maturity of teams inside the same organization?

I'm not sure how to answer this. Could you clarify your question?

From NuGet.org's perspective, there is really only one decision: is my team going to sign its packages or not? If the answer is no, the default behavior works fine. If the answer is yes, you must upload the public certificate to your owning account (either a user or organization profile).

> Is the only option to force them to buy a certificate even tough they really don't need it?

I am not an expert in code signing but I imagine it's the best use of company resources to use a single certificate for all code that a company ships. Maybe I think this because it's what Microsoft does... but once you figure out how to securely sign packages internally prior to release (i.e. one release management team holding the private key of the certificate) it seems like the best.

For teams, they don't need to manage the private key. They just need to upload the new .cer file when the certificate rotates.

For package consumers, there is a single entity appearing in packages you get from the company. Do package consumers really care about team X vs. team Y inside an organization? Probably not.

Remember that author signing on packages is _optional_. If you want to sidestep the issue and you are not concerned about the additional security benefits of author signing, can you just tell some teams "don't sign your packages"?

**Comment by jmecosta** [comment]
On Tue, Sep 6, 2022 at 11:50 PM Joel Verhagen ***@***.***>
wrote:

> Hey @jmecosta <https://github.com/jmecosta>, I like the direction of this
> question. It's something that hasn't been explored deeply for general
> NuGet.org users. The Microsoft organization on NuGet.org has some
> procedures in place but these aren't easily replicated for all
> organizations (for a variety of reason). Up until now, the features and
> documentation for NuGet.org has been mainly tailored to individual
> developers or small organizations where this sort of "certificate
> management" question is not a challenging thing to complete with the
> provided resources.
>
> All of that is to say: let's talk through the current state and your
> requirements to find the best solution.
>
> However some of the groups don't have signing certificates and nuget.org
> prevents their packages from being uploaded because other users in the
> organization have uploaded their certificate that they want use when
> delivering their packages.
>
> Is the final goal for various team at your wider organization to use a
> single signing certificate or multiple, in parallel?
>
I dont see us having a single certificate for the all company, even
security wise is more problematic because more users using it more likely
the certificate can leak. Unless you develop a central way of doing it
without users having access to it.. Then we also have multiple CIs so
applying that looks complicated. Each division or group will  likely own a
company  official certificate.

> If there is a single signing certificate, each team can upload the same
> public certificate to the organization page thus allowing packages signed
> with that certificate. There is no requirement that a public certificate
> can only be used by a single NuGet.org account (user or organization).
>
This is essentially the model that Microsoft uses for its various NuGet.org
> organizations (although there are some tools running behind the scenes to
> make certificate rotation easier). Packages pushed by azure-sdk
> <https://www.nuget.org/profiles/azure-sdk> or by aspnet
> <https://www.nuget.org/profiles/aspnet> (separate teams, from a package
> ownership perspective) are both signed with a code signing with hash
> A6E18D21B507879FC7F9C392A5CE355936E3AD2C. I won't go into details of how
> packages from two teams are signed with the same certificate but suffice it
> to say that there is a shared internal system allowing secure signing with
> a single code signing certificate. The signing of course is done outside of
> the scope of NuGet.org but they arrive to NuGet.org with the same author
> signature signer.
>
Ok i think this is what i was confused about... So the problem, our main
account, lets called Organization A has several admins (one per division,
not the best in terms of permissions but thats what nuget.org offers). Me
as an admin uploaded our cer to the organization (not my account), so
basically the other admins were no longer able to upload nugets anymore
because the cert applyed to all organization. However if i understood you,
what i should have done is upload to certificate to my account only or to
all accounts that use our certificate. So the wide Organization A in fact
cant have any certificate... And admins decide if they upload cert to there
account or not.

If you confirm this, then yes, this is what we need to suits us very
well.  And yes, we have something similar internally were we have 2 teams
using one certificate. But this is something done in a single CI system, so
we control the signing. Other groups will have their own certificate if
needed.

> How we handle different maturity of teams inside the same organization?
>
> I'm not sure how to answer this. Could you clarify your question?
>
Was related with previous point, some teams dont do code signing (i see
maturity level related with signing)

> From NuGet.org's perspective, there is really only one decision: is my
> team going to sign its packages or not? If the answer is no, the default
> behavior works fine. If the answer is yes, you must upload the public
> certificate to your owning account (either a user or organization profile).
>
Yes very clear now.

> Is the only option to force them to buy a certificate even tough they
> really don't need it?
>
> I am not an expert in code signing but I imagine it's the best use of
> company resources to use a single certificate for all code that a company
> ships. Maybe I think this because it's what Microsoft does... but once you
> figure out how to securely sign packages internally prior to release (i.e.
> one release management team holding the private key of the certificate) it
> seems like the best.
>
I dont see why a company cant have multiple certificates.  You just say we
have the following hashes that we use to sign code.

> For teams, they don't need to manage the private key. They just need to
> upload the new .cer file when the certificate rotates.
>
Clear

> For package consumers, there is a single entity appearing in packages you
> get from the company. Do package consumers really care about team X vs.
> team Y inside an organization? Probably not.
>
We want the packages the owner to be all from the main organization A.
Earlier the packages owners your the teams... so thats one requirement for
us.

> Remember that author signing on packages is *optional*. If you want to
> sidestep the issue and you are not concerned about the additional security
> benefits of author signing, can you just tell some teams "don't sign your
> packages"?
>
Yes, this is what will happen. I dont think we can force everyone to force
the packakges. What we want is that eveyone use the Organization A to host
there packages.

I will do some testing, but from this discussion i understand now
everything should work as we want.  I will close ticket once i get
everything working. Thanks

**Comment by joelverhagen** [comment]
Hey @jmecosta, just wanted to check in and see if you have everything sorted. I'll close this issue after 7 days if I don't hear back from you.

**Comment by jmecosta** [comment]
@joelverhagen  thanks and apologies for the delay... everything is clear now from our side... The description you provided works quite ok. thank you again
