### ISSUE TITLE
[NuGet.org Bug]: Different search result count between NuGet.org search UI and API

### ISSUE THREAD

**Issue by MangelMaxime** [NuGet/NuGetGallery#9235]
### Impact

Other

### Describe the bug

There is a different number of pacakges found between NuGet.org website and the search API.

### Repro Steps

Click on the links below and compare the number of packages reported.

| Source     | Url                                                           | TotalHits |
|------------|---------------------------------------------------------------|-----------|
| NuGet.org  | [`https://www.nuget.org/packages?q=Tags%3A%22fable%22`](https://www.nuget.org/packages?q=Tags%3A%22fable%22)           | 361       |
| Search API | [`https://azuresearch-usnc.nuget.org/query?q=Tags%3A%22fable%22&prerelease=true`](https://azuresearch-usnc.nuget.org/query?q=Tags%3A%22fable%22&prerelease=true) | 360 |

The difference being of only 1, I wonder if this something harmful or if this is just because of an index issue related to zero based array for example.

### Expected Behavior

Both way of searching should return the same number of packages.

### NuGet.org

![image](https://user-images.githubusercontent.com/4760796/189943046-0305fd6b-1583-4ab1-87a6-1f66ab0f5524.png)

### Search API

![image](https://user-images.githubusercontent.com/4760796/189943534-4f58a7a9-6f0c-4451-a4a6-cfb3de234b6d.png)

**Comment by joelverhagen** [comment]
This is because prerelease and SemVer 2.0.0 packages are filtered out by default. Please take a look at the API documentation here: https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource#request-parameters.

Try this URL:
https://azuresearch-usnc.nuget.org/query?q=Tags%3A%22fable%22&prerelease=true&semVerLevel=2.0.0
(note the `semVerLevel=2.0.0` parameter I added)

The NuGet.org search web UI includes SemVer 2.0.0 package cause nearly all users have SemVer 2.0.0 compatible clients. We cannot do this breaking change on the search API so it is opt-in on the API.

**Comment by MangelMaxime** [comment]
Hello @joelverhagen,

thank you for the explanation. I was aware of the `prerelease=true` requirements but I didn't know about the `semVerLevel` I will make sure to include it in my search query.
