### ISSUE TITLE
[Feature]: Make dotnet CLI the default installation method.

### ISSUE THREAD

**Issue by JonDouglas** [NuGet/NuGetGallery#9288]
### The Elevator Pitch

.NET continues to evolve into its 3rd major unified release known as .NET 7. However, the default installation method is still "Package Manager" which is mostly a Visual Studio / Windows concept.

There are some challenges here. The first is the expected tool to use. Developers on Unixy-systems won't have straight-forward access to setting up a powershell instance with the NuGet package provider installed. This makes copy/pasting not so straight-forward for new developers to the platform.

Another reason is that much of the Microsoft Learn content uses `dotnet add package` (i.e. https://learn.microsoft.com/en-us/training/modules/dotnet-dependencies/). Seasoned users will generally know the syntax or can use the functionality built in today to return them to their preferred tab.

<img width="861" alt="image" src="https://user-images.githubusercontent.com/1288848/198395683-9f0835e5-fff5-40a6-9bc3-f984fc6cd27d.png">

Pitch: Change the default to `dotnet CLI` as it's the most cross-platform friendly installation method today.

**Comment by joelverhagen** [comment]
This change makes a lot of sense. Based on the data, the ".NET CLI" tab is the most frequently switched-to tab, and the 2nd most frequently copied. "Package Manager" is the most frequently copied but perhaps that is because it is the current default.

@JonDouglas/@clairernovotny, what are your thoughts on these specific actions:

1. Switch ".NET CLI" to be the first tab and "Package Manager" to be the 2nd.
2. Make ".NET CLI" the default (as requested)
3. _optional:_ rename "Package Manager" to "VS Package Manager" (might clarify it's just a VS thing)

**Comment by loic-sharma** [comment]
> optional: rename "Package Manager" to "VS Package Manager" (might clarify it's just a VS thing)

Personally I'd skip this. The tabs don't look great on small screens, this would regress further with longer text. Also, the `Package Manager` tab's content has this notice below it: `This command is intended to be used within the Package Manager Console in Visual Studio, as it uses the NuGet module's version of [Install-Package](https://docs.microsoft.com/en-us/nuget/reference/ps-reference/ps-ref-install-package).`

+1 to bullets 1 and 2 though!

**Comment by joelverhagen** [comment]
Thanks for the suggestion, @JonDouglas! This is done.

![image](https://user-images.githubusercontent.com/94054/202310125-f636b29a-c52a-4ab9-82af-4374bb526864.png)
