### ISSUE TITLE
[Search-by-TFM] Users might expect to see computed compatible packages when filtering by TFMs

### ISSUE THREAD

**Issue by advay26** [NuGet/NuGetGallery#9372]
### Problem description
People might expect to see computed compatible packages in their search results, rather than just asset frameworks. Package authors target .NET Standard TFMs in order to be compatible with a range of other frameworks, and their package not showing up as a search result despite being compatible might be a problem.

Eg. People will expect packages targeting netstandard2.0 to show up with most framework selections, since it is compatible with most TFMs (.NET Core, .NET Framework), but since we only consider explicit asset TFMs, a user searching for net462 packages will not see compatible netstandard2.0 packages even though they should. 

### Solution
Include computed compatible frameworks in the filtering experience.

**Comment by jodydonetti** [comment]
Totally agree.
Ideally I think a better option would be the ability to choose if "direct" (or "target" or "explicit", you get the idea) and "compatible".

Compatible should imho be the default, since that should be what most people would expect for the reasons highlighted by @advay26 .

Direct (or whatever) can also be interesting though, for both research/analysis purposes or to search for packages with specific targets or optimizations for
a specific tfm.
