### ISSUE TITLE
Revoke button besides delete button for api keys

### ISSUE THREAD

**Issue by erdembayar** [NuGet/NuGetGallery#9426]
### The Elevator Pitch

Hi.
I would be nice if there's `Revoke` button next to `Delete` so I don't have to delete the key after finish uploading the package.
That way I keep packaging globing pattern for next time. If I delete it, then I have to use my memory muscle to figure out correct pattern each time.
![image](https://user-images.githubusercontent.com/8766776/223483195-2d359990-dfe7-4873-bb43-09df3f654f62.png)

**Comment by joelverhagen** [comment]
This is a reasonable idea, @erdembayar. Thanks for taking the time to suggest this.

It shouldn't be too hard to implement. I believe we would just make the button set the expiration date to 5 minutes ago or something like that. We'll keep this issue open for tracking and to collect upvotes.

I've put "help wanted" on this issue since it should be relatively straightforward for a community member to implement this.

**Comment by erdembayar** [comment]
> It shouldn't be too hard to implement. I believe we would just make the button set the expiration date to 5 minutes ago or something like that. We'll keep this issue open for tracking and to collect upvotes.
> 

I would prefer an actual 'revoke' button instead of a '5 min' button. For instance, when publishing a package, we may require someone else's approval even though I am publishing it using my API key. We don't know when it will be approved; it could be within 5 minutes or next Monday.

**Comment by joelverhagen** [comment]
Certainly the button would say revoke. I was referring to an implementation detail of how to mark our credential DB records as revoked. This can be done just by moving the expiration date into the past.

**Comment by mert019** [comment]
Hi @joelverhagen,

I created a PR for this issue. I am awaiting your reviews and comments eagerly. 😃

**Comment by agr** [comment]
Out in PROD now. Thanks again for the contribution!
