### ISSUE TITLE
[Feature]: Make NuGet.Server support .Net Core 6/7/8

### ISSUE THREAD

**Issue by CuteLeon** [NuGet/NuGetGallery#9430]
### Related Problem

[Feature]: Make NuGet.Server support .Net Core 6/7/8

### The Elevator Pitch

[Feature]: Make NuGet.Server support .Net Core 6/7/8

### Additional Context and Details

[Feature]: Make NuGet.Server support .Net Core 6/7/8

**Comment by joelverhagen** [comment]
This is a duplicate of https://github.com/NuGet/NuGetGallery/issues/9430.

NuGet.Server is in maintenance mode which means we are not actively developing any new features. If there is a critical bug or a security issue that must be mitigated in the project itself, we will act. Otherwise, we're limiting our investment in that area so we can focus as a team on supporting nuget.org itself.

If you're interested in porting NuGet.Server to .NET (Core), feel free to open a PR and we will review it and consider merging it in.

Otherwise, I recommend looking at the list of other private package feed implementations:
https://learn.microsoft.com/en-us/nuget/hosting-packages/overview

I know many customers have succeed with using BaGet which is a .NET Core compatible V3 NuGet server implementation. Note that NuGet.Server supports only the V2 protocol so that may be a change for you depending on the client software you are using.

**Comment by CuteLeon** [comment]
That's great, let me have a look at BaGet. Thanks for your reply.
