### ISSUE TITLE
[NuGet.org Bug]: More Download Count Issues?

### ISSUE THREAD

**Issue by SoftCircuits** [NuGet/NuGetGallery#9531]
### Impact

It bothers me. A fix would be nice

### Describe the bug

My SoftCircuits.Wordify package has been climbing quickly in download counts relative to my other packages. But it seemed to suddenly stopped climbing.

As I review the package information, it says the package averages 11 downloads per day. But the download count shown on nuget.org has increased about 10 over the past month.

I understand that people just may have suddenly just lost interest in my package. But then why does it say I'm averaging 11 downloads per day? Clearly something is off here. And I know there has been issues with the download counts in the past.

Is there anyway to get this checked?

### Repro Steps

View the average downloads per day vs how fast the total download count grows.

### Expected Behavior

I expected the total download count to grow roughly by the average daily download count each day.

**Comment by agr** [comment]
That "Per day average" statistic is a "Total downloads of all version / number of days since uploading first version", i.e. average over the whole package life:
https://github.com/NuGet/NuGetGallery/blob/0c62a31f83c699beb4797f620a68b62c76eb585c/src/NuGetGallery/Helpers/ViewModelExtensions/DisplayPackageViewModelFactory.cs#L102

~4.4k / 386 (days since 6/22/2022) ≈ 11, so the number is technically correct, but now what you expect.

**Comment by SoftCircuits** [comment]
@agr I did not realize this. Thanks for the information.

**Comment by agr** [comment]
I do agree however, that the utility of that statistic is questionable at best. That was brought up a while ago here: https://github.com/NuGet/NuGetGallery/issues/3973 but the issue didn't seem to get much traction.

**Comment by SoftCircuits** [comment]
@agr Yes, a running average of, say, the last 30 days would be far more meaningful.
