### ISSUE TITLE
[Self-hosted Bug]: Error 406 pushing SOME packages to nuget server

### ISSUE THREAD

**Issue by weloytty** [NuGet/NuGetGallery#9539]
### Impact

I'm unable to use this version

### Describe the bug

We have an internal nuget server that our build system uses, and when we try to push to it, we get the error: 

![image](https://github.com/NuGet/NuGetGallery/assets/3042440/9e67f859-c66a-4c53-af5b-696f5a098be2)

on the client.  I couldn't determine what was happening, so I ran the server locally (i.e. in the visual studio debugger, server installed as per https://learn.microsoft.com/en-us/nuget/hosting-packages/nuget-server) and get this when I try to push

the specific package we are using is https://www.nuget.org/packages/Elastic.Apm/1.22.0

(and one that will push successfully is https://www.nuget.org/packages/Elasticsearch.Net/7.17.5)

I am not sure if the problem is with the package itself, or with the server, but I thought I'd start with seeing if I can get any further information from the server,

I get the same error if I drop the .nupkg into the packages folder on the server

### Repro Steps

Steps to reproduce:

1. Install nuget server as per https://learn.microsoft.com/en-us/nuget/hosting-packages/nuget-server (I am using v 3.4.2)
2. try to push https://www.nuget.org/packages/Elastic.Apm/1.22.0 to it, using either
nuget push
dotnet nuget push
or
dragging the nupkg to the appropriate packages folder

all give the same result

### Expected Behavior

to have the package successfully pushed to the server

### Additional Context and logs

```
`The thread 0xa184 has exited with code 0 (0x0).
The thread 0x6330 has exited with code 0 (0x0).
Exception thrown: 'System.ArgumentException' in WindowsBase.dll
Exception thrown: 'System.ArgumentException' in WindowsBase.dll
Exception thrown: 'System.ArgumentException' in WindowsBase.dll
Exception thrown: 'System.ArgumentException' in mscorlib.dll
Exception thrown: 'System.ArgumentException' in mscorlib.dll
Exception thrown: 'System.ArgumentException' in mscorlib.dll
Exception thrown: 'System.ArgumentException' in mscorlib.dll
iisexpress.exe Error: 0 : System.ArgumentException: Part URI is not valid per rules defined in the Open Packaging Conventions specification.
   at System.IO.Packaging.PackUriHelper.ValidatePartUri(Uri partUri)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ProcessOverrideTagAttributes(XmlTextReader reader)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ParseContentTypesFile(ZipFileInfoCollection zipFiles)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper..ctor(ZipArchive zipArchive, IgnoredItemHelper ignoredItemHelper)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at NuGet.PackageHelper.GetManifestStream(Stream packageStream)
   at NuGet.OptimizedZipPackage.EnsureManifest()
   at NuGet.Server.Core.PackageFactory.Open(String fullPackagePath)
   at NuGet.Server.V2.Controllers.NuGetODataController.<UploadPackage>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
The thread 0x4f44 has exited with code 0 (0x0).``

**Comment by joelverhagen** [comment]
Hey @weloytty, thanks for taking the time to report this issue.

Essentially what you're running into is a shift in the NuGet ecosystem that has organically occurred over the past decade from pure, compliant OPC (Open Packaging Conventions) style packages for .nupkg to something that is more custom and NuGet specific. What I mean by that is originally NuGet packages are were expected to conform to OPC standards because of the simple fact that NuGet code (both client and server) used OPC libraries like System.IO.Packaging to interact with .nupkgs. Over time, this has changed. Most notably, NuGet client 3.x and on have treating NuGet packages more like ZIP files that must have a .nuspec instead of a proper OPC container. This has allowed non-OPC packages (or non-compliant OPC packages) to leak into the ecosystem unnoticed. And, I would argue, that's okay overall. But users like yourself get pinched by this shift.

The reasons for evolution this are varied but suffice it to say that NuGet 2.x (notably the NuGet.Core library which NuGet.Server is based on) expects packages to be well-formed OPC archives but NuGet client 3.x+, NuGet.org, and most of the NuGet ecosystem now do not hold packages to this higher standard. They pretty much need to just have a .nuspec in the root of the ZIP directory and have the .nuspec meet some minimal expectations.

For this specific package, the hint is in the stack trace (thanks for providing that by the way). The line about the content types file points us in the right direction:
<pre>
at System.IO.Packaging.ZipPackage.ContentTypeHelper.Parse<b>ContentTypesFile</b>(ZipFileInfoCollection zipFiles)
</pre>
 
If we look at the content types file in Elastic.Apm 1.22.0, we see this:
![image](https://github.com/NuGet/NuGetGallery/assets/94054/5970f9a9-c1de-4ae0-bb63-7a86fd73a458)

I am not an expert in OPC minutia, but I think the paths are malformed. If we delete these two entries from the content types file, the .nupkg is read fine. I don't know how the .nupkg got into this shape but it's possible the NuGet client's pack behavior (which still is best effort OPC on the pack side) is making bad paths. A minimal repro of the failed consumption side would be:

```csharp
using System.IO.Packaging;

using var packageStream = File.OpenRead(@"C:\Users\jver\Downloads\elastic.apm.1.22.0.nupkg");
using var package = Package.Open(packageStream);
```

This exhibits the same exception as shown in your question above.

So, what does all this mean for your workflow? Well you have some options:

1. Move away from NuGet.Server to a more modern server implementation that is permissive to non-OPC compliant packages. A list of alternatives is here: https://learn.microsoft.com/en-us/nuget/hosting-packages/overview. I know many people have had good success with BaGet and Sleet (both implemented by former NuGet team members by the way 🚀).
2. (scary) As part of your ingestion workflow (from NuGet.org to your NuGet.Server instance), edit the package to remove these two bad XML lines. This is problematic for several reasons, such as breaking the integrity signature that in the package, so you'd need to "unsign" it by removing the .signature.p7s file. I don't recommend this solution but I'll call it out for completeness.
3. Pursue a conversation with the package author so they know about the compatibility problem with NuGet.Server and NuGet 2.x. They may care to fix it on subsequent versions. To be honest, this would surprise me since this is an edge case w.r.t. to most users. As alluded to above, this might actually be a bug in NuGet client or the package author is doing something custom to produce the .nukg.
4. It is theoretically possible to patch NuGet.Server to handle this case but moving to NuGet 3.x client libraries in NuGet.Server would be a costly endeavor. Frankly, I don't recommend it since NuGet.Server is in maintenance mode for us -- meaning we'll take PRs for bad bugs and we'll address security issues. But refactoring or even reviewing a big community PR like this would be difficult to schedule for the team.

Let me know if you have any questions.

**Comment by weloytty** [comment]
Thank you for the help Joel, it clears up a whole bunch of things.  Luckily, we found an alternate method to house our packages that makes them available for build, and we don't need to run our own nuget server anymore, which is a relief. (Not because there's anything wrong with running our own, but its one less thing that we have to manage and take care of)
