### ISSUE TITLE
[NuGet.org Bug]: Create a new organization with the name "" failed

### ISSUE THREAD

**Issue by shenxianpeng** [NuGet/NuGetGallery#9626]
### Impact

Other

### Describe the bug

I would like to create an organization named '' but it failed with an error: The username '' is not available. It seems this name has already been used, but when I tried to visit https://www.nuget.org/profiles/myusername, the page is not found. 

Any suggestions? Thanks in advance.

### Repro Steps

1. Open https://www.nuget.org/account/Organizations
2. Add new 
3. Fill in the Organization Name and Organization Email Address, and click Add 
4. Creating a new organization failed.

### Expected Behavior

Create a new organization with the name '' successfully.

**Comment by joelverhagen** [comment]
Hey @shenxianpeng, we typically try to do user-specific support requests over email. Most often the problem is very particular to individual cases and the conversation can include PII (which should be kept out of GitHub issues). Please sign in and create a support ticket on this page: https://www.nuget.org/policies/Contact and we'll help you out.

The general case here is: **when a user or organization is deleted, the username is kept in a reserved state.** This is to avoid impersonation attacks.
