### ISSUE TITLE
Some old packages are missing owners

### ISSUE THREAD

**Issue by jeffhandley** [NuGet/NuGetGallery#974]
We need to determine what to do with packages that are missing owners.  Some really old packages are in this state.

Here are a couple examples that have been discovered by users recently:
1. http://nuget.org/packages/Migrator/
2. http://nuget.org/packages/MarkdownSharp/

With the following query, I found there are 59 ownerless packages.

``` sql
SELECT  Id
FROM    PackageRegistrations
WHERE   NOT EXISTS(
            SELECT  *
            FROM    PackageRegistrationOwners
            WHERE   PackageRegistrationKey = PackageRegistrations.[Key]
        )
```

**Comment by skofman1** [comment]
This issue is still relevant for a few packages that are very active. @karann-msft  can we try to track down the owners and ask them to take ownership?

https://www.nuget.org/packages/MarkdownSharp/
https://www.nuget.org/packages/NDesk.Options/
https://www.nuget.org/packages/CommonServiceLocator.WindsorAdapter/
https://www.nuget.org/packages/NVelocity/
https://www.nuget.org/packages/Castle.Components.Validator/
https://www.nuget.org/packages/Argotic.Common/
https://www.nuget.org/packages/Argotic.Extensions/
https://www.nuget.org/packages/Argotic.core/
https://www.nuget.org/packages/Argotic.Web/
https://www.nuget.org/packages/Mvc3CodeTemplatesCSharp/
https://www.nuget.org/packages/NUnit.Sample/
https://www.nuget.org/packages/WCFExtras/
https://www.nuget.org/packages/OData.Helper/

For the full list:
```
SELECT  *
FROM    PackageRegistrations
WHERE   NOT EXISTS(
            SELECT  *
            FROM    PackageRegistrationOwners
            WHERE   PackageRegistrationKey = PackageRegistrations.[Key]
        ) AND (
		select count(*) from [dbo].[Packages] 
		where PackageRegistrations.[Key] = PackageRegistrationKey) > 0
ORDER by DownloadCount desc

```

**Comment by karann-msft** [comment]
one down - [](https://www.nuget.org/packages/MarkdownSharp/)

**Comment by skofman1** [comment]
I went over the list above again, and saw some of the packages have new owners now, which is great. I don't think any action is required here on our part.
