### ISSUE TITLE
[NuGet.org Bug]: Number of downloads changes among web and mobile.

### ISSUE THREAD

**Issue by meokullu** [NuGet/NuGetGallery#9784]
### Impact

It bothers me. A fix would be nice

### Describe the bug

On last view, I realized number of downloads don't change on web view and I was suspecting if there is a problem through data. Then I checked, new versions of packages' download count and check mobile view to see same result. Interestingly, mobile view show correct number of downloads while web view doesn't.

### Repro Steps

1. Open URL on web view. https://www.nuget.org/profiles/Okullu
2. Open URL on mobile view. https://www.nuget.org/profiles/Okullu

### Expected Behavior

Same number of downloads on both usage of same web site.

### Screenshots

Mobile view:
![photo_2024-01-23_17-36-22](https://github.com/NuGet/NuGetGallery/assets/4971757/cd22f130-df9e-410c-b74a-ad176073bbd1)

Web view: 
![image](https://github.com/NuGet/NuGetGallery/assets/4971757/f30d0759-dee5-4b32-ac6e-f86a48ee1a07)

**Comment by zhhyu** [comment]
Hi! The statistics is cached in memory. There is a chance that different instances have different versions of download counts, but it is eventual consistent. That's why the number of downloads may vary when you initialize a different session each time.

This is a known issue, and the infrastructure needs the iteration to solve this problem.

**Comment by meokullu** [comment]
Interestingly, for a long time I wasn't seeing this difference. Web version was eventually updating, at least once in a day. For significant amount of time, it wasn't refreshing that's why I wanted to create an issue. Thanks.
